### ISSUE TITLE
Carrier swap issue

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#6617] opened 2022-04-26 11:32 UTC
OS: Android 12

ver: 4.0.9 APK from github

Device: SM-G970N

mod: (none)

savefile: [Spain -  161 turns.zip](https://github.com/yairm210/Unciv/files/8562428/Spain.-.161.turns.zip)

Description:
- When i swap 2 carriers, their air units are not swapped.
- When i swap 2 carriers carrying more than 2 air units, game crashes and shut down without any seconds.
<br>

Please refer to this video.
video: https://youtu.be/m16YE0FRyVw

I've started new game on custom map without any mod. There are 2 carriers, 9 fighters, 1 jet fighter. Carrier's name is different, and only one of it is carrying jet fighter.
![Screenshot_20220426-194503_UnCiv (1)](https://user-images.githubusercontent.com/64586749/165287979-17830cce-de71-451e-96be-fb450e8708f1.jpg)
<br>

Watch when i swap them. Carriers are swapped, but their air units are not. This is what i wanted to report at the first place.
<br>

Give [ Flight Deck I ] promotion to 1 carrier, load 1 more fighter, swap carriers again, and then it crashes. Game shows error message then it shuts down in no seconds, so i could only capture partially.
![Screenshot_20220426-195025_Video Player](https://user-images.githubusercontent.com/64586749/165288007-07a56502-4574-426b-9da6-5dd0e1d79a96.jpg)
<br>

After watching error i restarted game with autosave, but there's no "floating on nowhere" issue this time. I guess bugged data is not saved, or my city is close enough to warp.

**Additional context**
Related issue: #6584
My initial report was 2 carrier with 4/4 air units on very big map. Now i've got same bug with 2/3 carrier on very tiny map. I'm happy the problem is not my device.

**Comment by xlenstra** [comment] 2022-04-26 11:34
Duplicate of #6584, which is already marked fixed for 4.0.10. Please open a new issue if this problem persists after we release that

**Comment by saud2410** [comment] 2022-04-27 11:39
Android 12
Unciv 4.0.10 APK from github
[Spain -  163 turns.zip](https://github.com/yairm210/Unciv/files/8571618/Spain.-.163.turns.zip)

I'm back :)
I mentioned 2 symptoms. Crash issue disappeared on both small map and big map. Thank you so much! However, deck planes are still not swapped. It's not game-crashing problem so, maybe tag should be changed to "feature"...

**Comment by JackRainy** [comment] 2022-04-27 20:28
Ouch... Thank you for the saved files to reproduce.
I had an assumption that it may happen but probably did not test it enough.
If you dismiss one of the planes on the deck, it even crashes the game, so I am back to work on it :)

**Closed** 2022-04-28 11:31 UTC
Labels: bug
