### ISSUE TITLE
Free buildings stay free when their "Source" is gone

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#10107] opened 2023-09-12 09:24 UTC
**Version**
#10094 branch

**Describe the bug**
Conquering and pupetting the city with CN Tower will:
* Not affect already built Broadcast Towers for the conqueror
* Give other conqueror cities a free Broadcast Tower immediately
* Selling built Broadcast Towers will give you a free one _next turn_
* Victim cities will all keep their free Broadcast Towers, 

**To Reproduce**
1. Load attached game (yes heavily cheated to get the required situation)
2. Select one of the McInf's around Carthage and attack
3. Check Mecca: Non-free BT
4. Check Medina: Free BT
5. Next-turn
6. Check cities: Free BT

<details><summary>Saved game</summary>

```
H4sIAAAAAAAA/+092XbbuJK/wtHTnTNWrriJkt8cp51kTpx4Yvdk5vj4ASYhi7clUkNSSbtz8u9TBXBfJC6AJKdzl25TogpVBaA2VBW+j77SIHR9b3T+feRt1480GJ3rZyM7oCSizhc3WuI3Ef0zGp2PjFezV/roLH1xrqo/fsDL7ld35f5FIoATjs7vv+MnH8mawk9ek+CRBC6BL84AjB2Ds5fhZxpSEthL6sBPRlcr92kZwTu/ragdBb7n2viLT5uI/3EbUbJWbvxvMO7Z6ML2t2H8zaW/fsQHoOFs9HFrrwCqcrUN+QfX/qO7osodsePXP/uPfvznteu53hN+RtxV4BOHDQR/809/c7Y2ieF+ICHwCUdGjINnHHcbBNSz8c/XZLVyE3zebr2N/81heF7RIELWsIdrGpGVckngRQ7f9j1/nRDhhVGwtePhcBQXuBRtA4qPEb6n3C2pH/DxvD84jDsK7PLX6y3wK+Y/48iGhIxYulkRm5JHYMENCSL87J0fhPSR2H8on12HQ0EWuh51lItgzQAs6RroYWO99xzgLsxgMsOMRxEFiiOKL7+GyfqLKl/8IMYJp2oF6wb+sl3qRe4ij/vN0l35ob9ZsgfAybURueVzmE7nZhtxZr8JyJooxHNg4ilH5xrYGZHgWWGwbeTOTeB6yFLlJqCM6msSAQEknQ93xWb2teuv/KdntgbsPxJ4BDjt8Rn9zXuCP2nAycA5IDT5CV+Wru1G+PTm2SNroJ+tHYfg7N74UcTBXDzBe9tVPHfvgT055nx2F/HyQo7EwD+Sr+4TKS9hN4zX8NuV/5hn/yVZUY+PCqO7Pl9LMaxrEvoewwPmga4YxxPe3gVks4mpc74SYJ+jFNbu5dL9Slbs14Ce8mXJIVx47hqW7rtt+AiTwb7+ErjxMr7E3a/c0uCry6aDLfPVNuCcpovAfaJBgvrNiiRjXYS4zf01Z4Dno1DwEipuliRYw8rdwstkFY4eQMxs/BXwH9bc+XcudPKbJv70/7Y0jK6JR55QPuEnAQXJAi8UPnzyVw71Lp4YsFEY+QF13jHe4Ao6n07wHRSBN9TfrCj/EQ03AAeAFEAB1fDz5+KYW9cLC59ETP6Q1cX7GNafmxUO+pk+ceELcvT7CDbrMw3unjcoOd9t1wRZhriOzrWJMbdmZznJegl7Zwkj5ORqQDeAM0zLXVnAamejkG+YTwuQZdHsbhswWW1oZ1PrzNLPLPNspp7NzbPJ2eTh7OcW0Vdb3JwKcumXwP4lsH8JbAkCOxYhd34iRJgIyW285I333k3gP7GVACIs/8a5YWk/ioI/ltWX8Wydq1P1bEQcfwPG6k362v3o1ge7lrpPHpv9axrYxMONHa75oxv5dkCYZLgKKIy39LdcuH1wwbSNnhVc1ivKVswlcO4v6oVLd8PX+xrgUb5bAW/YMQm3PrM/CI6TBxDDxL2MQp1jkdtrn+lXf7VNYNDN9hEoKYLji8Ghyu9eLDRuKaxZMK3Zd5f+Cte7+5Uqn7egsB4SI/3T4qLMnalY7RmhJvlAF9GVH3CBG71NXgDFU9GkMJ2w/UN4+yN4FW/5dwHsgUt/60VsjBH+316hSDwf/Yt8Ja9WxHt69R6+fmKSGdb8Fmd/MvmRwUcYNwx2DhKDr+ACWMIKaAl3BkD5Dy9A3IXtf5Yg85aChCIrjg0wQR1oPjgumAtrXK+AyUVAHl2Cf/kgNoPL1CKIvzgbLVbkiTPB8b8x1+6WRtEK9g2sZBp+hP34O6IF9sQbaq9Qk9xQ2LywNvgnBPbYF5BXbK3Eg8PGvvYdWK8o6gFk7r1PHoIbq/NXJggaElz7HqCOyI/1H2wHB/6f7hpFcQ7/0UfYoMtH0G4jeMUjsJDI6ovvOWyA+9GnlaNcEfBAF9sVkxYlGwokEO6evNsJau4JtdY5YsEMI+a3XngKTMj6WbmPVZ3y2sfN8aD8436sGw/Ku5t/V5YkVEgEg/wBQvY+sa74KxP2CgB0bT7WqAgIzSCci/f49T9v3NWKG2bv10D5V7qGPcG/ggl4VmzKVieQROwM+Q8+J+WC2xTAqFX8Cf79J/ASjDggzfjBbMW9r5vs7TF46D8e8Af7mXNNcZOAqHOU994CtkvwzMmf1XHonbvZ+AoasNuQvabpFS7VQDwMq2LitZa8GhvCmKXN9y6n+JWTYFS3NTVW09eHrinrZ2YTf10XwCb1Z2YTX02mADZNf2Y26bnV9FDSex/8JzYoWmFgEO3Rilz/Z5zNsQhZR//cgLsA7HCjUAHFjJr434pajyT0xxZ4V9rVlJYOG6lO3uwh5SkAy6cB9xt/A5YzG2bA1JURepPaaClOXyjgAiY5+L3cIsVVyc2fhwJuqeWWW3wZvM5IGpn2K2MJvpaTRi1S1n1U7jBsw1n3SKmnPIITHimul9tFeYRfo48O7mS8GOLfD9wJzDH1N9RxSe4XrvcHspLZhdlI7ShDN57RFEZABXAfXPt79uFrn0ThQ8P6yCCVCMJdn6FmxwZttkfHdbKsslJ/j1zwtHLMhlE98N4Av8hXnv1toNhk44JX3rCA0b/qzusdKLbm3W3kezx0JJJ5ZvN6rTCvaHYemIU7EG3NwguYe3xTHP+4TOW2K0OLKwPt5JVBL6vqRSiDnXv+AJyNTatxa0XbRX5Vt+AhKGq9TLpIk7fEoQekQW1JQ35H77UyEouCUeHEURnlGwlQ3GyLNNQat7H1MdTxrXNVUBDfX5PA9WjeUO9phXNAPcWM1ZL3/O3pcKdErQubVBgyKGjyghiCXACVjPsm5gJqR7A5e5LOf92N9I6hi8os7Z5KTatOJZ+fY86enr5dJvt3z43ysjCh5QHmCRwAqoDLu/bBbPm3GpJKSF+TDYJrh/MNh1v8gcdj2CnHGgFwC4fj/P1//a2yJuCJL30/pApRFniaw846nn98V358d7YULUI7PezwnsCKfXY8+qx82tCAKO/8bUgffuyR9CflbDTbHbXuXQ25PR29KiT5Ll/NmMMk0Tecog2e/jpIN25jcM3xSJBJm926sk5C9YuB7A173YPQ4XRscacq4PbSFHEPT5y7oN5Pyky7hfI6GGn7qP9f5sNhlC21nZlY8tePJAAvb0k5cwrCaWeYriCFLwM/DJfEDV4LdaSbSCiazKdCSMFSznmO+sl7joz5v5xGwUzVfjqn0ewqlk7Wd8wOAYY5kHUWwiXmL6FlRJT7Kz+gYRTb6zwLXLnXJg9K9kNl4QclkdbVtmk9E2095l0zJ8NvM6opAfL9ts4bVMuW/1CmmG2c2dnfiCmn4NBmhz1D1/2pUNP55Lwmo8esW6vF02C1ehr8t8roaZGkYr7Y8/LmJJVObntp8R/UZc+FDVq76rUI8p3IQXUN2rR31RHMP3MDndTxWNeDz33Mj61yuazP4TyY98WogrEjqtAxHNIv8NE6pqB1NN61TiZy21y2nBefCchT8eCbxcqLDKbkYhDGyccgusXhX1Igor2pNZ3sN7WqR35/J1PLaJHBqf6EplZXNu232evO114Umw6U6Ppy2dTs/L0ow71LIuUOy7HKcAkGe20q5ckYjDn5sncBdbcsO1qKQ7dv/tyx8/GdmJPHxNraq9d+MqP3ZR2/mS/E9P11BicvcbM1b0//DG7akaLTPYMzBJ3BvcTAvMDgcwuP6GcMPr/EWdcbLfKu/p32M0+6MDb92hvt2FRbkV5kk/XC2TSoTku4G9yx8qlQKFbnDHfLHjkr56Fm0If2BtjlJSeDFsbb5y6bL8NdLoqtjuuyXU8FwdXyv3zSw/ukD9gqKOJNlZqJBiwdIM5ePKqWrk7Ghon/MJz5mNgGGdvGo+44mjmbqI+jsyTTP9e/buFvPdxnsBeLXyx5Y7JzVcMuUKm/d/698KSqCMJ3bllvqNH5dM46HEXPl36xxdGIyZ9kV3Od4HtbZOkI228Rx91iN6WL9WbpAj8JZy12b4N/vSMBuBUjbOf0tIyWLBOddV4CblP2u8/UfsZ2Ok/KZTItNdnrAD8+42ZRHQd72igfCLLmhnV+Um6xnAH7eOEBiXK7pCsO7CIIqUfwiy+u56xBSsSmXbj0sTXVOz9kNa+jXNu114QN+TYgHom7jPn2H8pvf6IujMu/1nGXOmywZ5Mwimussd0bdqPLg7uwweNa875loGIixp4gAA3MewHmyfzdc1l32ShuT0Yi1mAtreFGhvHeYDH52GpvxYbbxhy9pWTjB3FfroAT8IWseIMxN+0cVpno2N49n2IrJzv37X9tKbZqus9ZxFgykq4JgPjVBS/yKvDXd0s3vIx1YKu1zeI0lT5Rt1HcoC5uE1XhMxMY+38Wrz/YlbyBJPGSxr1x87pk/WvWPNe6a1RsXskfI3cV7+kshcxAPDK1oCWPRuzHnhXO8M++c6F99j39bfJ5piu04qNefDSKj+lvtcKAWuFdteZJL2JaQlwvkqUWRykNahQf9eKjVgRVglzi37SAv5V8aRaxMIuAzSJgsw6wWUSq9GgVqTcLnCo+WQUMzXgKk39nGBenqfRooY74hpvJuUsXVXUlJAumNOe7F4jVhQ9WAw8TPnBV9nzx/sq3t7jVrkBl8L9BlISfAtgtIFwveduA0TlIDFrXSg1kFihxm76ha+LBbtMnXMTw9gN3fgwA7Vg2DMJhW7wxcherT2qrc2s+NceUOBaImOl8/KhO9LEx0eePCwL/cXLqk8cldylPDCZf2P+3dZlQUHdpULOoQNV+CrSsNivqZKciTfVJXqPmdEumQHIaL9MKiYLbrRdSzXtuTpo0Q/pOW93QauJORTeYfVTDuCQmx6WtmH2vl75P+xAUf18SnePSXs6ejdJzGh6vkTp1+Kj18Mr0VMfbKS72SwXV7CkVUgM8lgrzOZ3NbW0ynqozZ2zMHG1MiAqGh00fZ7PpwpzrWiYV8k5FJ9mQWtqW1UFQaNapCIq8hy5ebCTmJBeMAszJVrP6QkXGtLTF096KxedU9U9Lz0ZRkY9LxtG4ZB2NS7ZU9vvpHlkxLe39MvwyYuXxEjt1oKjQehoQyflSLCicyUSfGjM6nk8IQd1jjB8XVB/bC2tuPurmRFWdTFCwgzM51oOuShUKLTf0PoOirZ1giLMTWs1Q300vehunq+t7wUtINkPRHdQK76ixrZ9ulOSPotuUuGf1u1Mrj1/8cc5fELEHVX33HlyQFfYdSMNhl7wykhFRucthFPkbbIid7NMJ5xEupEc/ivz1Z3aRQhJVncRihvWyxnbrt5R6uWgfm8t4Rdj++tXWs92vr/4V+t6rdyRcXpPNf1NsIo1mALwe8GjdfcWtbbGq8iFFIPa+4sG1gHFNvO2CsK7WORh5O683InmF0BdItq6HMsRqCePKDZcYE4zLM8osacvXJjC5oEeb2cESy+zHuTBHix/fwOLEvIkfDw+wVJck/O0rDT5986jT4D1HPjzE2RbYHt4HRobYEd1QDQbgGta4c7GNsL84dXhHmvi3Iey98J0bsoUEW0DFf9zCTw1YBh9Zq/LL0fnsbHQD1AO0t+ySFMsAku6AJPjiCl4yTHh+hxsc9AW8DpvtIt7uWgzQwh0IADWdQdQsBnI6SUFOTQZyqjOQpob3sADIeQWinkCcTjlEg0PUOUQ9gTibTDhEi0E0VNNgEGcFiBhXNxKIFidaMzlEs4TjzIxx5GTrM4uTbVUgmgnE2YxDnOapNucJxLk6YxARUB7itASRnfHsvLhmMtG0/MU1abPT/dfWqDuurTGsM2AbsHA6xztrft1a8+vWml+31vy6tcY/+q016pxZcjturdFQ2tbcWlO8mAbve3ETMTHkVpoUUP2dNLkLZy4C1LcJAh/oU3L3zCeQosgO9jFPs/xtxVcmuHDJN11uoWHxseotNEVPCj+YLUx14RjT8cIxF2NDs7UxmU2dsUX06cwimkUezbZeU+qytTR4Ck3H0OZB7NApqPh6iGk6v+2QaUVYNuqG2ijiakfO3FWxQ/+QcicQmkov7k6gaQq1dLmPOhl0uw/z+C6XPmzYz/QbCRwmCWBcggld4VLxFwqzpHAhFO4BSoM155WbgPK5FS3vApq2uAuIibX8VT4ZClIv86mkfV9T2yYHS/tOTh8Hl47uokNSqUM3bECwHI6tydnMrFM+fVIp3nAPxs51dNSunTtm4ojNMURgVcwoOi3cWLLQaaHED15OC6csVeu08OIZYaeFE8+XOy2cComDp4Vavu3wSSGWZEueFlZxxuNpIZXP0zwtzHL5s6eFWJyre1pI8bzaE8OplFp8WtjlM7BPC7M4Xf0gSLW92yytyyi4CjlvVM79ZiWUHDe02f3PgFHe73xocGDesXAlhvK6YpJk+u69XOH7W8Ii3/fqQ1qcxQqE/hH+e/6eAhYUZHcU5MJ7xcsJ+rUGmZZ4hRcnxPPH544oPEKjXDzRrnzaVUN1t418DOv/MwM/KqLCLnFgaBSQqGdLMbjZdG1DDtMO88IDI3snphjkLKHAQXSdnXJ1XVIIqdzzWFVyZJAvpfMDj1XS8RhCYcqKP+oeMyg3pOh8reRh4zOztH7s5cdnfvorGe/xpOpbY10o5/henVYuCE2BDpmAdvRmQw29b++wu0TLwmc/zzb5G1xtU7uJPv25gEWi5MI2AjdTBbj8TVUdck8hbWLrpU0yiPJIAvifS7B7gE3WG8ydY6f6AU3NQWxGiacpIm8FLd2wVbYs/sOcMavmgZkTi8BfswJfdgzUYL4MQGNWQiP13P2Fcp87po5bjMTnwU38SLIfSrgggAwPPA+Pz53y5+BD75Q5xhnPz2FDtOirUbm1jnWncygmSzzj7ZFLTG7irTXQ6uU3PTTdDdH13jsRnez6NYcet20ueb9PpcSHZd2F6wAFU+wN1qpzRXfdcohjlOJRXiYkOjd9PqyQUDM37aeSEqdyEty2l3Zp+exsUpEV7fAyGYOqtqkTe2zNqTU2FoY1fqS6NSa28zjXnMnCJvNRWibDpmVULpNJM1iTqjkdE3J3NKiYlOpreXWgvA4VmY9yNrqKc/G79a0Y3qLiNfmLMO1Tte2O17QCOPjIOkx0bVohrVPFOxqsAcsnmmQS2TxfKv/i+/D3kAa3NEpy42vrkTJImOmIX2EeMEarih/dBZSEW9S5eyqGLK1bH4lSvdysWC43K5T9JJ9Oa56KANTCU/G7pBpIKw6lFhFJin3TwqPCaOmvjGL5YKmM0ah91IqPxUKnFJRe/K1e/K1e/K1W/LZUcF2qn7aKv7WKvzVrH/XiYwLZLH5cQqf4bTpe4dMiYKPwpBUwLOKrNZSATWuZqpdmNVlX5eVWGMisGXYP1wxpHSN41XTfgs+sYUSrLM6cKkOd3qzLigWfeoeCT5inELNTMVk4ulglWDPx1jHLkkUMBBSPcn3YqPAapX9O7WWyP9VkQyrImSrgJTj1BeRcV+wRyd0Ecr75wfMo63qgntU9Jj18Ks0WrNLzbGfJ5tisGSX/uZHbXy02i9azMlM77crMvHDrX/0noprxREpE2xYh7qwvfZHFlPHv2+Je+WFeMbb4PSsHAdo3fhhlQMxu61Fega6YUmEhJbrqEEyGlshqWCTarUR2gv+4xQ4MvP50wko7J6yyMy4VnfKqzgkv6rTiwtMJK+q05qyoE6VhWmyrT3LFthoHpSaFrPpcn+SrbdWpNeW1sVjem0EslNsaOi88tThIlYOcxSDVuaFzkHMGUlMN5AOCtCog9QTkVGUgZ/UgWU+bO2zlwEFOJrNpHmS+hDcpuDV1nYFUjXzBrT6twLRimKo6yVOeh5mU3JpYm4ww4yLeKYNpJLXLvE4WYaaka3x68AcFmD9Q36XnHczAyM48uD6G3e3WHFKgLk21LbbVDDcEV2e8rmCENAjMV9kPXneyWLBiQx40dHlFJNoaoONwhDXZ3JAADE1WUsk/uHX/YrUpKG5QVSODvrkOxkuwInpJua5F4mIT9c71nrF8JL53+gtYdP+NvjhSMTJezV7pyj+YBajMVRUDziFl4ZTp3DAnlm7o2mQe20AfYFcwPjySkN5RMPdcBALGWhiu0LDIrIPXz6UkpdgkfkBTixsjuLlJxD1+jDfghg5GxValhUr1AryPzKwDGyYCfYFWwwQFSmmCEuMKQwBFnG9W8O+wHcIZFjUjruN4CM41jupXqfBjIVVDYOJGJKH9OE5xndpCWhL1Y55SELkLNI/BWFr7qRmcf7rnVvujC7Y34xCrGuO/dGMLbh1Dv6ZrP0gifCXOpfcsVJmafvXACjJrvxvC7tz6+B3cAB6bSz68WONOY/aum7cZC3qCr6fUmk0Kxnuts89711n9Auu4KXausdJo1cE+kD9oW+722ml1y2AoydL2/E7EIv7pFcVqOl4h/A57/j50XZsXq+3a9WoX50wecVkgS5ZAK42YdigasqPlSvcqcuImvAur1BNl1QEXTC39HaRTbqBGBh9Q2GaLbJDM3U3V4fZyzSoQR4VYzf8FA4USDUOtzVI6nOgYZ+GGEj7XqFLwTwFzlHZ7O4YBrw2Zp904D9TpclDXxDC7h6ySy61s8m+XlG7k7VG1BQNraPnPrffE26R0pGbj2kwU7idn0ksFVymRpYKrIwl1EOrIb9bWMq2zPYsxSynJkNeZj5x80cXOHKQ8hXH1AIprHwsnPVjYZB4cg4XDNmJe+/ksw6bs/lnl2ET+dEUOewft+DZGw2Ftbl162K6WyANa4vpeP/6AxmeWpFNC5g0NKUu/EjxiejfOgcbL3aAwyLwWFjzTGxggc1NpTTxooznOMPpMw6i7Ysa0yRohOZVmN2oteFtDZnv6WKpLckrU24gcFPKqUidMUtmYAQ+klQ80UuL3H2fE1dSlcwoYy8EjXZZc0u4UIrt7sZEVxo5ziMH7S5YrcLiNL4QLufW9fWJJWzn7Jt+0E1dh1iKzgXvsROrOL6T8aAOZmrkbO4y7A2rUJt/1iB5D1dTor/vama3NSmi3T3ikjVnIGj4BVrUxvGVHvtpxsbPKSL8oK4y68++yEmmjOGo1Rr2qkGgoFGXn1ZY1xm4SnZdk3Ri/aCky9ziNJ6XZk9W9a+XXTdcu00f2bmhnsp0Sm5PUy0YfTKvfEwNET1dPQUA0pCkHp7X8qb/Evk4YJcVp05rEHAV0hLtS8BWKHOKVviHeVnSXtHwpZu78D6bUzc9KGTy3tr9lbXHej85yD+9LjyNssg8c539+pv/afqVeYntdsz7rcZ1Z9ib89f7JgylR4ulTbExYBY8GOPhX8j6HmEskwobkASk2H7/J4az3kQD1Vr3B0vBi1t1iUhzy7hbLZpOU+CwjtlY+iIgd5cQ2u3MhrPFgDWlentHCSBK0/frEiU4vwyHlWdXiTkNKRzj2Mnq5+EaTIyMzOGRmZVCHCcnxAavj7VnjINfCZfc525lI2GcP7GDUSzlfNRpmQHbMWxrrTiUhNHUkpVHaJ+7beasNjPvG7o7UIO8AcVUJ4kqS5mob7gtRm73wU1uIYfGs7Bc1rWJ56ZOwpW7qnhdQg8IBZvFAEZekp+aekoPbFVdBfWIw6VFFc7B2V/C+50GVGK+zTZbIobxOPfM6LVWU18l6q/wdvc52J0r7PNDkjLHOAW06exLrJPWKbzdmU/bF7dQjNrm9gzeFCto7k7/p3klSWputTH3g3hGUNFuXoVz0DpJ6b9lHSdISfKRkkR2kgKUXOxujekdNJu3D5CGx9cMe65UjNiKNX1Hc7OfViuJjr8IAs98C6JvX/pp48N+yK96X/yIPt0Qd9o6zLozNkc2G00SzjVzpWUggOklGHR42MRskvKjgpUTTMDfgSyyozw6tdizS+tPYXAeYAcH5/AqNfK9qEh01YGo2GH67rKW+kck3NKVw12LV+qijngVYAkkRGGQ1GzzZo9pcRv9pke2T9ytxnKZdtvpHN3eXcEyTRmKlAe62nhOQzuLjk9tQ9dLnxFEi2WYD2UcssRhErbDqA6OBMcetfR7Gm9zBkxsuK8qt2IxMeCVHFfcOGaPl85PCRd+43/LXfPc7/JO4y7QGBvQ+ietT8SyRPrXFZhlSMRLbYrIOzYRJnN6HZjsEsKyeEEMKCGRGFIYa3PvnoN7YPka4fS4sQfLvGm5Pzuab5Z4p5KhqeGBPnjg7vdKC7I6cxvO1+mPtxvrLLuKwKaZ0RYJ1RYjsECB18SX9V6zmvLhnmi2q+ikeN9We9pxigVGZ8na7PIHt1lUipk2Sms/b9Np5aeyuJD3mXpzMQpfo5s28T/uLKQc6hlFgtFb6P0l+SodaqPpz9fS7Tor+JI9p2pFZI1VF9S2TejQ97Ni8hV5vJQaMwSeqTcUnPZ22hvYPWqVHjivUbiRuEHffvu+THRkxgaXgPVxsD6QCTG2dJKRXBJhLnygXIvGfTYJD66Ebd52B5o5AOwgREXzbWUJnlhNNy/5hq2K5TlwVyEnkZdO3LyuCUJQS9YZhffS+SqnQcHbLBgcyA9k1B1RtEslEpbeIjGueniud3FPXeGRVn7QxbVh7h6nAEja1TcJC8LGfvAzEg/KpSka/06H6w8vetbyNbD9Qt88ch6ojHuNscSo9Z6APb6r4CN5lImOoacpyH0qHFUlVTlH7lZ3V4RdfCGlV8PtkUyKkvTUfoTpAmuZw+HUnkdppA7W3nv9NgpAxpRNk7pu+XqlRfbI0JBJpSFyjgw7Sdemk6w2kDzlI75MLUcVAcC5EdQARlmn3Klu9Vzqa2sSlnsmmjdliA2sw1cYj/IGoS0rEkLXsagk+hhsuIhVneMJJtoSHpewUF/GuJkBte30LDDk3tnTY69r17+fQMmta7eHiNTVzOMYqbuwULZy10gr4Bjk7whjZ2MboJTCyqZvUQRh5eoG6XbUrO0tXGitXxMegdt/H13S+VnPstPN8TR28tJpKsI4SORcQg8wHLuDDUZfM63bbtdm/riIuLpgg04xpR6P0UImw45sBNDatQMGkvqg6fKtJagpmyiD9tnuAhIbqEIJpkNYOuFNowWqyGgVTO8hGbjdj1SH60yC5TVUfU8aKfcNGFk9rDRmrwaUUFFuuOUvrs/6q+Albf+MZH2Imbwg+QnUA4UtcIg2WdBqm0mmYNtAg92RBIkHmMIJ2VG+JKYU1pHPAGLgsd8TddxwmSCRIbyBI0DGziHMGiUJAky5lVAE07D5NrjOWq7X9jXFmWcTLXLe1aAvbEo0HN+JsgKbzlaMWane7BklipfC4qRT6iHFsmQ5DU5PrDutNdLRZWOi7f0Sj6W7LY3ClsR3NwbnS1N/nGFwRklEoMIopPc4zLLwmMtAnMc43SLOKoVG6b3wC8ziTHrCdiT0gGUyqxO05E3DMWDl+EUq8xPjtbPhhdbuQlcSo7ExA5kLFIG5Hlcg4bS1VMi3lmfR45Wy4q9KOBpn+1pwPMZc3BB+heYCaGMp7u21FfDsGSqRudkTqLOnUWQ3UCY81S6RhKp0GUzoN5kAaOgZXDekEGYclSJdOkD58lXVW05p0qrQ90k1YFFjiEKpUGmQiL5f1jfF30ZMrcYTGegtxNDQVXBwjrNTYxlQcuU3NRo8YcZXohoybbqg8YihVWFx3aCj1NALMjaXHB+dKU9W16FDqoGiQyFCq9LDUKUSNBYQ99/i/Mr132W67RL4koQeZrJe9jBMaJA4xly11EhokDjEfrk/a0SBxiPlwS6EdDRKHmA837trRIHGI+XB7vB0NEoeY7/GLZAYN5wdw+yaxZJ9I9F75GDuGOAATZRI4PyZ9M/n0zY5JnyWfPmsffcJi5zLHmMqnwpRPhSmfCkM+FYZ8KnT5VOjyqdDkU6HJp0I9gBKVS4VU9CWzX/65xFjuwUQWHZdp6jWVCQgWF1Ij/E1dowQLbqlh+6b71gSrUKmxeFO2h93YqVG0SSa9SFdmsGbcVLktOvgrMy7XlOEp2D2TGbwcS4/AyjVfDuD8HyKGIZ0KmdsgoULiGPEQMgVSQoXEMeIhZKqGhAqJY8RDyFTSCRUSx4iHkGkuJVRIHCMeotmslBnfSuiTaNTGQxwniJ3QJ7PWdXLEzN6EPmHOITyGeAuL6z198G12WRVi/ADwn8ia3pAA/gkU8QvvVuSZ/Xmf/H33vGE9KrdrGJwhXPPxQ3YpCt4agveEIFuAlK8u61aJr8cXbbnUwxvz8Iasy+2KXUYMf77x1256k9YbFyhcwxO+dOeuGWsTIn4LCKZJbpH1CoWHH3EzNeapxJ1cbhiS+eyA+Iv0UhoG9lydzg1zMjd1zZrNOEPeO/Cz6cR2qDN3xqpDHseGbZDxXNOs8WxhzVXTWdCFgdUwMZ85QHZdz+TH/wMNyx1aoWsBAA==
```
</details>

**Expected behavior**
* Not sure: Built buildings you get the right to have a free one from conquest- as is, or auto-sell and instantiate the free one immediately?
* Victim civ cities lose their free Broadcast Towers when the civ loses CN Tower

**Screenshots**
![image](https://github.com/yairm210/Unciv/assets/63000004/22ae50c5-e720-4e46-b15c-8165e04d1683)

**Comment by yairm210** [comment] 2023-09-12 12:58
Not a bug imo, working as I would expect
Question is, how did Civ V handle this
@ravignir

**Comment by yairm210** [comment] 2024-03-14 19:15
Yeah, closing as "working as intended"

**Closed by yairm210** 2024-03-14 19:15 UTC
Labels: bug
