### ISSUE TITLE
Monument cannot be builded

### ISSUE THREAD

**Issue by WhiteRoar** [yairm210/Unciv#2461] opened 2020-04-18 14:54 UTC
**Describe the bug**
Since the new update monument cant be created its just stays on 1turn left

**To Reproduce**
1. Try to build monument
2. Not goin to work

**Expected behavior**

**Comment by JackRainy** [comment] 2020-04-18 15:56
I have 3.7.4 version and the monument is built fine.

![Screenshot_20200418-185519](https://user-images.githubusercontent.com/27405436/79642479-5d69f200-81a6-11ea-9442-2a2d96a81edb.png)

**Comment by JackRainy** [comment] 2020-04-18 15:58
Do you have a saved game to reproduce that?

**Comment by yairm210** [comment] 2020-04-18 18:54
Checked 3.7.5 and it worked as well...?

**Comment by WhiteRoar** [comment] 2020-04-18 21:24
We being testing this and happens on multiplayer only  our whole group of discord (around 8 players at the same time in differents matches) is having the same issue sadly I cannot attach pictures to show the bug in action

**Comment by Haeherfeder** [comment] 2020-04-19 05:54
I cannot reproduce it, I testet the local multiplayer and the 
online multiplayer, 
   but with both players on the same pc, 
   but with other ID s

**Comment by SomeTroglodyte** [comment] 2020-04-19 16:41
@WhiteRoar : not enough information. Which version exactly? Device type? Do you have the ability to look at console output while the game is showing this behaviour (if yes, anything suspicious)? Any mods loaded? How does the construction progress bar look after a few turns overdue? Is the 'Auto-assign city production' option on or off? Any messages below the next turn button while this is going on?

**Comment by SomeTroglodyte** [comment] 2020-04-19 16:46
@WhiteRoar : not enough information. Which version exactly? Device type? Do you have the ability to look at console output while the game is showing this behaviour (if yes, anything suspicious)? Any mods loaded? How does the construction progress bar look after a few turns overdue? Is the 'Auto-assign city production' option on or off? Any messages below the next turn button while this is going on?

**Comment by yairm210** [comment] 2020-04-22 12:36
Since we can't duplicate this, and no further information is given, I'm closing this

**Closed by yairm210** 2020-04-22 12:36 UTC
Labels: bug
