### ISSUE TITLE
City Ambience Does Not Change When Reaching a New Era

### ISSUE THREAD

**Issue by NoviceCoder2000** [yairm210/Unciv#7797] opened 2022-09-15 01:50 UTC
**Platform**
Android OS

**Version**
4.2.8

**Describe the bug**
Title says it all. On my experience, whenever I start from the Ancient Era, the stone cutting sounds still remains even after progressing to the Modern Era.

**To Reproduce**
Start the game (preferably anything that is not the future era) and proceed to the next era.

**Expected behavior**
Nothing will happen, which is not supposed to happen.

**Comment by alexban011** [comment] 2022-09-15 15:11
Hmmm

Does this only happen on 4.2.8 or did you noticed this before as well?

**Comment by NoviceCoder2000** [comment] 2022-09-17 05:47
I've noticed the bug even before 4.2.8 was released

**Comment by yairm210** [comment] 2022-10-09 09:32
What mod are you using for this? These files don't exist in the base game

**Comment by alexban011** [comment] 2022-10-09 11:50
> What mod are you using for this? These files don't exist in the base game

I think `the stone cutting sounds` is reffering to the chiesel city screen sound from the Ancient Era

**Comment by yairm210** [comment] 2022-11-27 21:30
Can you attach a save file? Cannot reproduce

**Comment by yairm210** [comment] 2023-03-19 20:55
Closing as irreproducible

**Closed by yairm210** 2023-03-19 20:55 UTC
Labels: bug
