### ISSUE TITLE
Scout's promotions 'Scouting II & III' have the requirements mixed up

### ISSUE THREAD

**Issue by CIZUK** [yairm210/Unciv#4386] opened 2021-07-05 15:05 UTC
If you select 'Scouting I' it unlocks 'Scouting III' and 'Scouting II' will only be unlocked with 'Scouting II', i.e. you can't get it.

**Comment by xlenstra** [comment] 2021-07-05 15:06
Thanks for your report, this has been fixed in the version currently rolling out

**Comment by saud2410** [comment] 2021-07-05 15:08
The issue is fixed on 3.15.8. It will be available after .9 release.

**Closed** 2021-07-05 18:08 UTC
Labels: bug
