### ISSUE TITLE
Podem resolver este problema ?

### ISSUE THREAD

**Issue by Skiny12** [yairm210/Unciv#5289] opened 2021-09-22 06:37 UTC
--------------------------------
Game version: 3.16.15-patch2
OS version: 29
Device model: SM-A105FN
Mods: Wakanda for Unciv, More Luxuries, Resource Recyclers
Game data: 
```
H4sIAAAAAAAAAN1933fbOJLuv6Kdl3khsuJvUm+O00lnb9LxJunJne3jB4qibN7IooeSkvbk5H+/AAkSBaJAFmWnu8/OyZmWJRAEwKoPVV8Vit/y8ku5K/+dHctqf1j99i0vj2UhPzxc8u+O9Slvf/y2PpW743P+f5tyf8PbvK32p7tif3T+Ua7rbF+e7hYfimLjfLity33hXGW7LC+cD1leF5vF2+q03zhvRMv6wXnF24v/fizu7nfFotouLupjcVcerp0c3PS/T8Wp4DfK6s/F8dop91d1dVMXh8NgZG2DlR99/+4Uv99n+wP/fvUtP+2Op7r4cKz4CFbud2crBsEHf1l+WX3KPmf7TebcFtnueLvy3KVTblZhni2XcR6wIvG3LAg9jyW5m7JiGRVBkufrfJk65eFdXd6U+2x3md2Xx2y34mMpnF2VN+u4+vb7ivnOwyr+7uyzu2L1vKz35X7xP3zOzn11f9rJZtuq2sjBpTH8xfW+O3Wx4/cQze7FjPk8+EQ/3haL7gexavzvN8VNsd94MZ/uLjscVv8v+5I922X7m2ev90f+W+18yXZ8Fd3l8nv3MK4yPuOp9j6/QA3jcHH8UN0VV1W5P15sqvsjH/RvoLvr786x3DWiw2cf8NlH3x3x0eMfk/ajr7711bee+tZV34b8Y6g+xu3HQO8sVZelqrNUNYjVt6CHWDUQt3jga6N+BDcFM+Atrp2vFRezzUc1TQ+dBZjb5IR8feixMZzBWPtB8vV+Ah39lB2LevG23O06lUQVUKrtiAbKFqso1VWQonOe629SbxOxLNpwnVsGKcs2ac7W3jrw4mK7jqNQU67mgYS6cv2f7HBb7m3q5Qfwl/DP167ofOUSMuUGjSwIqXBbqfPUt5761lffNpd5qkGsPoaqbajago++autzPeCgur/I/3UqxdJGkaEX3uCuwbCn4bh9qjgPpHhMZjvJH9s2ZBOhcGMbR0yR4m0QJ3HBN40093wWbNYxl2dvzTzPK9IizLJ86wEpflgFugB/+Ps/M6v8JvAH/88X3+Bc8W2m3SGj36Cd30sH+EmJTNQ0ivq/W8QOVVMlp/FQNvmuOpTNwX1C0O81v7y1fy7rIhOT8PnfXwZCs62LQknkNwp4CXNqsJwfjhx/b+Rq6lLNR0GxQqY67YSbd0cRzblj5CrBF+LDMVPqybXsS7nhy/btVbXjEnDt/Jzd3/NthvfK/+A/b9pVFH99yMtinxfi48us5BLHP1y2ajc1FMqSCzgZ64OywlN9UJaVr/5LrsZ8dlxfuDD9IjS+A5BNeb+r7rL8YfXt4q6oyzxbfZPfHctcrO3psLoqhBVdHW+L+lJeLxu3mLUTAAHke9kbDYluWEnwBx9ZpJRBQLKnDAyplMp+SftuAY4z8Lm5cds27m/sAtMMbAWJMmxCNYRI08du11j2PTSdSdso7W8G9ioGPveb4IMw/GW7RE3Q0w20fj9qrb3hNplqQzPMzqZl0k8NjmappqmATn7bzA0slLqXgjvXBZ2BcXnDjdR1NAPUBbPx2gmCKQPrANgBLR7DPRoYt9AICNqGAEfB0/TANQrGB+aGbnUos6S9YaBPK1CPDUwL+AFwau3YQD/qzmnzU6ru66NOA/y6e35q55HfAMsKtFNbitc9r/6xAfuK9b+2DSM1Wg9sd8qRCPXF9MGCgOXG/Q/1OFN1G191G6qr4CIsm4EYDpSvJhuoQYW6QQeauqopuBH4WkGGFKu2x0gX8kjdZtnfRi2Ip8QPOk9AfAHMAUz0+mGk6gauGgBY6BTcwgXrr8QBrBWYaqwWYKnu4al7tLNWUhOqC1x1ga8uAH4gWEe1Qmr1FdqCG4IFb5+xrwYLNC1S85UTUxd7SgbVx6hfpFiNLAGrqBr4+hKBCcX9LBI14aXqVT0wgDiJ6h+scao6cFUHvrpMqYPSY7BHKh30+8vjvs+on57chpbq7mmPNaC79r6xPvJQjTxSiwBkFawywDi1o0l0a+/u9neXA0k0wY76wcf9hNTmDh+Y0m8wwFjNAOyjBl0S9/dM1QNLgNa0Da6dG2EkumnQfCj2FzfCh+E267qo321fqe9c59A4QcqYDH1+gxtho18V1f2uWH2Tf9SHat94IdzTO3GHpeamqPhl8dP+hl8q/h73a8LkO7eqbrPDT1/4KL7uiw3K9O2rY7kt8541zVqzVnaeV3fPTntu7D3bVTdl/gxyrM/eSA/wormkdwgBbwb2tVjY2WXe/CzMwdfi439KM5n7OsXvx9XffgP04vWCj33ReLLcEF+Ux8NiXdUbvjD/8Tfe7VONc8glhHPG2TI1f9BIW2NKjU6azs47YU+3w3zRWeHdQD8VfGxfigX3T1op4uPrLrzmo7t27nfZQ1F/fLgvVj+f7hq3fVfmgjj/lrX+71X3xW/cBc925eHOuahLLsh5ze/kvOOOc1bntw/OxzrblM3AucPWfHXtdEpwMegrlJrQ+UmB2Dv+dSoOx7f82d8I8VZOef9V94V4MMXqKtvzqfPbtV21vlfK+6lP5f7QX8SX/Xh5Wx2K/fvia1Zv+EQ25SGvuFosbqvdw+LwcLeudgfnoTrVi9YN4Z7R4rQvj4u6yIvyS3FYHOus5I/8RhAARX67+nZovb532ze8/+Qj99V5x77n8H9eKv75bv/vurnm8Lpnb1bfLsVz5w5o/aXkrqObum2/h/fFoRBrJ3gH6K47L+rsLltwEVtcVcWxfnAus13BXa/aeXfPXayD8zbjq9G4W+Izhw/e5ueqPhTrLP+8eF8Kx9Z520xCPCqBQDfO87ra/7tYfKrqz+LPDxkXRvH7Lf/utih2/FHzsYi7neqaz/fBuaqOR/HFxb68y3aLn0+HNR8U/+JTzR8+v/bihktX+1id17z7rnO5CB+rbop8gnAR+Mry//BH+aBE4LtzXhhHj9sYoRo+u6sHvp7lBo/SXN5mdVkdF+3kR2g3veEqXDqNq9uEgf6n4C6v547RcXGi03GdSpebVRTnueslLsviMOEeeRCybO2lbBOmWRItt5v1OqREb9J2u923zrqAq5tjZSeXtdhN/PTsnCCLnXf7YvGVK+vil6xR/icI3wy61FjmpDczkt72kJYO4OeWvYnSfGybAZMENFM2mNdbB+qTMl18JNASY327w9sM+2mHPDdQIrVgKP6fst3uaeXeH5VyL8KlvCOdw5Z09lzfDbmY+0uvYEGeeyz1lwXbLLP1xsu2m2201CTbFfs186Vs/1J8XfyTr7U1Kgl/iJ5esP0zBDt9nFz3C9B/DsBnaa8H4LML2vjgex/04w4/h+CzN2SlQzNiot0F6cG4e2COZKago7LcB1SsQixbrMJR6XUt0stFNt8u1+s08VgQbF3+f3HI0jxeMzdcumGer7NNrEf7YgfESqrDCBAHf0SUZKa4EiIlY+Iaae5n2AOyIkmUj6/8L/Vd2H+nnPSwx8hoKJqJi2KvP7hH24tF4B4Zi0tGUdEqVoWX8q3ejVmceiEL4ihgaRSFLAr8lD+DcBOs14ZYsW6Tv7otd9mm2N3fltYUDRf+8KMSNGZK1yM3+VihSKQgTDxnprZrpuSPKYsAXqZ8fGaEh92liXagq6jDrmHoLUBCbyqC0j14EEER3n+pBVDeVhvupfOvV9/+yW3nw7ttE0tZJc+4BlDiLG2X34VB/q9TVR4onUfWrre77KblJTbVVy413OQv+KpUv1THD8XxuCt+4f38emicMW0Y3e2/OzJwRIsSycZolAg8aMCGMkCvDUEn0kBHblXBQDxUiIQB7rbbpxRpbw9SMUnQCXRiMegO7NggGjSMTck+FP5pfQRqpArH5KDDwQacqoGqwI7izSAOdpcHcAihuj4FQ1DYK1dCwXUXlRLNInW1HJ9ae0AJdg3VjpCAaSiWtLm3ComYKt/cKVRLHMF7xPAPteLwaafKEonVGkZ9W7VxgXVhavBM7VNMRRS6wTU3XqrRASdguOepOFuq7tB24KoxAkfGiLl1+52SYWgmNrQcg9k17VL2C2qDxf6JKKJf0xFX3Uo9SR/eM1bjl4uoSFfgk8nnBK3RANyym5omRYH8ErhrDCiLDBaBXsAzAgZppOYAHrPqSAWdOjmHVm4IR6T0BNreYLKqQaCeGwhgw2fEAFcp1cBVeOaqEIZydaGbALa7AGyC/RcuuBHiECho8DpVURqjAnRg/P4QrTzwXFQYttcJEDhX4YPeN1cNlawzTbLgk9UdaKA3Klzh+mDtwGqBmBZYLKAQrhquCkp2DwREX1z9Y++JqYGAyzugBksERBI0BIFDpsJMDNAIXv8twAoG4ETyFaBPEAmEQgs8M1+JJ4iwyJVQCwKgAMCiC8apgjLdkoGdCwQCuxVRsfgAXK/G4YJtAi6Zp+QOSDZAn66xQqhAA1jVUi0oU5EzuBEBHYVuOABDYCYClelauHoLEP1jMCwHZAOsU6ymAQaqYlcMxNP6NVFWCwMx9g5tlPqpkJ5SnFDBXDxYE7AQYEkDJR9qLGk/Am0AsXrqDGhK96zV17EaewSWQSFZoIYZqrHF4BHAHavdBGU4z/fd+eG8IA5+UDjP80nhvJHozc/Vvqqdt+WOt64fFpfZ4ViITLYtHzh3SrLd4qK+e3BelIecm+R8UPboTTCI3iR84YVHeX+xK+qjsMuPIqD0sqwPR+74HLP8KKfRWfLXTxLsCZNhsGc0OuNFjvgXgH/iGyQ6A2Ipq8DDQjNG8OWpAy5GfKULvEzFWRzBAFSH6v72AQm5gJk9QcBFBlg6Zvl5Vtd87ji53HqGo6xydszu+YxWUejI1qskcYZkszdK1w14lc7jFMRKGvlpnqwDli8DlwXLImDJJtow/rzWYREU/Nt8OqbSIkrDtbzbV1wIbqw8S/CDoymx4Ey00yquQrneXpbfqL9ALlH3C3CAQMqfZsi2BzpYjAQ17LeKBx2g9zgzrjGWMt+JEkXavNGUeW9EoLZulhbhMmX+xhXpu1nB1slmyYK1n+TLnP9/ttXPUnVWTSs+BwEOn2k03Q846REa4gPNMwZMWgbtLgYMNwYMFOYbV4OTSgxk5DGQgcZSI6jgm8eTtK7D4f1T85Zy8E8RSWjFbUSS2gbcBBEIvHheZXwLHD2/F9lFKgxDP9gUBYvXXJqCpbthmR8G3IcK4m2arLOIW3lQpHqbuREpoRMbvvdwI4EW4w2eXqyCoVgZZr3mSQFDFzoGrmsw+uYRiPEePL03XBQeFTryghkUP3zMGz9acmMxYMuwEOH9aMmSxC247esluevm/jrX4/idMjZP+eLz1+KQHe4K6yEb+FThowA67SnNAT4EUE+gTsHgsoTCjcte5xLi/TJRGfFf91meF/fHbL0rXnDbZr85CHbvmRc6Gp8t5MHCNpf7LZdccYiDRUucOUeONUyNwRyCnVInn4oA7DTgrAH/DfxawG9DJpshf0B+0oc/GEwz/NrCOgMKQeeQO3ZTuZmAudV4YMDzMvAZkMJzKV1mfAappSZrC1swjXaFn02KVaNVITcKKFNgpTHPeBaANDFYU/V4IDeqEaU9z6keE4NUp6vUGn7N+u/V80qN1QbPEQ5ZneGcICiHHSaaRQrZTgZ7GxCbTJKu4LgxxCzXoCshiwlaM9hc4yotRGQnKUo0bEwmIDsZ/B7a1enwUhcOpLuPCzsZYzCZ2vWUsgI6s7f3tW0AbpWAzwQkprQKYdRg6EHIpekuBTP1YRdIJghOgQJOTCPC4ZOS7DOIoPTksnpuUD+gMarNBhx8QKhVyI4C6lQjSgE9qklWe2qGgYDWKA0KOFOYz6NIVbByDIZyNLsdmuegRxaBJw1NMhfsJgbhKq/SHiNkilO4GN3CA8ECSwswB2iWdhttOlKQwekKzZ3sVr79j43BHUqxD8cLHgYYHBBHMBO5iDGcqGJ1WQJhHHDDDF4M7sRQpri/O+hhmjCWg3LBzUHMF4YFtPbayiOuVTAcrQqfI/T00IYEVoHBQ8sB+HAALhiAOntjEsuAecapa4UDimxmoAMG+mWAm2agZ/A1ILIBlppMNZQDqRSpphRg+oCWZoCXZoDEZoDbjgerDLQHRAxAICiCMrmEg4HRIMChAzJck2f4uPqDLiGX1zOY8RBjxl8V+6LOdi01vgqFayo+vazqX4rfj69Ak1Wy/AH8N4Xt9gdsd0o4qQBZap9wIuFvf3OyxeGYHW6Fsy1Wd/yggZs62D/soIFM3F+5aYgQ2WcdK/hDSG3svICcyw84KnBZ1vnpMDwxIGbQxmkGSdQ4UXSs9sVtsb8ZJYv6RlyD4zH6IPR1/kAM5ufTvqWyC3/jL72cbf04Y0EW5ywV+adBttmE/noThuuMVNyps0FbXuFY7nbZ3w+Ly+pUH62s9vIH09qeSB+84DIvtEhI1eG2vH+CZOphl3qhJ5grwkCiBIOeGDT3GTDoGDRAGcxLgD4UNB+hS8KAx8rgPgkyf1iXWoIUb0qG945s93At9wvgLIKnOmnQyHoDC3hISJ5EsOpK8/tUwMeuJEVepIEbJMzP/YgFebBh6yiMmZf76SaPimWYZLo2uJ0TLFNp62yjs/N/QN7sXMEPHy34wFdnMJ1N/tHlI0InCubzyV80mUthswT+EsM/tF+6DqSlP2AY/aUp9+jIf/gpmSbGO31GBjYTHu2YDCcWIe6OyHhtRb8w8nLP3bJkGXGoXydrloZJwbJk6WaiWEy6GaC72502uOLf3dTrkbJ9f0hdprmyTThyMCHbHbBB8xtYzsyNICbDciohvAJYxj09GoKGRrAiCBFxBX6CdiuZePJXAt14FHS9pR11ozz2w9j1WbEUoQ0v2bJsnW64kqepF6yXy4iruy6lnWPVRkXX1aZavM342tkjo/9LpVXzMAEZwWAymaISodj2W7gPL3PhZZA9gulvLMUkGAvDuh7W1fJM0X3kua1gvEbqiGHghp5bbPyErTlqsiBKfS6i0Yb522yd8L8SbxsOgVTuUO1hw7//FzcMPmeLfwh7+UYPw/1FhNF7PHQam3II5S2Ev0QQNDWzQBPLAP4SGvUXA9sWHyBRxHA0itg/bjOCxkAIjcGDIyBchhcRY4BR6jQs0rQUzk+zSzQjSmPewA+YdqXwat1ogmsOFR76LZBN0qw6D/6h2WG97QaftkYAq8/Q+4ED1uYO6TANfjrPRP0Of+6mFMNlUqc7GIwFQldswCoDZw3d87tqNVOGLUguZvChQ18KNWTBU+ptC/BUIPuoeZmQxQNkoa+uxWwJzUqHY+5MIbicprMYw7H3TwN82X0HjlMwuJ7DuCUgYEELuK11LTBw0SAE7oGAwWTgqAmDx0cgRQ6PjwzQDO6RcFbaEwPsOTgKAqvExWBaSzi6pTGH7mnCGUfgicDxozg79OXhJLv2kBRwYTgS/gAtYWhvaAFZdVmvM8MpaWioLXlvLQ8npv0AsQw+CrC23Ue4aJrSwsX3YSvE7IcMjb41wR0sBT1pAqdlirNwsvCTZ/DhXrP1Hd4U2+PLqm6JzWN/xQoly0fSyJsapMfycJxkC2hVocQB22z3qdqLMkar30RiL7ejinpxWYs629fTRPsncQm3LS4r7pQOWPf+T1UyiELED4sGRd7T1Axyg5BI0e8X2b5Z6cV9Xd3fFg0V3dL0oobsR0FYi+AHmn3elASSeeeh4yVtnaCJ7PMkOI+0/1PT0f/ADHRayZ8zE9K7JPQ4Hc3mHHgabcZYkx+cb9dbkWYeFD73M/IsZUm8ddk6TNaxX4RZQ+wQEs7d/nQ/77sQunewucae94PZeeHlOq+qzYZ3Ji49tpb2JPK47rRHgnSrVdzuE1Uc9VnLZlOpNt1/9SQsJN1KS32TQfj+bKkLenDhRa4tDV4biAsGgnRhjK7rYa4/PSbmQrdHpbxtwJ/rHIpSCflmk6bxdpOwyM83XMhTj63dhAv5Joy8IF7623WqF+5pJhn2zGR9yG64O13YiPYfkKLsnSnDhHcdjIswTI58WOlpgjDvsEuSVJWFB2mZWqEBgywPzeInsA/7/SLE0fZGHW0pCOMFwG0lJtJ5+bCzyldwu/R9sT0dtMIUl83MZHkKvhwiQ/dFwR86XzVusbzbN18HzyLPXlhjWP3i9Q23dwoufXfNPbiCdOUv+GqPZBb3xTCwNF8N1eBnQFgAHgNm+k4UpzBKTJipv3htij+kIkU6vB0sxAHyB2H6pexOlU6ANSDQ0hE9dTBUJZByBZZCS9Ud1qkwClkYddbdYRfEyhMwYxmwAHoxJHu6Mq3MBNyL9DznifISWqIzntzccwHDLQ7JjgY+PPxekQWAQdCqSHQO/xDekNRoWGYCFJ8A/ryWBG3WkAAUCV4mAvAHWnI1/EMRBb2/roTblnINykOAwt+AZ5xOvtbSq5PhatoTrX9faVnamlsPdxVL7vVoqQiYu63nSWvZ2MC/B7SAVjkC1G9UCdsdbzDUjVCtjXHy0ZKVDbiAM/Ozh0nWvR5AUhimYw8P64DWWg4ykqYNiWrVC0zY1jOqYX42PKJnK2AxlratJVV3pi+Spj1Z1AKyylrWNmhzTjELBtsAqhmQyCDnejpXW8ustqZfmznaKbwaybCeLodxVqp1CEcL864Bpayd9xxPvZ6dbw15XEB9DmtkqNdFaMm6Zir1zARpSM7CXGZA8U6mNT8ug3qqOActPVpzBCZzpW0JyyC3eDKhGCYfj2YQd4nCy/l5wt6Skicc/PA84TH68pwSGULFkBIZgjFUzJ70MhV99kR1MrhrT+M3N18y7qpsFl+L7F4QiIstXwJQF72oJ9KSY0f8iwb/ridqm9voy7PZSoOcHLKXlOIZGDnJfeOWqr9q6uaD919tt02HD6uruuTr4txwF+81d57zwN14acHSaO2yIFv6LNtmGQuWuR/F/jpN3U3T9iqr+f8fGz/2rhIPRPbdPINfxSsDnLf8CSzenH4/1VzEuHd74E8mLxbvi/wh52J14OJYPc/qdVaXGX8cLZUvBZR7vg+NiBxWS1n1v6FYGyGA7wIcvhGAK7b6d93L3097cdZ1095ELpS4iHf6orrjCiee7DUgS1bftLfybavdrvpa1M/578X2oL9lD1JN2nvGGsoItETKjBodD8uGGp13JThlTQ+tNZZ4YdzBSKQwbtGnI7R51oP2Fi7KuA/GLRm3koRMWw7AvECezH+b8YncZfea2GX3H8p/8yW8Lcqb2+PKc+V6c93ZOSJUczqIveNruRHHGkTaVVYXL4tmoQ7vy/y2gfDls2UcOoeiKZ7sc0BPfS/xUv7VbcaFikvrMdvfnHZc34/F3T0HbXH9T78f6+KukD2EafO/yGkLCQkEuqxqDvCH7xzZslpo9Rv1eozrZk5vRPzrt2/r7FB8LGrxwobVh331lePuoezJR+n41FJ5Vk26HBft8aukadRfdVnd84EPLvvIH0Sd6RdG4KKL3YkrxumOcJkMiuIty7v7uvpSNDWGOQ7tj80y6B10kX81z3L3ma9301H3yPhmV+5214O7vKqzw4F3u9F77DI20D4cvhNzkR529YIjfn102pecZPtf96WgWFsEfdtNwZNvJ2hoaKfie3bdqySf6F3VcY7f4cxBwOytCPxoY+3SBvD5tqHXj9VrsI6BdREoq925j/1qfyoNoeLX8h1Yv07meQxaXlZ8S9UayiSgQbt3eZHpA5En4ibbSZMNvS+c78uyeWNEW9NE66G3edWUb/kufiAto9iLFnkhAthap73D03faBDAPTl1lG8nBvucfJ9er94sNAbg4VqbEmx30XIbS+DpbT17W0TzTeguX4E6al6Pq0Zo2Uj0kxg+0QxOtzvMdLB0NAgxIkp4G6WIDPZXvMY6fb7LPhS5lPV86CdCSJ+xvIIw6Eqp70323ZMpks9Dy2E1cNjqT2KCpXlbfIQAMIf3X9jW2OOZS9K1P+TlLSCy6nd3dI+AYgHG/KIravAW+g1hR01htC2oa6GpBTQK6xii6mveNUHTFl8t4zB1NRMQ4Q5Tk4zfBzBB0G3z5FDkeBTodN8JH4gYVd1r40MFUvveo8eXHTQsEdgyRwBHEWC8cQQhAI2mZ81bLtdo7hMfpo7BksQQ7uvos1MAUWkYUaHfvwjHG3f7rtL/ZFdN7e4rChwUWCPARE+EjIsJHOGKcmQBgIIUVAGy7jokAmOGEw7MVGqZBBAUQGwYYj8ts2EVnJxv20cMzfEB8wLp/IwvxibRMyUlK5Okrmw2gZxKy0Av/75VQ247euVK/uENTMKKBVIiBlM2GgUb6y1N9mOUWoghEljkMQbqQwhMaMqO+nqfZssejYWya6toHMWk+CY5+XXgY3DzbTd46ISJeTHRHIxTxLEhGQLyAiHg+GfH6aKyx2O+yQ3mwiJT2+PnNBTtsQpvGqtwWxT0F6ab1j1lsKhvShVPulA35piFSJg2QEMMG9AgmynTacTuM5AzrJaHphl0XBtVcEaJ5hAnTDIA6E5sQHHFRW61tSNyJcP4A2YemWAe+CXnDNZYxfjqeGSKELGCXsXW21RcTncYIxUBkRCERBLt8ALVdlodb0uJ0qRUkQUHcfoMX7RNmHrEtmmSrFWpnkAZPzYYJ4yhAjSPY7LfL5i3Qr681Ee4wfpRztKMcXd+MZaVhX3XXjLVYPK++ijd2UylBle6pWQ/nOucWrtO26xAs+GDO9jTdn8xBm/abW+rwUb4zyW6WCS5P5zYTB22zRSncUYqCOSmu49LjOgbS+3rk6ouxS1sA3njcFjecsBGEYxvB/IiWzfnDQ1oGi9qlEimC+0tVP2CRLPcPQNyZDqmGuRc5v0OWPwxhV+U7GgHTJ1OZLttUCxPM2l/Nnc9wR2a4k8Nw14fTTWaxR0f3YHVa4FwUU3nSZ24HPnU7CIjbgUyiJcH3Y6nPx8C/TMclmQuGHW8x43WsJkY6CH0lKJpbsNQwyy1YSsDckIi5AZGA8Im2t4cSEDZVPi9kM4EB83eKSWMR7BNG+Egd4UC2Bo+MA49Bki52TkQCAmT02ekzGVt53GPmVQENd3zMurQBBLRn3pVDxs6GDueSBpYdCGO0lgMu9zITHM30Tkpg65IxGxNxnGYmAFmj2t0JkblJIxER9EIi6AVE1tUngp6Hgp4lSjYGfCR770NenY5T5p43be41/YgcotdOe1ByIUV4kVeCOht43oZcIbLHLIaXHc7o3J0d0Kbjt/2RGiKgEX3Ts/NuujNuZ17tPdKwch9pWC0phhUxqyLFbC1K1o2hQ4/Z2WdlNRpD6Qo3EbIXEQunq9EE8vX4E6F5wQRQDIig6BMtQQ8FxRGwi/UdlkoUT9OmA59UnF5ZvKuHWySy4gw3Ku0ohRGzc1FqOk+tPzRIRCkCnPWHyObm98nT2SQgI/CC3gy8syHWTMQbT31bDkw/ESl/JD1jkjEETi09H0rpxPTsNKvEElU7N7wBIeBVcWfJSaAF2iOiRx2iHrUFHwk46hNx1CPiqEvG0RZD58GmCXfGfmmFOxswjmqUOls8FsK1YR4BHEMqOEY4OCIY59MwzqNhnIt5p9jBEJu3B2Faptc/wqlELS1iKp88ioPeffxAydAsoqII4kwQHC/8MI5FxwlY4BOxwEOxwKLjhkxQSYAGHyYIAKu6E91RhhNxVjPGwAabRhs+oE2jCaofUVU/nqX6xqyRdh4NIlwMImyuE+U4QopxWJbsCx8JzJzhUMmSHKNuiH1LpuzIREUlKLRPVGgPVeg5x6mMMxLoaSpkfXES7KE9jTZq7iEWFbZn9AV7BpsGPrQfEheFsTPcV26oURNwtHjpnq/SoTiXFvdRAGtUlMJJ9gU/hod3Jh6SDc4IMaG+cMR0yxhHPgtQEU5juTQ8WxL4eQtqYW4e2VdOMNjDo2DkfF2cT37EEcQQgzsEy4gwRujKI8IdflxjOANLvh5x9gw3ajA2uCtqNMcCHI+mdwVvSD0iYw9QsEAaduVczl6liIwGfQmcsTxEE24SHBpw92XabJPlBEnIYACIBQqiQT4HTf9nA8jTZc8QqBFZn++cEBYxgkXkLChWEhFZCF25JASieU/dm8mnVYPKpTA8UodhkpGuZT2nQbMP+7JSfYdXRVbvhlYYsgr4YVSkYUyGku7dsNOOqUsDhSUGCm13unZlTb2g1U9tMSLHknH4sS5FKRGpbX1dG6BtMEDZldkRyv+F6+g/ROlwYZotLuq7qh4mqaVEZEoGyPTiASNayCZL3ELWxNlvHBGICTrEKA+R4KDYG0RAmOyKZrYw3G5BGuLEC9KQGs3qS9eNbb42+4BwtJThZ0ttWk6BgwSHA6RlisMBvvdr1C1m71uSlQn5JqkdRYaKSUgdizGuBdevcPy54tpGTCAhhgyIJAVlCyYoG6EbRtvKO2WjaCU1NMKoiTcMT/G2qRdFD/ESETb1ouhhiuuhRU2oyaJknwM/Fk8sMUQ8FE94AmguMK4xRIeYaLUS9yhcI4haQlEnqm/OqMEFRs3YYHjyrk1LKOpErZjAqPWsWi2hqJM8+TIdN2jVaXpXS4lal2CbGK42hAlHNO0KadqFZrziakMMTRME0KVoF2nLoisQpSGV9GfUkD6jJowy/GiSTYEomkYtbdS9tZGqQERzDE28fJ0TjusmRLWK281snl0d0ZQspClZQFMyH1MyPPGNGPOdlD3S9sXs+9dAg6jKQ+mMGitn1ARERj2LwvCT4DbloWgZtTxj/7ZVQks8eRDffnB6FqVOXlb1sdw+LDyDPOmCc7fiaPGrqhavNh6hUCYTv4e8yofbKv+8eO18qqrN4S7bD4mVhLbfxigwIIxJZDFzccoFj78QnhSawYhrPzHH3xb0GE81dPTMnuZ46MTtpo6lWLCC6tSRNlsqVFA6o+biMepJD0Y9U8zwCjuzGN7uXbzjKQBYpGyJwg/WEk/RM3QssYOKoYq2IsVDVaRs5iGN6Alomonm3eEqN5IgqWc0SBS9OB3Fi8FMBhrLcHgCAhrPenjTQPDiTqTLDbFgJLxFOUAwkWkyurUsbatiqVzxpAQ9FjY7O45LMrIk2lGtI5JxRNBlPCnRFiImnPnt331NI4ZscSHL2OeA4ASfSi0w1dfcn1d2pempyXHSy0uh3dEKG6gXupMkkZ5V1L+z/SyJN+6D1BXoXiVG79DYSM6uKRC329CZV0c0ezKk2pMBbXNCUz7xXcfYnCwH06Mz0iXtB2EsmdWWxN05R2IsoXUqt0/lXCygd8YZFRtC6EA7jkZYajT18Ej3jnu8y9E0WpagNixyj65kJA3WadVGZAXus+s646dSyHhETc3CEeVsPIpoZnFoI75INwmoeOTT8Ei+DXY8b8QCPDaAQs2/D7uiuLeaftkxuz/tjj/G5COeE2Xo2RkLalHD/1QPlsp1kUw6wsbBuuPCZyTtm3rXvQxUhe6z3XAbmuUzUPLkSPDcva5zeKbpMe+9oKDfI86JIl26jwRU/Li0Aaj/feL738Pg2i7bdV6ZlAZKpysYRC3i4otymx2ei+LJd+/F+6bel1zVu9fzDeB0Zj0aUsfBHJxGkvz8FqkfW/naeyRPiWbUmlQfiR9y8GoTMwpUM5TBtORSUpM5qEE2ipeLniKyzGXkdBvxTVQsGaJwd+4Dl7rzC/qZt06HmE0vdoedgOnql1OaunMQ0gZnhIqhLp6RO4UC4AcUGaIW254GcqZuFkqbVMGvqCl+3r3fFNs5tw5Qg/Ztddof+QdrtwYIEmwWj0gBuxY0JHFQJM+boZbtrHcAMG/glX+4L3MLVU8kvmSpnnl5hIyY78SI6b0MfU+NxW+lVI81Yw300mQsHULnDMVAq0Yth4CIJOUj5hpqNLlDs/NtVq93xRMTb4+AUDw1eZRa/EEWutsnP8876tig8MxyLhTICuegOyJIgY1EIJt8/phJO89ytBqwlm5wxJ1GZoRrIBaEYKiBqi7+a5EJEtzplVAspi0lbYSYdseI6eKMePqLoa89tMRzSChPK9qH1xyf4R+fHQpgLp5kboPNR8AunnuOc4TTzQLUybYhCsU292zQMwsuKKX0jDJq2tEPUZ/pHNobPVFmeXGoATrk+glSic3A2rTSELMBGTGjnREPcDH0TYQWpbab/HshDtnuU7XfcGR9LqIl+5uiXlzWmbFCaE1FSp0uvX6TpaCe3a/EY3rnGTWB80PCvY96Q2L/MBBkokBYMBvC5lftIMTWAS2CWtDhMNTf0I4YARKS0FQrYkR6H1aAgrANXSlvdbZl5HjzTEa0mMqflHp0Nq/hyp1GK9T26JD0DMrWVrTK+gI5Y+f5S5qmZ9vhI5kJRJIikHviyDvRLTsd9ZAd9fADNSeTGiCnmMOyVjrF1KUkRbL+pZXnO5LMxU+rWLYQ/MSKpTF+agUHUTzy9FdTHx/Fe/kArThH4AM9ySgMi01N3MnO1k4jLWXXcceyHSyYa4gzxhCjNfz/pP3JhHd3wPA9XYFZJlns0XozMxjONoVjWHvxPJ+DcqiEeKCJEQ/lspiI2Gi9Lcs5GlJll6Udskm2LPaOPptJO/ttCZOew+R7EDpXh0KWmCVyDaOLvI9QLaux7YVQP9PFz3QhXryLH+rCNyFqVthUwG4UAvyhq9G/o2wOnXw21NvoCk9y5ePQMbEBjZqPbrfHUe6gbR8+vfC4CebeE2X2YM5Ax59TR/eX2O+oBTD94VbVJx5MZxhYtphHFI1gxNN0jHiwnaHlWSxbD2WLQivh2rYe0h6FHpXD3Ar0rBwO0ueR58ETYDt+ts4K2YSML3s6wblAPhLz81AvxVy+sfevuF088owKskQan7koj28FL4iO5vlNC676ppHMV89uxho4QCoSh57lsyg8tXAVtWQI9cw2BRhkzXyiwlP4Bhc9LmY/1UQiXk1rbjaxQDtxNGkC2Oy9adoegS7jrUXEF8swF3+FpTG4ZqVmnW+aSA3xJILNy6Z17SyKBiIUtpq5KF1tK51r5p4R0EdmMMzADEpeO34WywIa1JqW1Gpc1CopFHDBC/DbQMNyZPJHHWhy0UNZNiO8PZn1KI4SPbRF0f5HJMRHc2we5Pp4CDwkNfZaNCFp+1R99BGDxdT2kbd/mAqvvWegNGY1ZjaQTBM8rdTSbUgFh2jo0NBSJGMiVBDL2jG0/qsNAkhYgZ5KwhoSSwMxFz2XhBoYTx/rxd8h0Z6AoqVyYga2P22y2HJ13fZUFTAhSu4eEF96hCHLI0GF8CYa1zhuJYz7a+l6cHUJvv9/UDj41+8WAQA=
```

**Comment by xlenstra** [comment] 2021-09-22 06:49
Wakanda for Unciv had a bug resulting in a crash that was recently fixed, is your problem also fixed by updating the mod?

**Comment by yairm210** [comment] 2021-09-28 20:07
I'm going to assume that with no response forthcoming this was indeed the cause.

**Closed by yairm210** 2021-09-28 20:07 UTC
Labels: bug
