### ISSUE TITLE
Add allow insecure certificates for multiplayer

### ISSUE THREAD

**Issue by Mape6** [yairm210/Unciv#6537] opened 2022-04-13 08:21 UTC
**Is your feature request related to a problem? Please describe.**
I wrote an Unciv_server with Python and tried to implement SSL for serving HTTPS. Because Unciv on Android does not like to send unencrypted data to private IPs. For serving HTTPS I generated a self-signed certificate. The JRE, which is shipped with Unciv on Windows, does not except that cert, because the issuer is not trusted. I found out how to add the cert to the JRE cert-store. After that the  HTTPS connection is working fine.
Unfortunately that seems not to be possible on Android.

**Describe the solution you'd like**
Would it be possible to insert a simple option in the multiplayer option menu to allow insecure connections? (Ignoring the cert trust)
But I dont know if thats allowed/possible on Android.

**Additional context**
If you like to try and test it by yourself: [Unciv_server with SSL branch](https://github.com/Mape6/Unciv_server/tree/ssl)

**Comment by touhidurrr** [comment] 2022-04-16 07:34
`http://` doesn’t work?

**Comment by Mape6** [comment] 2022-04-19 18:24
> `http://` doesn’t work? 

Right, does not work. Android or the Java environment does not like to send HTTP traffic to private IPs. 

> I would personally like to recommend the free SSL's provided by Cloudflare. The Downside is the latency might increase a bit.

I think that would have the same problem as Lets Encrypt. You need a public domain name for that cert. If you like to host it in your LAN, that does not work. Please correct if I'm wrong with that asumption.

**Comment by touhidurrr** [comment] 2022-05-02 14:21
I think if we allow HTTP anyways there is no reason not to allow Insecure Certificates.
So, someone should implement this. I don't know Kotlin, lol.

**Comment by alexpamir** [comment] 2022-05-07 20:04
Yep, I think we're running into the same issue with my multiplayer party (hosting on the internet on a personal domain with players accessing from 5 different countries), we can connect to the server via desktop client but not from Android phones. Instead of supporting a workaround like insecure certificates, it would be better to actually fix this properly. Maybe [this](https://developer.android.com/guide/topics/manifest/application-element#usesCleartextTraffic) or another solution from [this](https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted) might help for now. In the long run, implementing proper authentication and HTTPS support will be best but then certificates and other stuff might become a problem especially for an OSS public app to maintain.

**Comment by SomeTroglodyte** [comment] 2022-05-15 19:33
> fix this properly

In a way, it's not our problem, it's G00gle's for coding crap. But I was the wrong guy to "ask" - OK you didn't directly, but I still experimented with android:usesCleartextTraffic a few weeks ago and failed. But then maybe Android AVD's aren't allowed to talk to each other by design and my tests were doomed to fail anyway... And I have no desire to dig out enough old Android hardware to set up proper testing.

**Comment by yairm210** [comment] 2022-06-20 20:08
Closing this as "wrong solution"

**Closed by yairm210** 2022-06-20 20:08 UTC
Labels: feature
