### ISSUE TITLE
Duplication of workers

### ISSUE THREAD

**Issue by Knirps1** [yairm210/Unciv#9895] opened 2023-08-08 11:32 UTC
**Platform**
Archlinux arm (aarch64) and Archlinux (x86_64)

**Version**
AUR 4.7.12.REL-1

**Describe the bug**
Buying a worker and having him build a road glitches the game out and duplicates it sometimes.

**To Reproduce**
1. Start a game
2. Unlock roads
3. Buy a worker when you have enough money
4. Tell it to build a road
5. Go to next unit
6. Sometimes it is the same worker
7. move it somewhere else
8. You duplicated the worker

**Expected behavior**
The worker starts work on the road and I can go to the next unit with the button up right.

**Comment by Knirps1** [comment] 2023-08-08 11:34
After further testing this seems to work also with build workers and other buildings.

**Comment by yairm210** [comment] 2023-08-08 11:40
Duplicate of #9887

**Comment by yairm210** [comment] 2023-08-08 11:40
Solved in latest version

**Closed by yairm210** 2023-08-08 11:40 UTC
Labels: bug

**Comment by Knirps1** [comment] 2023-08-08 11:42
Forgot to look at closed Issues.
