### ISSUE TITLE
"Civilizations" Section in New Game doesnt show in mobile 3.14.6-patch 2

### ISSUE THREAD

**Issue by BFUR64** [yairm210/Unciv#3887] opened 2021-05-07 03:36 UTC
Update: Might be caused by my sd card dying on my phone, now that I got rid of it the game seems to be fine.

Oppo A5s - Patch 2
![180219644_1812654888907159_205741212569980151_n](https://user-images.githubusercontent.com/78485623/117392884-89792200-af25-11eb-83d8-dbb0aa634af1.jpg)
![181917308_1209880762775794_6123373898034474708_n](https://user-images.githubusercontent.com/78485623/117392890-8b42e580-af25-11eb-959a-e595106fb350.jpg)

PC
![image](https://user-images.githubusercontent.com/78485623/117392926-985fd480-af25-11eb-9bfd-d72b1a6eb022.png)
![image](https://user-images.githubusercontent.com/78485623/117392931-9b5ac500-af25-11eb-97da-157c309c0cc8.png)

PC - Patch 2
![image](https://user-images.githubusercontent.com/78485623/117394297-7ca9fd80-af28-11eb-8c22-e408a758c61a.png)
![image](https://user-images.githubusercontent.com/78485623/117394308-7fa4ee00-af28-11eb-908a-d31b275ad28c.png)

**Comment by jahodovykolac** [comment] 2021-05-07 08:34
I have similar problem - I have buttons disappearing on the Load game screen.

**Comment by yairm210** [comment] 2021-05-07 08:55
Can't reproduce on my android device :/

**Comment by jahodovykolac** [comment] 2021-05-07 09:10
Looks like I have a separate problem from this, will open a new issue

**Comment by BFUR64** [comment] 2021-05-07 13:19
> Can't reproduce on my android device :/

Update, I think its caused by the sd card dying on my phone. Im not sure if this is related but its a coincidence to say the least, getting rid of it the game seems to be fine at this point.

**Comment by yairm210** [comment] 2021-05-07 13:30
Ok, interesting
I'm closing this then

**Closed by yairm210** 2021-05-07 13:30 UTC
Labels: bug
