### ISSUE TITLE
AI doesn't make use of the Transform feature

### ISSUE THREAD

**Issue by NalmTheNam** [yairm210/Unciv#9720] opened 2023-07-02 15:58 UTC
**Platform**
Ubuntu 22.04 64 bit.

**Version**
4.7.5-patch1 (Build 885)

**Describe the bug**
A human player's units could transform into a different unit, and AI units could but does not transform into a different unit.

**To Reproduce**
1. Download/make a mod that allows a unit transforming into a unit (Archer transforming into a Warrior). Minimum civilizations: 1.
2. Create a new game with the Spectator civilization with other civilization(s).
3. Wait for the civilization(s) to build their first unit.
4. Observe the unit. You will notice that it doesn't transform.

**Expected behavior**
AI units could also transform into a unit with human players.

**Screenshots**
![image](https://github.com/yairm210/Unciv/assets/75718836/35056094-50f2-48a8-ad5b-eb0e28a0fbd3)

After 5 turns...
![image](https://github.com/yairm210/Unciv/assets/75718836/ce170cf0-3839-4f8d-baa6-739e718bf721)

Civilopedia
![image](https://github.com/yairm210/Unciv/assets/75718836/2c42ccf7-a66a-47f6-8df6-74b7f69a79c3)

**Comment by yairm210** [comment] 2023-07-02 16:34
Not a bug, there is simply no way to write a general AI that knows when it is best to transform
Unless you have a suggestion m

**Comment by NalmTheNam** [comment] 2023-07-03 02:41
I have suggestions for transform priorities: 
Priority #1: If a unit can transform into a civilian unit that can construct Land improvements, determine if the number of civilian units are enough. If enough, don't transform and move to priority #2

Priority #2: If a melee unit can transform into a stronger melee unit or a ranged unit, determine if the terrain they are standing on is:
1. Has an elevation of 1 or more
2. Is a rough terrain

If the terrain has an elevation of 1 or more and is a rough terrain, transform into a ranged unit
Otherwise transform into a melee unit

This will work best for now, I think

**Comment by trentonk23** [comment] 2023-07-14 14:32
what mod is this?? human?!!?

**Comment by yairm210** [comment] 2023-08-11 09:16
Sorry, after thinking through this again with still no good methodology, I'm going to close this as simply "not workable"

**Closed by yairm210** 2023-08-11 09:16 UTC
Labels: bug
