### ISSUE TITLE
Foreign Civs accept ridiculous peace deals

### ISSUE THREAD

**Issue by CIZUK** [yairm210/Unciv#6548] opened 2022-04-14 10:57 UTC
I've noticed that when you have probably about twice the military power of an opponent they will accept anything for peace, even handing over all of their cities and resources and paying so much gold that they're in financial debt. The amount of military force you have near their borders is irrelevant.
As the peace treaty is only for a short time, it makes it a lot easier to destroy the civilisation. They used to do this when they had no military at all, but not when they still had a decent size military.

**Comment by xlenstra** [comment] 2022-04-14 16:24
Duplicate of #5490.

**Closed by xlenstra** 2022-04-14 16:24 UTC
Labels: bug
