### ISSUE TITLE
Research agreements in mods with non-default era names are broken

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4277] opened 2021-06-26 11:45 UTC
![Screenshot_20210626-144410_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/123511926-140c1100-d68d-11eb-9b8a-31c8524473cc.jpg)

amogus

**Comment by SomeTroglodyte** [comment] 2021-06-27 11:04
What's "amogus"? [this one](https://unanything.fandom.com/wiki/Amogus_(disease))?
Also, not enough info to repro. I know there's a mod using water as currency, but which one?

**Comment by logicminimal** [comment] 2021-06-27 13:22
> What's "amogus"? [this one](https://unanything.fandom.com/wiki/Amogus_(disease))?
> Also, not enough info to repro. I know there's a mod using water as currency, but which one?

Well i definitely didn't mean it as a disease name, it is just a sarcastic version of game among us, i just put it there, there is no reason behind it

it's the deciv redux mod, sorry for lack of information, i assumed you would guess from the screenshot

**Comment by jahodovykolac** [comment] 2021-06-29 10:01
- Probably not caused by different era names, Water (Gold) is the broken thing here
- This was fixed in a version earlier than Deciv, so it may be a mod issue (outdated mod)

**Comment by yairm210** [comment] 2021-07-02 13:12
Resolved by #4336

**Closed by yairm210** 2021-07-02 13:12 UTC
