### ISSUE TITLE
Idle unit missing for units created in the turn

### ISSUE THREAD

**Issue by Benrate** [yairm210/Unciv#9943] opened 2023-08-19 09:49 UTC
**Platform**
Android

**Version**
4.7.11

**Describe the bug**
When an unit is product in the turn then the unit is not in the next unit list.
We must check in the unit overview to check which unit is idle

**To Reproduce**
Start  a new turn with a unit incoming. 
Checked with 1 new unti type workboat in one turn. But i for others cases.

**Expected behavior**
Get new units in idle list for next unit

**Screenshots**
Options 
![Screenshot_20230819_114635_Unciv](https://github.com/yairm210/Unciv/assets/142661075/51e8625b-b203-4cbf-8e97-ec8fb3172057)

**Comment by yairm210** [comment] 2024-03-14 19:17
Closing as "cannot reproduce" - if you have a save file with an example we can reopen

**Closed by yairm210** 2024-03-14 19:17 UTC
Labels: bug
