### ISSUE TITLE
City-states are able to capture cities

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3714] opened 2021-03-18 20:06 UTC
Version 3.13.8, a city-state captured an enemy city. Aren't they supposed to destroy the cities?
![16160978072567529264613703940012](https://user-images.githubusercontent.com/79529669/111690408-6daea500-882d-11eb-93fa-81adc3876b9d.jpg)

Also just a question, what is locking assigned population useful for?

**Comment by yairm210** [comment] 2021-03-18 21:03
Not a bug - this is the functionality in Civ V, and was confirmed by a discord poll.

**Comment by yairm210** [comment] 2021-03-18 21:03
Locked population means you (and the auto-whatsits) can't accidentally reassign it

**Closed by yairm210** 2021-03-18 21:03 UTC
Labels: bug
