### ISSUE TITLE
Create a multiplayer game with incorrect ID

### ISSUE THREAD

**Issue by kamilsuchy** [yairm210/Unciv#3530] opened 2021-01-13 21:43 UTC
**Describe the bug**
We can create a multiplayer game with incorrect our ID

![1 (1)](https://user-images.githubusercontent.com/44306803/104513863-a1ccd600-55f0-11eb-9343-a8814e79eb0a.png)
![2 (1)](https://user-images.githubusercontent.com/44306803/104513866-a3969980-55f0-11eb-8aee-39ae9f720ac5.png)
![3 (1)](https://user-images.githubusercontent.com/44306803/104513871-a5f8f380-55f0-11eb-9e37-4e6ac1c91f19.png)

**Comment by yairm210** [comment] 2021-01-14 20:46
Ah I seee
It's not actually a bug
If you put random text there that can't be parsed as an I then it recognizes it
The text you put, though, CAN be a valid ID, so the game says "okay looks legit"
The fact that it isn't the ID you wanted isn't something the game can detect
Closing this as "not a bug"

**Closed by yairm210** 2021-01-14 20:46 UTC
Labels: bug
