### ISSUE TITLE
Feature request: Better diplomacy overview screen

### ISSUE THREAD

**Issue by OptimizedForDensity** [yairm210/Unciv#7106] opened 2022-06-08 18:04 UTC
It's hard to differentiate the different colors of lines on the diplomacy overview (or even to know what the colors mean since there's no legend). According to the eyedropper tool from Gimp, there are 4 colors of lines in this image yet I, who isn't even colorblind, can hardly differentiate between 2 of them unless I stare at them for a while. I think a key and more line differentiation (dotted, dashed, dot-dashed, very large differences in line thickness, black line outlines, etc.) would definitely help.

![Diplomacy screen](https://files.catbox.moe/epcsuu.png)

**Comment by zhan313** [comment] 2022-06-09 01:55
I use this diagram and stat screen to test if allied CS bonus works for ai, for mods testing

**Comment by yairm210** [comment] 2023-03-19 20:57
Duplicate of #7870 , discussed in more detail there

**Closed by yairm210** 2023-03-19 20:57 UTC
Labels: feature
