### ISSUE TITLE
Religion follower count bug

### ISSUE THREAD

**Issue by yairm210** [yairm210/Unciv#4891] opened 2021-08-17 12:33 UTC
**Platform**
Android

**Version**
3.16.4-patch1

**Describe the bug**
java.lang.ArithmeticException: 
  at com.unciv.logic.city.CityInfoReligionManager.updateNumberOfFollowers (CityReligion.kt:131)
  at com.unciv.logic.city.CityInfoReligionManager.updatePressureOnPopulationChange (CityReligion.kt:92)
  at com.unciv.logic.city.PopulationManager.addPopulation$core (PopulationManager.kt:91)
  at com.unciv.logic.city.CityInfo.endTurn (CityInfo.kt:477)
  at com.unciv.logic.civilization.CivilizationInfo.endTurn (CivilizationInfo.kt:606)
  at com.unciv.logic.GameInfo$nextTurn$1.invoke (GameInfo.kt:106)
  at com.unciv.logic.GameInfo.nextTurn (GameInfo.kt:144)
  at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke (WorldScreen.kt:592)
  at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke (WorldScreen.kt:56)
  at kotlin.concurrent.ThreadsKt$thread$thread$1.run (Thread.kt:30)

**Comment by xlenstra** [comment] 2021-08-17 14:35
Duplicate of #4880, happens when population is 0 when calculating the amount of followers. Can be resolved by putting
`if (cityInfo.population.population <= 0) return` at the start of `updateNumberOfFollowers`.
I'm currently away, feel free to fix this.

**Closed** 2021-08-18 08:07 UTC
Labels: bug
