### ISSUE TITLE
Seaport and Harbor Not Adding Resources 

### ISSUE THREAD

**Issue by Seadog18** [yairm210/Unciv#3203] opened 2020-09-30 19:16 UTC
**Describe the bug**
When building or purchasing a harbor or a seaport, there appear to be no additional resources from water tiles granted as a result. 

See #3153

**To Reproduce**
1. View a coastal city without seaport or harbor, observe worked water tiles. 
2. Build or purchase seaport or harbor. 
3. Observe that water tiles are not producing the resources (gold, production) that the building should have granted. 

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**

Building these buildings should provide the resources described in the building description. 

**Screenshots**

**Additional context**
Running most recent Android version.

**Comment by yairm210** [comment] 2020-09-30 20:10
I already checked this and it's not an issue for most players.
A. Are you running with any mods?
B. Do you have a saved game that exhibits this behavior? Please send the game data here if so

**Comment by yairm210** [comment] 2020-10-07 11:20
Is this still relevant? Or should I close it?

**Comment by flecheapolinienne** [comment] 2020-10-12 13:24
Yup, the bug is still there
![Screenshot 2020-10-12 at 09 23 31](https://user-images.githubusercontent.com/45007481/95751458-a2aa4080-0c6c-11eb-8cb1-33e5c7010a46.png)
![Screenshot 2020-10-12 at 09 21 28](https://user-images.githubusercontent.com/45007481/95751464-a5a53100-0c6c-11eb-8e55-9e7088d2023c.png)

**Comment by yairm210** [comment] 2020-10-12 15:02
Doesn't look like you have any resources there though

**Comment by yairm210** [comment] 2020-10-12 15:02
The buildings effects are only on tiles with sea resources

**Comment by flecheapolinienne** [comment] 2020-10-13 17:12
Ok, got it... sorry about my poor understanding of the game mechanic -_-

**Comment by yairm210** [comment] 2020-10-13 17:20
How do you think this could be phrased better?

**Comment by yairm210** [comment] 2020-10-15 12:30
In any case, this looks like a problem with the description, and not a bug
I'm open to suggestions on how to improve the description

**Closed by yairm210** 2020-10-15 12:30 UTC
Labels: bug
