### ISSUE TITLE
I need help with error 

### ISSUE THREAD

**Issue by Casperblaze** [yairm210/Unciv#10512] opened 2023-11-16 15:53 UTC
Hello, I haven't played this game in a while, but I Remember playing it with my father, we had a great time so I decided to start playing it again, this is the 2nd play attempt and I encounter the same error can somebody please help me with it

**Platform:** Android
**Version:** 4.8.17 (Build 927)
**Rulesets:** [Higher quality builtin sounds, Modern Civilizations, Civ V - Vanilla, Brave New World, Resource Recyclers, Community Maps, Extra Buildings, Expanded Warfare, Civ V - Gods & Kings, Dacia Unciv mod, More Luxuries, Closer Cities Distance of 1, 5Hex Tileset, Additional Music Various]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: SM-A536B
API Level: 33

--------------------------------

**Message:**
```
kotlin.UninitializedPropertyAccessException: lateinit property currentTile has not been initialized
	at com.unciv.logic.map.mapunit.MapUnit.getCurrentTile(MapUnit.kt:45)
	at com.unciv.logic.map.mapunit.MapUnit.getTile(MapUnit.kt:203)
	at com.unciv.models.ruleset.unique.Unique$conditionalApplies$relevantTile$2.invoke(Unique.kt:153)
	at com.unciv.models.ruleset.unique.Unique$conditionalApplies$relevantTile$2.invoke(Unique.kt:151)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.unciv.models.ruleset.unique.Unique.conditionalApplies$lambda$10(Unique.kt:151)
	at com.unciv.models.ruleset.unique.Unique.conditionalApplies(Unique.kt:291)
	at com.unciv.models.ruleset.unique.Unique.conditionalsApply(Unique.kt:68)
	at com.unciv.models.ruleset.unique.UniqueMap$getMatchingUniques$1.invoke(Unique.kt:442)
	at com.unciv.models.ruleset.unique.UniqueMap$getMatchingUniques$1.invoke(Unique.kt:442)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequenceBuilderIterator.yieldAll(SequenceBuilder.kt:172)
	at kotlin.sequences.SequenceScope.yieldAll(SequenceBuilder.kt:92)
	at com.unciv.logic.map.mapunit.MapUnit$getMatchingUniques$1.invokeSuspend(MapUnit.kt:215)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at kotlin.sequences.SequencesKt___SequencesKt.any(_Sequences.kt:1218)
	at com.unciv.logic.map.mapunit.MapUnit.hasUnique(MapUnit.kt:227)
	at com.unciv.logic.map.mapunit.MapUnit.hasUnique$default(MapUnit.kt:222)
	at com.unciv.logic.map.mapunit.MapUnitCache.updateUniques(MapUnitCache.kt:81)
	at com.unciv.logic.map.mapunit.MapUnit.updateUniques(MapUnit.kt:244)
	at com.unciv.logic.map.mapunit.MapUnit.setTransients(MapUnit.kt:509)
	at com.unciv.models.ruleset.unit.BaseUnit.getMapUnit(BaseUnit.kt:84)
	at com.unciv.logic.automation.civilization.ReligionAutomation.buyInquisitorNear(ReligionAutomation.kt:176)
	at com.unciv.logic.automation.civilization.ReligionAutomation.spendFaithOnReligion(ReligionAutomation.kt:67)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:47)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:327)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:376)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:602)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher.$r8$lambda$GFMOlD6QMgmLfgwAvPAW33Ob6HE(Unknown Source:0)
	at com.unciv.utils.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```
**Save Mods:**
```
[Modern Civilizations, Brave New World, Expanded Warfare, Resource Recyclers, Civ V - Gods & Kings, Community Maps, Dacia Unciv mod, More Luxuries, Closer Cities Distance of 1, Extra Buildings, 5Hex Tileset]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```

**Comment by tuvus** [comment] 2023-11-16 21:56
It might have something to do with mods. The important line in your error is buyInquisitorNear(ReligionAutomation.kt:176), which searches through the ruleset (determined by the mods) for a unit that can act like an Inquisitor. 

Could it be that we are trying to get the current tile of a hypothetical MapUnit that hasn't been placed yet called by some unique checking code?

**Comment by Casperblaze** [comment] 2023-11-16 22:13
Pretty fascinating that you saw that in all the code, but therefore I think that's not fixable, that's something about the mods compatibility but Is there atleast a way to find out which of the mods is causing the error

**Comment by SeventhM** [comment] 2023-11-17 23:54
Someone correct me (haven't checked the save yet), but is this not a duplicate of #10425? ~~One of us should probably pr a fix for that~~

**Comment by SeventhM** [comment] 2023-11-18 01:34
Crash starts in `mapUnitCache.updateUniques` during `getMapUnit`. Therefore, regardless of if the unique that is being checked would return false or not is irrelevant. The fake unit isn't spawning in the first place

Sure, we can have concerns regarding the AI not recognizing unit roles due to blocking conditionals. But even if that was the case, you would still need to address 10425 first in some way, or else we can't even reach a point of the AI checking the unit role

**Comment by yairm210** [comment] 2023-11-19 20:29
Wow, a Crocodile Dundee "this is a knife" reference! I am getting more and more convinced that you're actually my father in an alternate universe, your reference bag is almost entirely equivalent

And... To answer your question, yes, I independently came up with the #10425 solution before I saw your comment, so I think that despite how ugly it looks it's the way to go. If anyone has a better solution to replace it later, fantastic, if not, let's at least fix the bug

**Closed** 2023-11-19 21:04 UTC
Labels: bug

**Comment by yairm210** [comment] 2023-11-19 21:06
That solves the "bug" part. However, the point remains that the "tile entering" uniques are all cached into booleans in UpdateUniques, which means that conditionals placed upon them may not work. Sounds like yet another mod checker addition
