### ISSUE TITLE
City garrison bug/feature fix

### ISSUE THREAD

**Issue by bitappend** [yairm210/Unciv#3205] opened 2020-10-01 11:56 UTC
Getting unreliable results when trying to select a Bomber or selecting destinations. It's not exclusive to aircraft. Just an example. I have tried to see where the selective zone is to choose from the garrison and not open the city window. But when I click in the same spot, sometimes the garrison picked opens and sometimes the city window opens. I dislike that it's sometimes* and random*. Super annoying when trying to move units to another city. Have to go back and click again and again until I can do a simple movement

**Is your feature request related to a problem?
The issue may be due to Android screen sizing and limitations. And or finger sizing. 

**Describe the solution you'd like**
An explicit zone to open the garrison. Perhaps having the city units icon bigger and a blank circle for City's without a garrison. Like a landing pad sort of thing.

**Describe alternatives you've considered**
An alternative which mightdwork  and would be more clicks. Would be for the garrison window to open by default when exiting the city view window. This does still leave issue when trying to chose a destination city for movement.
************
A better choice would be garrison one click. Then a second click will open the city view window.

**Comment by natrius** [comment] 2020-10-02 13:03
Here it is like that: 
Press on the city-name and the city-name moves down. This happens on empty cities as well. If there is a unit in the city, on top it shows the unit. When pressing the unit-icon, the unit is now selected. When pressing the city-name again, the city-window opens. 

To see beforehand is a bit had, the city-name has a small part of a circle on top if there is a unit garrisoned(?).  That circle mabye bigger.

Is that what you mean? Thats not random at all.

**Comment by bitappend** [comment] 2020-10-02 15:06
That is not consistent  behavior i have seen in any of the versions i have used.  Sometimes the city name moves down. sometimes it opens the city window. its random. 
I think it would be a great idea if the city name moved down on the first click revealing the garrison(and move to destination option). and only having the city window open on the second click. that would definitely fix the problem

**Comment by natrius** [comment] 2020-10-02 17:03
I tried it now multiple times with different cities. One-press: city-name gets down. Second-press: city-screen opens. "exit city" and the city-name is back up again, the screen is centered and i can start from the beginning. But when i'm in the city-screen and pressing the phone-back instead of "exit city", the city-name stays at the bottom and the game-screen is not centered. And these different behaviors are consistent for me, using 3.10.12 on android. 

That maybe should be changed so its the same @yairm210 ?

Other than that: Are you sure you are doing the same thing every time? @bitappend

**Comment by bitappend** [comment] 2020-10-02 19:21
I am sure. It's more obvious when I'm moving a squadron of 6 bombers as I'm clicking in one city then another right after each other. It's random if it opens the garrison or city. 


I suspect what might be happening is a  variable is not being cleared in the code under some circumstances. Perhaps right after i move(give destination order) to the first plane in the squadron. Or it might be a glitch in the animation sequence of city name move down/up hasn't completed.   Sometimes the frame rate is dropped badly when I'm on a high turn game.

**Comment by bitappend** [comment] 2020-10-02 21:17
The more I think about it, the more I believe it the animation routine causing the issue. Can the animation be removed and have the city name instant drop/raise? I think it's not clearing the flag until the sequence is complete, thus on a game with slow frame rate or if the user clicks to fast it will not be in the proper state.

**Comment by natrius** [comment] 2020-10-03 18:37
Okay, so what i was able to reproduce was:
If you open a city-screen and exit it, the city-name moves bck to the default position. If you press the city-name again before it reaches its default podition, you instantly are opening the city-screen again. 
Thats basically the same thats happening with the bombers - managed to do this once with them again. 

So, not random, you are just sometimes faster when pressing the last city again? 

I guess the better behaviour would be the city-name moving back down again instead of opening the city-screen.

**Comment by bitappend** [comment] 2020-10-03 19:29
Sometimes I'm not moving fast. Usually when I'm past turn 500 in the game. The frame rate drops to aBout 1fps. With a turn based game it's almost intolerable.  This seems to be thesituation  where it's not tolerable.


I do suspect there is another instance where it's happening. Either way I think nixing the animated city name movement might help.

**Comment by yairm210** [comment] 2022-10-07 09:32
Closing since performance improvements should have mitigated this

**Closed by yairm210** 2022-10-07 09:32 UTC
Labels: feature
