### ISSUE TITLE
Autosave Crash, Manual Save Crash

### ISSUE THREAD

**Issue by iamtimsson** [yairm210/Unciv#6292] opened 2022-03-07 00:40 UTC
Android 9, Unciv 3.19.14 and since a long ago update, maybe one year ago or more. I cannot seek out last working version, older github apks won't successfully install. Newer, signed apks will.

Quick start or new game, at end of turn or when saving manually, immediate crash to desktop, closing application. No alert or notice.

I believe it has to do with not having storage permissions required and enabled for the app in my android version. No storage options are available in app info.

Game cannot be played. Autosave max 10 turns. Cannot disable autosave.

If I manually save to chosen location, save file will populate, but app will still crash. Game used to work. I would really like to play again. Thanks for your work.

**Comment by SomeTroglodyte** [comment] 2022-03-07 12:11
Not enough information - by a long shot. We'd _need_ the system logs - I believe I have explained somewhere before you either need root and any one of the logcat/catlog apps, or need adb debugging enabled and matlog then tells you what to do to grant minimal permissions correctly.

I'd also bet (personal prejudice) it's your box, not Unciv updates, that are the cause - checking that would mean wipe data partition (aka factory reset) then configure the OS minimally and try Unciv before anything else -> if it works, restore your backup (proper nandroid partion backups again need some control over your system, I'd do that using TWRP - a custom recovery) and know you'll need a proper migration soon... Maybe even creating a separate "user" as some droid versions offer might be enough.

**Comment by yairm210** [comment] 2022-06-20 20:09
Since no new info has been updated for 3 months, closing as "cannot investigate"

**Closed by yairm210** 2022-06-20 20:09 UTC
Labels: bug
