### ISSUE TITLE
non-highlighted tech

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3525] opened 2021-01-13 13:09 UTC
if you select a distant unavailable technology, it will turn light blue. all the necessary previous grays turn blue, and among the green ones only ONE (not all) will change color. the one that is examined first turns dark green. it's good. but shouldn't all the other greens be different from both the rest and the dark green (the first one in the chain)? like light blue (the last one in the chain) is different from both the blue and grays among the unavailable technologies.

similar to this let the technology that is currently being researched be highlighted in a separate color in the technology tree so that it is clear which technology will be researched after pressing the close button instead the select button.

also the color of the selected GREEN technology is very similar to the color of the unavailabled. need to be changed.

I continued to play after updating the game and realized how important it was to change the color scheme of the Incas in #3469))) it really became more readable:D
https://drive.google.com/file/d/1Ox1ahY33_y8QtP4VlREkixDn-RRqG3Sk/view?usp=drivesdk

**Comment by yairm210** [comment] 2021-01-14 20:09
It's hard to tell what you're talking about to be honest.
![image](https://user-images.githubusercontent.com/8366208/104643327-ee79e500-56b4-11eb-927c-4b30fca3e504.png)

So an example.
Civil service is the *fina tech* - light blue
Philosophy is an *intermediate tech* - blue
Calendar is the *currently researched tech* - and so dark green.
Which of these do you feel needs to be a different color?

**Comment by yairm210** [comment] 2021-01-24 18:06
?

**Comment by yairm210** [comment] 2021-01-28 19:53
Closing this, not sure what you think the problem is :/

**Closed by yairm210** 2021-01-28 19:53 UTC
Labels: feature
