### ISSUE TITLE
Very Bad Memory Leak

### ISSUE THREAD

**Issue by PolygonalPhantom** [yairm210/Unciv#7929] opened 2022-10-18 19:04 UTC
**Platform**
Mobile(Android), ARM 32-bit, maj. Game version 4.x.x

**Version**
Play Store, game version 4.2.12

**Describe the bug**
Game starts having lag spikes after 15-20mins of gameplay, after that the phone locks up and 2 things will happen: either the phone manages to save itself and do a soft restart or the entire thing dies and it reboots. Most likely a memory leak.

**To Reproduce**

N/A

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):

N/A

**Expected behavior**
A clear and concise description of what you expected to happen

Consistent gameplay without crashes or lag spikes

**Screenshots**
If applicable, add screenshots to help explain your problem

N/A

**Additional context**

N/A

**Comment by yairm210** [comment] 2022-10-19 04:24
Duplicate of #7876

**Closed by yairm210** 2022-10-19 04:24 UTC
Labels: bug
