### ISSUE TITLE
local mods don't work after you locally delete one of them (android)

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4739] opened 2021-08-03 09:35 UTC
i locally deleted one of my self made mods but then put it back it didnt work i even changed the name but it doesnt show up in unciv, then i tried moving out then moving in that file but no chance
is this json broken or is something wrong with the game? btw even when i pressed delete the mod (local mod) the file for it stood, i even tried to copy paste it with another name, change some of the files but doesnt work. 3.15.18

```
[
	{  // Simplify this when more than one element per tilefilter unique gets implemented
		"name": "Petra",
		"culture": 1,
		"isWonder": true,
		"greatPersonPoints": {"Great Engineer": 1},
		"uniques": ["Must be next to [Desert]", "[+1 Food, +1 Production, +1 Gold] from [Desert] tiles without [Flood plains] [in this city]", "[-1 Food, -1 Production, -1 Gold] from [Oasis] tiles [in this city]", "[-1 Food, -1 Production, -1 Gold] from [Hill] tiles [in this city]", "[+1 Gold] from [Desert] tiles without [Oasis] [in all cities]", "Provides a free [Amphitheater] [in this city]", "[+6 Culture] once [Archaeology] is discovered"],
		"requiredTech": "Currency",
		"quote": "'...who drinks the water I shall give him, says the Lord, will have a spring inside him welling up for eternal life. Let them bring me to your holy mountain in the place where you dwell. Across the desert and through the mountain to the Canyon of the Crescent Moon...'  - Indiana Jones"
	}
]
```

edit: i made a small mod that adds some op warrior and im sure there are no json errors on it but it doesnt show up

**Comment by yairm210** [comment] 2021-08-03 16:05
What os? Did you restart Unciv?

**Comment by logicminimal** [comment] 2021-08-03 16:40
> What os? Did you restart Unciv?

android 8.1.0 samsung experience 9.5.0 J7 Prime. i tried everything other than downloading and re installing the game which should work but i shouldnt need to uninstall and re install a game just cause i might have misclicked a button. this problem started in 3.15.17 and even after i updayed it to 3.15.18 it still persist. i also tried to make a brand new mod and not even that shows up

**Comment by SomeTroglodyte** [comment] 2021-08-03 19:27
"put it back"? "Moving"? "copy paste"? If you can do so in /data/data/com.unciv.app/files/mods then... No, I'd better shut up.

**Comment by logicminimal** [comment] 2021-08-03 19:35
> "put it back"? "Moving"? "copy paste"? If you can do so in /data/data/com.unciv.app/files/mods then... No, I'd better shut up.

nope dude, i mean i closed the game, put the mod folder somewhere else, booted the game, closed it then put it bacj where it was, but i mean not even a dummy mod works so im sure somehing is wrong. i would bet uninstalling then installing the game would solve it (for now) but I'm not gonna do it

**Comment by SomeTroglodyte** [comment] 2021-08-03 21:22
Well, I'm betting your copying produces folders and files owned by root, with chmod 0600 on most files, and SELinux context s0.

**Comment by logicminimal** [comment] 2021-08-03 21:41
> Well, I'm betting your copying produces folders and files owned by root, with chmod 0600 on most files, and SELinux context s0.

could this be fixed or be reproduced? i deleted it inside unciv btw dont know if i mentioned it

**Comment by logicminimal** [comment] 2021-08-04 08:49
so... any idea or fix?

**Comment by logicminimal** [comment] 2021-08-04 09:03
> Well, I'm betting your copying produces folders and files owned by root, with chmod 0600 on most files, and SELinux context s0.

if this were the case then my new dummy mod should have worked

**Comment by logicminimal** [comment] 2021-08-06 09:30
@yairm210 @SomeTroglodyte as i have said i uninstalled then re installed the game and its fixed but this is going to occur again so this isnt solved at all yet. needs replication to point where the problem is

**Comment by logicminimal** [comment] 2021-08-06 09:41
edit: the problem still happens even when i havent even deleted the mod

**Comment by logicminimal** [comment] 2021-08-06 09:41
maybe this has to do something with the problem people have been mentioning that they can't see the mod that they downloaded after downloading

**Comment by logicminimal** [comment] 2021-08-06 11:34
another edit: after i uninstalled then reinstalled the game the problem still persist so i tried deleting all the data for unciv in options but it still didn't work at all and the same problem still happens + i lost my memorical saves from months ago

**Comment by SomeTroglodyte** [comment] 2021-08-06 17:04
Still no specific steps to reproduce.
I'm still convinced you're simply messing up Linux file system permissions because you're using tools you don't understand.
If you tap 'clear storage' for Unciv, _of course_ your settings, saves and mods are gone, no reason to complain. There's the custom save location feature to partially work around that.

**Comment by logicminimal** [comment] 2021-08-06 17:28
> Still no specific steps to reproduce.
> I'm still convinced you're simply messing up Linux file system permissions because you're using tools you don't understand.
> If you tap 'clear storage' for Unciv, _of course_ your settings, saves and mods are gone, no reason to complain. There's the custom save location feature to partially work around that.

im not messing up with anything they literally stop appearing in mods folder after a few unsuccessful tries to make a mod or after deletion

**Comment by logicminimal** [comment] 2021-08-09 10:06
any idea why this happens? i doubt if its the file system cause its fixed when i uninstall then install the game

**Comment by logicminimal** [comment] 2021-08-20 14:52
updaye: im on 3.16.4-patch2 and the problem still persists, i cant even download my mods from github, i typed this exact text into the field and it doesnt work, try for yourself

https://github.com/logicminimal/SightBonus-Reimplemented

**Comment by yairm210** [comment] 2022-06-20 20:36
Closing as not reproducable

**Closed by yairm210** 2022-06-20 20:36 UTC
