### ISSUE TITLE
Game crashing on end of turn in LOTR mod multiplayer game

### ISSUE THREAD

**Issue by AlatarTheYoung** [yairm210/Unciv#9533] opened 2023-06-06 19:20 UTC
**Platform**
Both Android and Windows 8.1 64 bits

**Version**
4.6.17 build 874

**Describe the bug**
Game crash on end of turn

**To Reproduce**
Load the game, play a turn, click Next turn

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>
**Platform:** Desktop
**Version:** 4.6.16 (Build 873)
**Rulesets:** [LOTR Unciv, LOTR-Unciv-rebirth, Tech Stopper _Renaissance _, Civ V - Vanilla, Latin American_Civs, LOTR reworked, Civ V - Gods & Kings, Bamboo Deciv Expans, DeCiv Redux, Thin Bubbly Borders, Epic of Fantasy, Only Mod Civilizations]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

OS: Windows 8.1
Java: Oracle Corporation 25.232-b09
	Max Memory: 910 MB

--------------------------------

**Message:**
```
kotlin.UninitializedPropertyAccessException: lateinit property currentTile has not been initialized
	at com.unciv.logic.map.mapunit.MapUnit.getCurrentTile(MapUnit.kt:42)
	at com.unciv.logic.map.mapunit.MapUnit.getTile(MapUnit.kt:198)
	at com.unciv.models.ruleset.unique.Unique$conditionalApplies$relevantTile$2.invoke(Unique.kt:142)
	at com.unciv.models.ruleset.unique.Unique$conditionalApplies$relevantTile$2.invoke(Unique.kt:140)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.unciv.models.ruleset.unique.Unique.conditionalApplies$lambda$9(Unique.kt:140)
	at com.unciv.models.ruleset.unique.Unique.conditionalApplies(Unique.kt:237)
	at com.unciv.models.ruleset.unique.Unique.conditionalsApply(Unique.kt:54)
	at com.unciv.models.ruleset.unique.UniqueMap$getMatchingUniques$1.invoke(Unique.kt:368)
	at com.unciv.models.ruleset.unique.UniqueMap$getMatchingUniques$1.invoke(Unique.kt:368)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequenceBuilderIterator.yieldAll(SequenceBuilder.kt:172)
	at kotlin.sequences.SequenceScope.yieldAll(SequenceBuilder.kt:92)
	at com.unciv.logic.map.mapunit.MapUnit$getMatchingUniques$1.invokeSuspend(MapUnit.kt:210)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at com.unciv.logic.map.mapunit.MapUnitCache.updateUniques(MapUnitCache.kt:89)
	at com.unciv.logic.map.mapunit.MapUnit.updateUniques(MapUnit.kt:239)
	at com.unciv.logic.map.mapunit.MapUnit.setTransients(MapUnit.kt:443)
	at com.unciv.models.ruleset.unit.BaseUnit.getMapUnit(BaseUnit.kt:82)
	at com.unciv.logic.map.TileMap.placeUnitNearTile(TileMap.kt:491)
	at com.unciv.logic.civilization.managers.UnitManager.placeUnitNearTile(UnitManager.kt:71)
	at com.unciv.models.ruleset.unit.BaseUnit.postBuildEvent(BaseUnit.kt:218)
	at com.unciv.models.ruleset.INonPerpetualConstruction$DefaultImpls.postBuildEvent$default(IConstruction.kt:38)
	at com.unciv.logic.city.CityConstructions.constructionComplete(CityConstructions.kt:439)
	at com.unciv.logic.city.CityConstructions.constructIfEnough(CityConstructions.kt:323)
	at com.unciv.logic.city.managers.CityTurnManager.startTurn(CityTurnManager.kt:19)
	at com.unciv.logic.civilization.managers.TurnManager.startTurn(TurnManager.kt:72)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:333)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:574)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
**Save Mods:**
```
[LOTR reworked]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
H4sIAAAAAAAAAOy9a5Pbtpqu/Ve0+8s7u8r0[...]bCwA=
```
</details>

**Expected behavior**
The next turn to unfold

**Screenshots**
![image](https://github.com/yairm210/Unciv/assets/110571755/d9d761d2-68f0-41f2-8101-c7380159cdff)

**Additional context**
Thanks for taking the time ! And for the game at all !

**Comment by AlatarTheYoung** [comment] 2023-06-06 19:42
I can give the complete save file code if necessary on Discord. The comment size seems not to be fitting.

**Comment by yairm210** [comment] 2023-06-07 06:10
I see
Then we need to cache that without conditionals, and then apply the conditionals on the check...

**Comment by AlatarTheYoung** [comment] 2023-06-07 08:16
Thanks a lot for the investigation and the fix !

**Comment by yairm210** [comment] 2023-06-07 10:40
@SomeTroglodyte You're right but then I wonder what happens if a unit loses this ability while there - it would get stranded... 
I'd prefer to not accommodate conditionals for those to begin with

**Comment by RealBamboolord** [comment] 2023-06-07 11:18
That conditional of the Mirkwood spider shouldn't have even been there in the current version of the mod, seems like I forgot to remove it

**Comment by RealBamboolord** [comment] 2023-06-07 11:21
I checked the mod checker yesterday and it didn't give a warning

**Comment by ferrosa** [comment] 2023-06-07 12:37
Just to mention: this is also a problem on the newest Unciv version (4.6.18-patch1).
And this issue is a duplicate of https://github.com/yairm210/Unciv/issues/9532.

**Closed** 2023-06-07 12:50 UTC
Labels: bug
