### ISSUE TITLE
Who does the bug when we have a free tech chance we can choose the future tech?😅

### ISSUE THREAD

**Issue by lishaoxia1985** [yairm210/Unciv#1956] opened 2020-02-17 16:01 UTC

**Comment by Whistler11** [comment] 2020-02-18 00:54
Are you saying that there is a bug which lets you select tech that you don't have the prerequisites for?

**Comment by lishaoxia1985** [comment] 2020-02-18 02:13
the bug is which lets you select tech that you don't have the prerequisites for.

**Comment by Whistler11** [comment] 2020-02-18 02:16
Good find!
Is it a specific tech you can select? a specific wonder that makes it happen? 
It seems to be working as intended on my system - I can't select tech i don't have prerequisites for...
Do you have a save file or a screenshot?

**Comment by lishaoxia1985** [comment] 2020-02-18 18:48
you can try to build the wonder "the great library", you will find the bug.

**Comment by Whistler11** [comment] 2020-02-18 20:37
Yep! They're right! You can choose "future tech" without the prerequisites. @yairm210 

![Screenshot_20200219-073415](https://user-images.githubusercontent.com/60082415/74775807-8e36c380-52ea-11ea-98d2-11a35058617f.png)
![Screenshot_20200219-073515](https://user-images.githubusercontent.com/60082415/74775816-91ca4a80-52ea-11ea-906c-90be1979be33.png)

**Comment by Whistler11** [comment] 2020-02-18 20:38
It's only future tech btw. The other options are successfully greyed out as intended

**Comment by JackRainy** [comment] 2020-02-18 21:46
Well spotted! Thank you for finding!
The fix is ready to be merged.

**Closed** 2020-02-19 01:30 UTC
Labels: bug
