### ISSUE TITLE
Game corruption

### ISSUE THREAD

**Issue by bitappend** [yairm210/Unciv#3256] opened 2020-10-13 01:17 UTC
Game crashes just when battle is getting good.

Usually after turn 100 sometime the game data seems to go corrupt. I have seen this over the many iterations of the game these last few months. 
I thought is was my crappy old android. However I now have a new Moto g6 power. I'm still getting same results. I can usually only play 1 out of 10 games to completion without crashing.  I would like to capture data to help troubleshoot. My gut says it's a memory leak of some kind. Normally the fps drops significantly in turns prior, but not always. I can tell crashing is coming soon when the AI turns start taking a long time. The game always crashes when it's processing a next turn.  Or when trying to load from an autosave. 

I have yet to see a version this does not happen. Are others seeing this?

**Comment by EdinCitaku** [comment] 2020-10-14 09:59
Maybe u can safe the game regularly next time u play it? A save state where this bug happens a few rounds after the save would help a lot to reproduce!

**Comment by yairm210** [comment] 2020-10-18 18:46
Can you send a save file? Or even better, an autosave of the urn before it's corrupted? Otherwise there's not much I can do

**Comment by kateyy** [comment] 2020-11-12 13:08
I'm having the same issue; it's the first time though that I'm seeing it. On Android 9, Unciv version 3.11.10 (from F-Droid).
Yesterday the game started to crash when trying to go the the next round. Restarting the game and loading the autosaved worked, but would crash again on "Next round". Today I can't even load the autosave anymore, no idea what changed since then. 

Here's today's, unloadable state: [Autosave.zip](https://github.com/yairm210/Unciv/files/5530728/Autosave.zip)

**Comment by yairm210** [comment] 2020-11-12 17:21
Beg your pardon but that's a completely empty file
Maybe try loading it from Load game > Show autosaves, and taking one with the turn number?

**Comment by kateyy** [comment] 2020-11-12 17:51
Right I missed that. I cannot say for sure if Unciv emptied that file. I don't have any saved games of that broken game. Anyway, I'll post here if it breaks again.

Nov 12, 2020 18:21:20 Yair Morgenstern <notifications@github.com>:

**Comment by kateyy** [comment] 2020-11-12 20:40
This one should do

Nov 12, 2020 18:21:20 Yair Morgenstern <notifications@github.com>:

**Comment by yairm210** [comment] 2020-11-12 21:27
That's really weird, it's working fine for me
I tried going forward a couple of turns and it's fine
Maybe it's a specific action you're taking during your turn? Maybe it's a problem that's since been fixed? Try updating your game to the latest version

**Comment by jwmh** [comment] 2020-11-15 06:22
I have also just started having crashes. Quite a few.
Can no longer play a game to completion.

**Comment by yairm210** [comment] 2020-11-15 08:29
This is really generic and doesn't help at all.
Most crash problems are different from each other.
A. Did you try and load the autosaves of the last turn?
B. Are you on the latest version? (3.11.11+)

**Comment by kateyy** [comment] 2020-12-02 11:21
I didn't see any crashes or save game corruption anymore on the recent versions (3.11.11 or so and later).

**Comment by yairm210** [comment] 2020-12-07 18:54
Okay, closing this for irrelevancy then :)
On 3.11.13+ this should be completely mitigated :D

**Closed by yairm210** 2020-12-07 18:54 UTC
Labels: bug
