### ISSUE TITLE
Next turn, buyInquisitorNear

### ISSUE THREAD

**Issue by CristianUlloa** [yairm210/Unciv#7603] opened 2022-08-04 16:14 UTC
**Platform:** Desktop
**Version:** 4.2.1 (Build 744)
**Rulesets:** [Unciv Vanilla Music Pack, Civ V - Vanilla, FantasiaExtension, Civ V - Gods & Kings, Civ6 mod, Alpha Frontier, Fantasia]
**Last Screen:** `com.unciv.ui.worldscreen.WorldScreen`

--------------------------------

OS: Windows 10
	Windows 10 Pro Version 2004 (Build 19041)
Java: Oracle Corporation 18.0.1.1+2-6
	Max Memory: 4084 MB

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.automation.civilization.ReligionAutomation.buyInquisitorNear(ReligionAutomation.kt:170)
	at com.unciv.logic.automation.civilization.ReligionAutomation.spendFaithOnReligion(ReligionAutomation.kt:63)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:66)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:273)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:579)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda-0(Concurrency.kt:164)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
**Save Mods:**
```
[FantasiaExtension, Unciv Vanilla Music Pack, Fantasia]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
Details in file
```
[bug details.txt](https://github.com/yairm210/Unciv/files/9261347/bug.details.txt)
</details>

**Additional context**
this error occurs when pressing next turn. I've reopened the last auto saved and bought an inquisitor and I don't get an error when I buy it.
[Smeheng - 133 turnos.no-edit.txt](https://github.com/yairm210/Unciv/files/9261283/Smeheng.-.133.turnos.no-edit.txt)

**Comment by yairm210** [comment] 2022-08-04 16:45
Duplicate of #7599

**Closed by yairm210** 2022-08-04 16:45 UTC
Labels: bug
