### ISSUE TITLE
Wrong difficulty rules for AI

### ISSUE THREAD

**Issue by sockybob** [yairm210/Unciv#4222] opened 2021-06-21 08:16 UTC
Not sure if it's intentional or not but it seems like no matter what difficulty you choose, AI will always have "Chieftain" difficulty modifiers applied. And not those that are intended for AI but those that are intended for player. This can be proven by starting a new game as spectator and checking any AI controlled civilization happiness stats. From what i found looking at code there's getDifficulty method in Unciv/core/src/com/unciv/logic/civilization/CivilizationInfo.kt which returns "Chieftain" difficulty ruleset for any non-player controlled civilization. This results in AI being kinda overpowered when playing on any difficulty except lowest.

**Comment by ravignir** [comment] 2021-06-21 08:18
that is how it works in civ5, so not a bug.

**Comment by logicminimal** [comment] 2021-06-21 08:21
> that is how it works in civ5, so not a bug.

what if it is problematic in the original game as well, i think the game should not absolutely stay loyal to the original game as it has bugs too and unciv has a great opportunity to fix it

**Comment by sockybob** [comment] 2021-06-21 11:59
I agree. I do understand that the purpose of it is to compensate AI stupidness, however isn't it better to just make smarter AI?

**Comment by logicminimal** [comment] 2021-06-21 12:32
> I agree. I do understand that the purpose of it is to compensate AI stupidness, however isn't it better to just make smarter AI?

smarter ai = more pass turn time = low universality for devices = overall bad experience

**Comment by sockybob** [comment] 2021-06-21 14:51
> smarter ai = more pass turn time = low universality for devices = overall bad experience

Well i'm personally totally fine with longer turn times if AI will be smarter, it can still be optimized. And i'm pretty sure there's still space for improvements even without writing more complex AI alghoritms.

**Comment by sockybob** [comment] 2021-06-21 15:07
So "Chieftain" difficulty for AI seems to be intended and it's same for Civ 5. But is AI in Civ 5 same to AI in this game? They're obviosly diffirent unless devs somehow got Civ 5 source code and made a copy of all AI algoritms, but in other language.

**Comment by sockybob** [comment] 2021-06-21 15:10
AI gets huge happiness bonuses so they're put lots of cities and can afford having big population in them since happiness, which is intended to be a limiting factor from growing too big, is not really limiting them anymore.

**Comment by sockybob** [comment] 2021-06-21 15:26
My suggestion is to make it so AI stop putting cities literally everywhere. The bonuses for AI can be left since it's a good compensation for its stupidness. At least until it get smarter if that ever going to happen.

**Comment by yairm210** [comment] 2021-06-21 15:37
"just make smarter AI"
Brilliant! If only I had thought of that!

Seriously though, if you have any concrete suggestions, they're welcome. But if not, this is completely unhelpful. If I know what to improve, I already would have.

**Comment by yairm210** [comment] 2021-06-21 15:38
For example, the cities. What does it get strong? What does it not take into account?

**Comment by sockybob** [comment] 2021-06-21 15:45
> For example, the cities. What does it get strong? What does it not take into account?

I don't know... Didn't looked in code. For me AI can put cities anywhere if there's no good places left. They put cities in places with no luxury resources, in plain thundra, in desert, everywhere. Even if there's no much free tiles left which is not occupied by other cities.

**Comment by sockybob** [comment] 2021-06-21 15:57
Maybe it makes sence for AI to put cities everywhere since it have lots of spare happiness. I'm suggesting to make it so AI stop abusing its happiness and don't settle more cities if it doesn't need to.

**Comment by sockybob** [comment] 2021-06-21 16:05
Also when i was playing there was civilization with many cities near sea. However they all were at least one tile from coast. They had many luxury and bonus resources on sea tiles but couldn't get them, because there no a single city that can build boats for that. Maybe making it so AI will tend to settle at coast if there's sea tiles near will help.

**Comment by yairm210** [comment] 2021-06-21 16:10
There is already a bias towards coast for AI city settling, but I'll increase it

**Comment by sockybob** [comment] 2021-06-21 16:14
Also noticed in spectator mode that AI can switch production in cities too often. Maybe make it so they won't switch unless it's really needed. Like some treshold for switching, if it didn't exists already.

**Comment by logicminimal** [comment] 2021-06-21 16:59
> There is already a bias towards coast for AI city settling, but I'll increase it

i think rather than increasing tendency for coastal settlements, -if possible- you should give it a chance that the ai settlers will be manipulated to settle in a coast only if it is 1 tiles nearby (or like %67 manipulation chance if 1 tiles away, %33 if 2, %11 if 3 etc)

**Comment by sockybob** [comment] 2021-06-21 17:02
> Also noticed in spectator mode that AI can switch production in cities too often. Maybe make it so they won't switch unless it's really needed. Like some treshold for switching, if it didn't exists already.

Just tested it again and it doesn't seems to be the case anymore. Maybe was fixed in recent updates.

**Comment by yairm210** [comment] 2021-06-21 18:04
I'm closing this.
The suggested 'fix' still just make the game easier to win (read: less interesting) for human players, as things stand.

**Closed by yairm210** 2021-06-21 18:04 UTC

**Comment by AdityaMH** [comment] 2021-06-21 19:55
Don't let making checker AI playing chess.
If you want more challenge, just increase AI level.
If you want more easier, just decrease AI level.
