### ISSUE TITLE
AI magic settlers

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#448] opened 2019-02-07 17:58 UTC
They can construct any improvement in one turn only.

**Comment by yairm210** [comment] 2019-02-07 18:56
....settlers????

**Comment by yairm210** [comment] 2019-02-07 19:08
Where did you see this?
I've followed them around and they do nothing of the sort.

**Comment by Am-per-Sand** [comment] 2019-02-10 16:35
Sorry I mean workers. I observed it only on the tiles previously pillaged, which may be the reason for this.

**Comment by yairm210** [comment] 2019-02-10 18:01
Pillaged tiles are indeed restored after 2 turns - I figure this is the cause
Close the issue if this answers your doubts

**Closed** 2019-02-11 12:42 UTC
