### ISSUE TITLE
Higher res buttons

### ISSUE THREAD

**Issue by skyace65** [yairm210/Unciv#3568] opened 2021-02-01 04:17 UTC
The buttons look a bit low res on desktop. Would it be possible to add higher res images for them? I can make some in inkscape if that's necessary.

EDIT: Wanted to make sure I'm being clear. The images for the buttons themselves, not the icons in the buttons

**Comment by lishaoxia1985** [comment] 2021-03-27 17:19
@skyace65 it don't need to redraw the picture. we can set filter for picture. because we don't want to set filter for all picture, now we close this feature.

**Comment by yairm210** [comment] 2021-03-28 18:40
@lishaoxia1985 No, this is a different problem entirely.
We can totally set the filter for the buttons specifically in the ImageGetter.getRoundedEdgeTableBackground() function:

```kotlin
    fun getRoundedEdgeTableBackground(tintColor: Color? = null): NinePatchDrawable {
        val region = getDrawable("OtherIcons/buttonBackground").region
        region.texture.setFilter(Texture.TextureFilter.MipMapLinearLinear, Texture.TextureFilter.MipMapLinearLinear)
        val drawable = NinePatchDrawable(NinePatch(region, 25, 25, 0, 0)).apply {
            setPadding(5f, 15f, 5f, 15f)
        }
        if (tintColor == null) return drawable
        return drawable.tint(tintColor)
    }
```

The problem is that the current ninepatch takes from a 50x50 circle - namely, OtherIcons/buttonBackground. No matter what filter you put on it, in screen-size resolution, this will look bad.
The problem is that I can't find a way to create a ninepatch from a larger circle and resize (e.g. OtherIcons/Circle). It llooks llike we can choose between either 'scaling the image' or 'having a ninepatch'.

**Comment by lishaoxia1985** [comment] 2021-03-29 07:20
@yairm210 you can try Texture.TextureFilter.Linear, sometimes Texture​.​TextureFilter​.​MipMapLinearLinear has no effect. some days ago I find this problem.

**Comment by yairm210** [comment] 2021-03-29 14:49
I tried these, all the results are still grainier than I would like. When you start from a 50x50 circle, there's a limit to how nice that circle will look no matter what filters you put...

Texture.TextureFilter.MipMapLinearLinear, Texture.TextureFilter.MipMapLinearLinear:
![image](https://user-images.githubusercontent.com/8366208/112854049-1f639680-90b6-11eb-820a-2fddab17c261.png)

Texture.TextureFilter.Nearest, Texture.TextureFilter.Nearest:
![image](https://user-images.githubusercontent.com/8366208/112854209-47eb9080-90b6-11eb-9f32-12d7fe7d238f.png)

Texture.TextureFilter.Linear, Texture.TextureFilter.Linear:
![image](https://user-images.githubusercontent.com/8366208/112854295-63ef3200-90b6-11eb-9a42-a362aac89aba.png)

Texture.TextureFilter.MipMapLinearNearest, Texture.TextureFilter.Linear:
![image](https://user-images.githubusercontent.com/8366208/112854486-9436d080-90b6-11eb-80e8-4c898f0a5981.png)

The magFilter Linear does give noticeably better results - even at full screen with the main menu buttons (the largest use we have), if I wasn't specifically looking for problems I wouldn't have noticed anything, so I think we can mark that as 'good enough'.

![image](https://user-images.githubusercontent.com/8366208/112854992-11624580-90b7-11eb-9f55-2fac4a42e651.png)

**Comment by yairm210** [comment] 2021-03-29 15:16
Nope, I tell a lie... you can't change the filter for the texture without changing it for the entire texture, you were right from the beginning and I was wrong :/
Tried putting this in a separate file, didn't really work with the ninepatch... I'm temporarily giving up on this

**Comment by lishaoxia1985** [comment] 2021-03-29 15:32
You should notice that if you use filter it will make the effect for all the picture, i have not found how to make it for special pictures.
in fact, if you want to use filter (not MipMap) for all the picture, you don't need to use this method. in texturepack, you can set filter, packed files "*.altas" with some words describes this "filter: linear,linear"
by the way, in texturepack, setting filter to MipMap makes no sense. It maybe has some bugs.

**Comment by yairm210** [comment] 2021-07-02 09:58
Done

**Closed by yairm210** 2021-07-02 09:58 UTC
Labels: UI, feature
