### ISSUE TITLE
Civs hits by a nuke declaring war on you

### ISSUE THREAD

**Issue by DavidBVal** [yairm210/Unciv#3507] opened 2021-01-06 10:54 UTC
As the game stands, you can nuke units and/or cities without any consequence past the -50 to diplomacy. Past that, unless I am missing something, you have a free pass on nuking towns or armies everywhere on the map, nothing will happen.

It's easy to use this for an advantage against allies. In a domination game (immortal) I was just left vs an ally (+75) which was far stronger than I. I nuked his armies everywhere, taking my time, before declaring war. We shouldn't be able to land a nuke on 6-7 units without retaliation.

**Comment by yairm210** [comment] 2021-01-06 20:48
??? When you nuke another civ they declare war on you, unless you have a peace agreement in the last 10 turns
Can you send me the game save?

**Comment by ravignir** [comment] 2021-01-08 10:29
Let me tell you how it works in civ5:
During peace agreement you can't nuke them at all: your nuke ranged reduced by their borders+2 tiles in each direction, also you can't nuke any tile that's occupied by their unit +2 tiles around it.
Which i think is stupid, because you don't even need to see that unit, allowing you to use nukes to get to know their units position.

**Comment by DavidBVal** [comment] 2021-01-08 10:51
> ??? When you nuke another civ they declare war on you, unless you have a peace agreement in the last 10 turns
> Can you send me the game save?

Unfortunately I uninstalled and no longer keep the save. I will try to reproduce it in the future, although I can't play in the next weeks. I am pretty sure I had a free nuking run of several rounds and it was not the first time.

**Comment by yairm210** [comment] 2021-01-24 07:53
Closing this as unreproducible, if more evidence comes to light we'll reopen it

**Closed by yairm210** 2021-01-24 07:53 UTC
Labels: feature
