### ISSUE TITLE
After nov 2 release on android button appears to move automated units

### ISSUE THREAD

**Issue by kklasmeier** [yairm210/Unciv#5683] opened 2021-11-15 15:29 UTC
**Platform**
Android

**Version**
Unciv 3.17.15

**Describe the bug**
Once an automated unit is enabled, a new button is appearing every single turn. This button allows automated units to execute their action. This should not happen as automated units should automatically do their work without this pause. The button should be removed and when the turn ends the automated units should automatically do their work

**To Reproduce**

1. Start a new game
2. create a worker
3. set worker to automate
4. play each turn and see a new button starting,"Move automated untis"

**Expected behavior**

Expecting button to not appear and automated units to conduct themselves without being asked.

**Screenshots**

**Additional context**

**Comment by yairm210** [comment] 2021-11-15 16:40
This is intentional, to allow players unit movement after the automatic moves have been carried out
But I agree this could be an optional setting

**Comment by will-ca** [comment] 2021-11-15 20:35
Hm, is it every turn? FWIW, in Civ V the equivalent behaviour only happens when an automated unit has MP left.… But I guess you wouldn't know that until after they've moved, so I suppose what Civ V is doing is to disguise the button as "Next Turn" instead and skipping the "real" Next Turn button if it's not needed, which IMO is more confusing.

**Comment by SomeTroglodyte** [comment] 2021-11-15 21:27
To clarify: "Expected behavior" matches the previous behaviour, which includes _losing opportunities_ you would have if you didn't automate, e.g. a multiturn move ending with MP left.

**Comment by will-ca** [comment] 2021-11-15 22:22
@SomeTroglodyte Just solve the Halting Problem, so you can skip the button if there won't be any MP left.

**Comment by SomeTroglodyte** [comment] 2021-11-16 00:17
You mean, run the whole automation sequence on a clone just to see whether any units would become 'due' again, and that just to see how to name the button? Nah.

**Comment by kklasmeier** [comment] 2021-11-16 02:41
When a turn is over, there is a button to press to end the turn. It is at that time, one can choose to reassign automated units to other duties. Since the new button is added, effectively every turn users have to click two buttons to end the turn. This reduces the game's playability. Would suggest removing the feature altogether, or at a minimum include a Gameplay option to enable.

**Comment by will-ca** [comment] 2021-11-16 03:17
@kklasmeier Disagreed, though TBH I haven't played any full games with it.

Before, what was happening was that if your automated units still had movement points left, they would go to waste because the game was already jumping to the next turn.

E.G. Say you tell your worker to move three tiles on flat ground. On the first turn, they move two tiles. On the second turn, they move one more tile and have one movement point left, which means they should be able to start building an improvement on the second turn. But instead the game cuts to the next turn, so you lose a turn and have to wait a total three turns before you can start building the improvement.

That's what was happening before. The feature fixes it. It's not about reassigning units that are still automated; It's about giving new assignments to units whose automation has already *ended*, because otherwise their MP would go to waste. Removing the feature would hurt playability because not having this feature basically forces players to waste turns. Civ V does something analogous (although they skip the second button if there aren't any MP left after the automated move, which in turn forces them to use IMO a more confusing label for the first button).

**Comment by kklasmeier** [comment] 2021-11-16 03:26
If I have 10 workers all automated, i would expect those workers to automatically do there work. If a worker has 1 MP left, then it should make use of it if it can, but not request a user to take manual action. I rather lose the MPs than have to take manual action. It contradicts the purpose of automating a worker if manual intervention is needed each turn. Furthermore, there is no way to tell which worker(s) have MP left so it makes it more complicated to try to figure that out.

**Comment by will-ca** [comment] 2021-11-16 05:37
@kklasmeier Just click the next turn button that shows up immediately after if you don't have anything that needs attention 🙄.

Also, the situation you mentioned doesn't even apply. Workers that are still automated shouldn't be asking for manual action. It's only when automated actions *end* that MP is at risk of being wasted.

If a worker has (1) MP left and (2) no outstanding orders (including active automation), then I believe the button will show "Next Unit" instead of "Next Turn". (Correct me if I'm wrong SomeTroglodyte.) If the button says "Next Turn" instead of "Next Unit", then that means there's nothing that needs your attention and you can just click it again.

**Comment by alextfish** [comment] 2021-11-23 10:15
Yeah, I was delighted to see this improvement go in. At last I don't have to carefully monitor my Worker movement instructions and order them to go a step or two before where I told them! At last I can give units instructions the turn that their long multi-turn journeys finish. And it's a great way for units on long journeys to notify me "wait, there's an enemy here, abort abort" as well. This was a much needed feature that's a great improvement to the game now it's in. 

And sure, it slows the ending turn process down by 2-3 seconds on Android. It's definitely worth it.

**Comment by yairm210** [comment] 2021-11-23 13:10
I'm closing this as "not a problem"

**Closed by yairm210** 2021-11-23 13:10 UTC
Labels: bug
