### ISSUE TITLE
Unciv not working in Raspberry Pi 3B+ (Linux armhf)

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#4943] opened 2021-08-22 04:52 UTC
Hi! I tried to run Unciv in Raspberry Pi and got the following errors.
```
~$ java -jar Unciv.jar
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Packing textures - 349ms
Could not initialize Discord
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'libgdxarm.so' for target: Linux, 32-bit
        at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:126)
        at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:31)
        at com.badlogic.gdx.backends.lwjgl.LwjglNativesLoader.load(LwjglNativesLoader.java:46)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:83)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:71)
        at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:67)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for extraction: libgdxarm.so
        at com.badlogic.gdx.utils.SharedLibraryLoader.readFile(SharedLibraryLoader.java:134)
        at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:290)
        at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:122)
        ... 5 more
```
Note that Raspberry Pi comes pre-installed with Java 11. I tried to manually install java8-jre, setting it as default and run Unciv, but got same kind of error. I tried using Windows 32 bit jar. It also failed.

**Comment by touhidurrr** [comment] 2021-08-22 05:15
https://github.com/libgdx/libgdx/wiki/Dependency-management-with-Gradle#freetypefont-gradle

In the error it shows `Linux 32 bit` but the kernel type for raspberry pi armhf is actually `armv7a` or `kernelv7a`. dunno if that will help.

**Comment by yairm210** [comment] 2021-08-22 05:41
Since the issue you referenced was closed, LibGDX 1.10.0 was released, which adds support for ARM, as per https://libgdx.com/news/2021/04/gdx-1-10
So this should be doable, but what with me not having a pi device, it's hard for me to tell what would and would not work
Could you try and add the armeabi natives and see if that works?
I see that the Discord error from #4151 does not seem to affect you, so that's at least one problem solved

**Comment by touhidurrr** [comment] 2021-08-22 05:45
``

> Since the issue you referenced was closed, LibGDX 1.10.0 was released, which adds support for ARM, as per https://libgdx.com/news/2021/04/gdx-1-10
> So this should be doable, but what with me not having a pi device, it's hard for me to tell what would and would not work
> Could you try and add the armeabi natives and see if that works?
> I see that the Discord error from #4151 does not seem to affect you, so that's at least one problem solved

I am not an actual Android developer. Just tried to stackoverflow the error.

**Comment by yairm210** [comment] 2021-08-22 05:58
K, this is a good enough lead to start with :)

**Comment by xlenstra** [comment] 2021-08-22 12:41
Yairm, if you want to test things out yourself, I have a pi 2b lying around somewhere. If you want to, I can set it up that you can SSH into it and try things yourself

**Comment by touhidurrr** [comment] 2021-08-22 12:45
I can give VNC veiwer access if you want. Just install VNC veiwer and i will give you credentials to log into my Pi 3B+ in Discord.

**Comment by yairm210** [comment] 2021-08-22 14:39
@xlenstra it sounds like we just need to add natives-armeabi-v7a versions of the gdx dependencies in build.gradle, subsection "desktop"
And see if it works
If yes, then great
If not, then we'll see what's next
But that's definitely the first step

**Comment by yairm210** [comment] 2021-08-22 19:49
Hm, how odd
All [documentation](https://github.com/libgdx/libgdx/wiki/Dependency-management-with-Gradle#guide-to-buildgradle) shows that this config should work, no extra steps are needed for the *desktop jar* file to work.
Even generated a new project with the [project generator](https://libgdx.com/dev/project-generation/) to check if I missed anything - same.
And libgdxarm.so IS in the .jar file - at least as I have it. Can you unpack yours and check?

**Comment by xlenstra** [comment] 2021-08-22 20:27
`libgdxarm.so` appears to be there when I unpack the Linux desktop version.
I've tried to run Unciv on my pi, but got the stack trace below.
Probably a 32 bit/64 bit problem on my end.

```
pi@tau:~/Documents/Unciv 3.16.6 $ java -jar Unciv.jar
Packing textures - 184ms
[LwjglApplication] Couldn't initialize audio, disabling audio
java.lang.UnsatisfiedLinkError: /tmp/libgdxpi/e06d3531/liblwjgl.so: /tmp/libgdxpi/e06d3531/liblwjgl.so: cannot open shared object file: No such file or directory (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1837)
        at org.lwjgl.Sys$1.run(Sys.java:70)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
        at org.lwjgl.Sys.loadLibrary(Sys.java:96)
        at org.lwjgl.Sys.<clinit>(Sys.java:117)
        at org.lwjgl.openal.AL.<clinit>(AL.java:59)
        at com.badlogic.gdx.backends.lwjgl.audio.OpenALLwjglAudio.<init>(OpenALLwjglAudio.java:72)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.createAudio(LwjglApplication.java:282)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:90)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:71)
        at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:67)
Exception in thread "LWJGL Application" java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.Sys
        at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(LwjglGraphics.java:643)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:125)
```

**Comment by touhidurrr** [comment] 2021-08-23 01:36
> `libgdxarm.so` appears to be there when I unpack the Linux desktop version.
> I've tried to run Unciv on my personal 4B pi, but got the stack trace below.
> Probably a 32 bit/64 bit problem on my end.

I saw kali linux for pi having both `kernel8.img` and `kernel7l.img` in its `/boot`. So try adding both `natives-armeabi-v7a` and `natives-arm64-v8a` maybe? Since pi is a arm64 hardware but runs on 32 bit.

**Comment by yairm210** [comment] 2021-08-23 08:54
There are no separate 'natives' for desktop
There is just 'desktop', which contains all the natives
Which is already there

**Comment by asda488** [comment] 2021-11-01 12:43
I'm backing from trawling through the internet, and it looks like the problem is with `GDX`, but since you are upgrading to `LWJGL 3` they seem to have fixed binaries for `LWJGL` and `OpenAL` for `LWJGL 3` on ARM devices, so I'll rebuild and/or test the prebuilt `.jar` after you merge/after you release. Hopefully should fix this and #5022. :crossed_fingers:

**Comment by asda488** [comment] 2021-11-03 18:11
Fixed for `aarch64/arm64` building `.jar` file without Android Studio and with JDK11, building commit ff389e0. Should also work on `armhf` as they are the same arch, just different bit, unless something hasn't been ported across, but that is unlikely, I think we would just need a confirmation from touhidurrr to close it, hopefully it works :-). (As above, most probably the upgrade to `LWJGL 3` that fixed it.)

**Comment by touhidurrr** [comment] 2021-11-04 19:24
> Fixed for `aarch64/arm64` building `.jar` file without Android Studio and with JDK11, building commit [25cad3a](https://github.com/yairm210/Unciv/commit/25cad3aef2e3fb38a2088840cf7c768021cd2fb8). Should also work on `armhf` as they are the same arch, just different bit, unless something hasn't been ported across, but that is unlikely, I think we would just need a confirmation from touhidurrr to close this issue, hopefully it works :-). (As above, most probably the upgrade to `LWJGL 3` that fixed it.)

Ok, so does the latest release has this fix? Ok I will start testing now.

**Comment by asda488** [comment] 2021-11-05 09:09
I have the `.jar` I built myself [here](https://drive.google.com/file/d/1jsNs-YE4H1lk9V6ikiBa8F2PYrdH-atS/view?usp=sharing), if you really wanted to you could probably test it before next release, up to you.

**Comment by touhidurrr** [comment] 2021-11-09 18:07
@asda488 @yairm210 yes the Game is confirmed to be working on Raspberry Pi. The commands `java -jar Unciv.jar` works fine. I have tested Mods too. Both `RekMOD` and `5Hex Tileset` is working fine. And yes I am using an `armhf` based OS.

**Comment by asda488** [comment] 2021-11-10 10:10
I'd close it then.

**Comment by yairm210** [comment] 2021-11-10 19:58
Awesome! :)

**Closed by yairm210** 2021-11-10 19:58 UTC
