### ISSUE TITLE
Can't run the game in Mac OS with M1 CPU

### ISSUE THREAD

**Issue by adatan** [yairm210/Unciv#6609] opened 2022-04-25 19:38 UTC
**Platform**
Mac OS, Darwin Kernel Version 21.3.0, AArch64 (Apple Silicon (M1))

**Version**
4.0.9 compiled by myself and from github releases

**Describe the bug**
I just can't run the game:(

**To Reproduce**
1. Get Unciv.jar
2. Download liblwjgl.dylib and put it in folder with game (my first error was missed liblwjgl.dylib)
3. Run `java -XstartOnFirstThread -Djava.awt.headless=true -jar Unciv.jar`

**Expected behavior**
The game just needs to start

**Screenshots**
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/50762345/165160502-c26d64cd-da95-4b6a-af48-ddf1396c9538.png">

**Additional context**
I tried to run the game with different versions of java and even with Temurin, as a result I have the same stdout + stderr

**Comment by xlenstra** [comment] 2022-04-25 19:40
Does this help with your problem?
https://github.com/yairm210/Unciv/wiki/Installing-on-macOS

**Comment by adatan** [comment] 2022-04-25 19:43
> Does this help with your problem? https://github.com/yairm210/Unciv/wiki/Installing-on-macOS

definitely not

P.S. I didn't try itch launcher, but I suppose I'll get amd64 arch version of game

**Comment by adatan** [comment] 2022-04-25 20:05
It's an issue with libGDX. Current version doesn't support M1 yet. We'd need to use the beta version or wait for next release (1.11.0)

Big thanks to itanasi (spellman23#8022) from Unciv discord

**Comment by touhidurrr** [comment] 2022-04-25 20:10
Just keeping the Issue updated with Discussions at Github.
From my personal research **libGDX** uses underlying library **LWGJL** so a failure at invoking a function from **LWGJL** means that the problem is on **libGDX** itself.

Apparently @itanasi tried to ask out in **libGDX** discord server and found out that **libGDX** doesn’t support Apple M1 devices yet. However the support is on the current development snapshot version **1.10.1-SNAPSHOT** and should be fixed at the next stable release of **libGDX**.

@adatan tried compiling Unciv from source with `libGDX 1.10.1-SNAPSHOT` and this solved the issue.

**Comment by touhidurrr** [comment] 2022-04-25 20:10
Also @adatan you shouldn’t have closed the issue yet. But after it is fixed in the official Unciv release that fixes this!! Maybe someone reopen it again?

**Comment by touhidurrr** [comment] 2022-05-12 11:05
Test Reply from Email. I wanted to see what wpuld happen if I try to
reply from email. XD

**Comment by touhidurrr** [comment] 2022-05-12 11:06
Wow, this looks cool.

**Closed** 2022-05-13 19:12 UTC
Labels: bug

**Comment by MRigal** [comment] 2022-09-19 20:22
@adatan does it work for you? I still have problems to run it on Monterrey/M1, see #7826
