### ISSUE TITLE
Europe example map

### ISSUE THREAD

**Issue by Lamlash** [yairm210/Unciv#3961] opened 2021-05-18 14:01 UTC
1. Go to 'map type - custom' 
2. Click on 'Europe Example map
3. See error
' Resource Gold does not exist in ruleset'

Also, 
1. Go to 'map type - custom'
2. Click on 'Large Africa txt'
3. See error - 'The game crashes'

**Comment by SomeTroglodyte** [comment] 2021-05-18 21:50
"Europe Example map" (a) is from mod "Unciv Europe Map Example" and "Large Africa txt" (b) from "Great Community Maps".

On selecting (b) the game (always current - you omit your game's version) will not crash but display an appropriate error message and continue.

So, yes, (a) needs an update and (b) is actually broken because is is not a map at all but human readable instructions on how to create the intended map - out of place in a repository marked as "unciv-mod". Neither are a problem of _this_ repository.

**Comment by SomeTroglodyte** [comment] 2021-05-18 22:17
[yairm210/Unciv-Europe-Map-Example/#1](https://github.com/yairm210/Unciv-Europe-Map-Example/pull/1)
[ArchDuque-Pancake/Great-Community-Maps/#4](https://github.com/ArchDuque-Pancake/Great-Community-Maps/pull/4)

**Comment by yairm210** [comment] 2021-05-19 07:20
The crash had been fixed in recent versions.
The gold resource is 'working as intended' in the app level.

**Closed by yairm210** 2021-05-19 07:20 UTC
Labels: bug

**Comment by Lamlash** [comment] 2021-05-25 13:41
> The crash had been fixed in recent versions.
> The gold resource is 'working as intended' in the app level.

**Comment by Lamlash** [comment] 2021-05-25 13:41
Thank you!!
