### ISSUE TITLE
Unit selected for move loses moveability after a map zoom

### ISSUE THREAD

**Issue by HeavyMetalFFT** [yairm210/Unciv#891] opened 2019-06-21 02:42 UTC
To reproduce:
1. Select a unit to move
2. Pinch-zoom the map view
3. Tap a destination hex as if to prepare for move confirmation
4. Note that the hex is selected, but no move confirmation icon is shown.  Note also that the unit still appears as if selected for move with the rotating outline.  

Workaround: Re-tap the unit to reselect, but this time do not pinch zoom.  Move as normal.

**Comment by yairm210** [comment] 2019-06-24 18:46
The reason the unit is deselected while zooming is that while zooming, you're actually touching tiles, which could move your unit unintentionally. So that's a feature, not a bug.
I tried to have the unit 'reselect' after zoom, so you can keep moving it &c, but it isn't working =(

**Comment by naivekook** [comment] 2019-12-19 12:25
Hi everybody!
@yairm210 But when you just move the map it works properly, may be the issue in 2 finger recognition?
as a workaround we can remove focus from unit after zoom in/out to to avoid misunderstanding

**Closed** 2019-12-21 17:35 UTC
