### ISSUE TITLE
Upgrade bug

### ISSUE THREAD

**Issue by Gettergg** [yairm210/Unciv#4952] opened 2021-08-22 15:06 UTC
https://user-images.githubusercontent.com/89348826/130360066-c3c38fc3-25a9-417a-8ab6-f040678ddf87.mp4

**Comment by AdityaMH** [comment] 2021-08-22 15:14
No bug description?

**Comment by xlenstra** [comment] 2021-08-22 15:54
The problem is a crash after upgrading a unit? Which version are you on? This is most likely fixed in 3.16.6

**Comment by logicminimal** [comment] 2021-08-22 16:41
> The problem is a crash after upgrading a unit? Which version are you on? This is most likely fixed in 3.16.6

seems like it is the problem i has

**Comment by yairm210** [comment] 2021-08-23 18:53
Fixed in latest version

**Closed by yairm210** 2021-08-23 18:53 UTC
Labels: bug
