### ISSUE TITLE
Waiting for rome

### ISSUE THREAD

**Issue by Giech91** [yairm210/Unciv#7380] opened 2022-07-05 19:00 UTC
Android phone

**Version**
4.1.15 build 733 

**Describe the bug**
Every time I've moved all my troops and workers I hit the button for next turn. This turn starts loading. I already see the notifications about the happenings like a city expanding at the right side of my screen. But at the top right it still shows "waiting for rome".
I can click every city to see what it is working on. But I can't change anything neither can I move any troop or worker.
![UnCiv_2022-07-05-20-56-59](https://user-images.githubusercontent.com/108759643/177396714-58f1e2a2-2012-4ce2-a041-7b82701056f9.jpg)

The only solution I got so for is to shut down the game completely and restart. This is very annoying. Especially since it worked fine before. Don't know what changed.

![UnCiv_2022-07-05-21-01-36](https://user-images.githubusercontent.com/108759643/177397558-417340fd-86d9-4968-b39a-449cfddaebd3.jpg)

**To Reproduce**

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by alexban011** [comment] 2022-07-06 12:32
> The only solution I got so for is to shut down the game completely and restart. 

You can just leave the game and rejoin. Or even better: use the button next to the next turn button to load the save again. It should be easier than to keep leaving the game

**Comment by letstalkaboutdune** [comment] 2022-07-07 18:35
I'm seeing the same issue, although it only happens if I'm the only player. This happens either if the other players resign or if I made a single-player game as a multiplayer game for ease of playing on other devices. 

Reloading the game does allow the next turn to be played. Here are two save files for reference. One is a straight save, the second has been edited to remove the "IsOnlineMultiplayer=true" tag from the save. This makes the issue go away since it interprets the save as single-player.

[Russia - 5 turns.txt](https://github.com/yairm210/Unciv/files/9066419/Russia.-.5.turns.txt)
[Russia - 5 turns_single.txt](https://github.com/yairm210/Unciv/files/9066420/Russia.-.5.turns_single.txt)

**Comment by daniel-nth** [comment] 2022-07-07 19:02
I have the same problem. Multiplayer game with two friends (v4.1.16 build 734). We started the game a couple of weeks ago on an old version. Huns, Germany, Maya.
It's the Huns' turn. When they finish their turn, it says for them it's Germany's turn. For Germany and Maya it still says it's the Huns'. In the multiplayer menu it says it's Germany's turn for everyone, but even when restarting the game, Germany and Maya still wait for the Huns. When the Huns restart the game, they can do their turn again.

**Comment by alexban011** [comment] 2022-07-07 19:26
@Azzurite could you take a look at this? I suspect the save game compatability to be the cause but maybe thats just a coincidence

**Comment by Akadelvo** [comment] 2022-07-14 18:01
Hm, are there no information which we can provide to you to get an idea how to resolve it?

**Comment by Akadelvo** [comment] 2022-07-14 18:48
Well, seems a bit strange.
Tested so far:
Different program locations (c:\, %appdatalocal%) to verifiy valid permission
Set permission of unciv folder to everyone = full access
4.1.18 - 4.1.15 same behaviour
Tested with Windows x64

Any other ideas what should/can i check?

**Comment by Akadelvo** [comment] 2022-07-14 19:07
keep going on testing and it points out, that maybe the interessting change would made in the past.
4.1.7. works
4.1.8. works
4.1.9 bug occours
4.1.15 bug occours
4.1.16 bug occours
4.1.17 bug occours
4.1.17.1 bug occours
4.1.18 bug occours

Maybe that helps.

**Comment by Giech91** [comment] 2022-10-11 07:50
I believe so. That is what the sign next to "waiting for rome" means right?
But, as far as I know, there are no realy players playing along.
I tried to play with my friend, but this failed. This is my first game.

Op di 5 jul. 2022 22:05 schreef alexban011 ***@***.***>:

**Comment by yairm210** [comment] 2022-12-07 19:13
Closing for irreproducibility
Chances are this was solved in the intervening versions

**Comment by alexban011** [comment] 2022-12-15 16:26
> Chances are this was solved in the intervening versions

It isn't. I also have this issue but have no clue how to debug it

**Comment by daniel-nth** [comment] 2022-12-15 20:02
For the game I mentioned [above](https://github.com/yairm210/Unciv/issues/7380#issuecomment-1178087799) the problem was fixed with a later update.

**Comment by Akadelvo** [comment] 2023-01-28 11:44
> > Chances are this was solved in the intervening versions
> 
> It isn't. I also encounter this issue but have no clue how to debug it

I rechecked my comment from 14.06.2022 and recognized that i have to correct it.
Currently it seems, that 4.1.8 and 4.1.9 are working and multiplayer works like expected.
But 4.1.10 show the initial described issue. 
I tested the windows64 versions.

Maybe these hints can help you to get clue how to debug.

Greetings, Akadelvo

**Comment by alexban011** [comment] 2023-01-28 15:10
It's working for me now. I think it has been fixed recently. Try using 4.4.6 @Akadelvo

**Comment by Akadelvo** [comment] 2023-01-28 15:33
Unfortunately not. Tried a fresh downloaded copy of 4.4.6 Win64, but same for me like before =/ @alexban011

**Comment by alexban011** [comment] 2023-01-28 15:48
What server are you using? Dropbox, uncivserver.xyz or something else?

**Comment by Akadelvo** [comment] 2023-01-28 16:17
Using the default setting with uncivserver.xyz

**Comment by Akadelvo** [comment] 2023-01-29 10:39
Short Info: 
Surrendering also does not working. If i'm clicking the button, dialog "Waiting ..." appears, but nothing happens and i have to kill Unciv App.

Maybe also helpfull for debugging: There are two workarounds to continue the game. 
a) Hit the multiplayer button and reload game manually
b) leave the game and reload it manually

So for me it seems, unciv does not trigger the automatically refresh/redownload the current state from server. 
-----------------------------
Are there any logs i can provide you to clarify that dust?

**Closed** 2023-05-11 12:50 UTC
Labels: bug
