### ISSUE TITLE
Feature request: Start game screen enhancements

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#9492] opened 2023-05-31 13:32 UTC
Items under "Advanced settings" often are repeated in "Extension mods". This is confusing and redundant. Items under the latter should be de-duplicated.

Further, the name "Advanced settings" might not be the best description for the contents. Something along the line of "Map enhancements" might be a better description of this menu field.

**Comment by hackedpassword** [comment] 2023-05-31 13:39
I restarted a game and what I requested above is already implemented? Just minutes previous the request was valid. No idea, and the correct behavior repeats. Upgrading to 4.6.16 and we'll go from there.

Since this req got opened any way, could someone comment if something was changed in a recent update that addressed this (maybe this will help regain sanity!)? o_O

**Comment by yairm210** [comment] 2023-05-31 15:44
Nothing related to this has ever been duplicated, I'm not sure what this was caused by... even loading modsis never done in a way where they can repeat, absolutely no idea
And no way to recreate this either :/ so I'm closing as 'currently unworkable', if you find out anything else we can reopen

**Closed by yairm210** 2023-05-31 15:44 UTC
Labels: feature
