### ISSUE TITLE
MOD Leader Mission 无法打开

### ISSUE THREAD

**Issue by Hrin3** [yairm210/Unciv#9468] opened 2023-05-28 02:37 UTC
**Platform:** Desktop
**Version:** 4.6.14-patch1 (Build 871)
**Rulesets:** [Civ V - Gods & Kings, Leader Mission, Civ V - Vanilla, 5Hex Tileset]
**Last Screen:** `com.unciv.ui.screens.newgamescreen.NewGameScreen`

--------------------------------

OS: Windows 10
Java: Oracle Corporation 25.232-b09
	Max Memory: 910 MB

--------------------------------

**Message:**
```
java.lang.RuntimeException: Actor: TranslatedSelectBox
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.badlogic.gdx.scenes.scene2d.utils.Selection.fireChangeEvent(Selection.java:228)
	at com.badlogic.gdx.scenes.scene2d.ui.SelectBox$1.fireChangeEvent(SelectBox.java:71)
	at com.badlogic.gdx.scenes.scene2d.utils.Selection.choose(Selection.java:53)
	at com.badlogic.gdx.scenes.scene2d.utils.ArraySelection.choose(ArraySelection.java:24)
	at com.badlogic.gdx.scenes.scene2d.ui.SelectBox$SelectBoxScrollPane$1.clicked(SelectBox.java:448)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:78)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:78)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:78)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:378)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:80)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: mods/Leader Mission/District鈥擲tudenicaMonastery.png
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:190)
	at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:101)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:122)
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.load(TextureAtlas.java:87)
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:80)
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:76)
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:71)
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:61)
	at com.unciv.ui.images.ImageGetter.loadModAtlases(ImageGetter.kt:105)
	at com.unciv.ui.images.ImageGetter.setNewRuleset(ImageGetter.kt:81)
	at com.unciv.ui.screens.newgamescreen.GameOptionsTable.reloadRuleset(GameOptionsTable.kt:453)
	at com.unciv.ui.screens.newgamescreen.GameOptionsTable.onChooseMod(GameOptionsTable.kt:466)
	at com.unciv.ui.screens.newgamescreen.GameOptionsTable.access$onChooseMod(GameOptionsTable.kt:39)
	at com.unciv.ui.screens.newgamescreen.GameOptionsTable$addBaseRulesetSelectBox$1.invoke(GameOptionsTable.kt:383)
	at com.unciv.ui.screens.newgamescreen.GameOptionsTable$addBaseRulesetSelectBox$1.invoke(GameOptionsTable.kt:365)
	at com.unciv.ui.screens.newgamescreen.GameOptionsTable$addSelectBox$1.invoke(GameOptionsTable.kt:349)
	at com.unciv.ui.screens.newgamescreen.GameOptionsTable$addSelectBox$1.invoke(GameOptionsTable.kt:348)
	at com.unciv.ui.components.extensions.OnChangeListener.changed(Scene2dExtensions.kt:341)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
	... 20 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: mods\Leader Mission\District鈥擲tudenicaMonastery.png (Local)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:142)
	at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:228)
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:187)
	... 39 more

```

**Comment by Jiangeshi** [comment] 2023-05-28 04:04
I'm very sorry, but Leader Mission mod currently does not support the desktop version. I will focus on resolving this issue.

**Comment by yairm210** [comment] 2023-05-28 05:38
It looks like the atlas doesn't match the packed image...? So just need to delete both of them and run on Desktop to rebuild them

**Comment by Alvin201777** [comment] 2023-05-29 11:55
Leader Mission failed at the start.

**Comment by Jiangeshi** [comment] 2023-05-29 13:51
After a day of hard work, it has finally been resolved that LM mod can now play on the desktop version

**Comment by HydrolienF** [comment] 2023-05-31 12:02
It is caused by Java 1.8 using OS encoding. It may be fix in libgdx https://github.com/libgdx/libgdx/issues/7155

To fix it in Unciv, you can add `-Dfile.encoding=UTF8` for Unciv-Windows64.zip release, but it migth break other mod that where providing OS specific file.
Else you can update Java version provided in Unciv-Windows64.zip to Java 18 (or more).

Anyway it won't fix it for people that launch from Unciv.jar.

**Comment by yairm210** [comment] 2023-08-02 19:48
We forgot to close this way back when, but it's my understanding that the problem was resolved on the mod's end
If that is incorrect and there is still work to do on our end, please notify me

**Closed by yairm210** 2023-08-02 19:48 UTC
Labels: bug
