### ISSUE TITLE
Problem to run on OSX Catalina

### ISSUE THREAD

**Issue by MRigal** [yairm210/Unciv#2551] opened 2020-04-30 14:05 UTC
**Describe the bug**
Running `java -jar Unciv.jar` as described crashes due to missing/mislinked libgdx

**To Reproduce**
1. Install java bia `brew install homebrew/cask/java`
2. Download Unciv.jar
3. Run `java -jar Unciv.jar`
4. See error `Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'libgdx64.dylib' for target: Mac OS X, 64-bit`

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**
I thought the jar could be used also this way on Mac OSX. I haven't tried yet to compile it.

**Comment by yairm210** [comment] 2020-04-30 20:39
From what I found on the internets, this could be a problem with OpenJDK 11.0.4 if you have it?
https://github.com/AdoptOpenJDK/openjdk-build/issues/1211

**Comment by yairm210** [comment] 2020-04-30 20:40
Sorry, more to the point: 
https://www.bountysource.com/issues/86517344-i-can-t-run-my-application

**Comment by MRigal** [comment] 2020-04-30 22:09
Thanks @yairm210 !
I also think this is related to osx Catalina CS OpenJDK... I have openjdk-14.0.1.jdk what a pity if this old problem is still going on there.. :-/
Thanks for your help!

**Comment by MRigal** [comment] 2020-04-30 22:29
I uninstalled it and run `brew install java11` to get 11.0.7, which should work, and I still get the same problems... Not related with Unciv, but others may encounter these also

**Comment by Go-rom** [comment] 2020-07-21 07:38
Hello,

same issue here with Mac OS 10.13.6 and JRE 14.0.2 (installed with the pkg provided by Oracle)

**Comment by JenniferJohnson89** [comment] 2020-08-24 14:39
I noticed that there is a similar problem at https://github.com/libgdx/libgdx. Perhaps we can refer to [this issue](https://github.com/libgdx/libgdx/issues/5882) or [this](https://github.com/libgdx/libgdx/issues/2198) to find more context about the bug (e.g. the Java version, or MacOS version, or their steps to reproduce?).

**Comment by yairm210** [comment] 2021-01-07 21:45
Since May, the problem was fixed in OpenJDK, and so it should work now :)

**Closed by yairm210** 2021-01-07 21:45 UTC
Labels: bug

**Comment by MRigal** [comment] 2021-01-08 12:17
I can confirm this @yairm210 !

Also on OSX 11 Big Sur, with OpenJDK 11.0.9, it works perfectly!
