### ISSUE TITLE
Error Game crash

### ISSUE THREAD

**Issue by EvilCalifex** [yairm210/Unciv#9448] opened 2023-05-24 11:44 UTC
**Platform:** Android
**Version:** 4.6.13 (Build 869)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: moto g(8)
API Level: 30

--------------------------------
![Screenshot_20230524-054359](https://github.com/yairm210/Unciv/assets/134506560/b2feda6c-a3d5-4e8f-8074-3a701f040753)

**Comment by yairm210** [comment] 2023-05-24 12:01
Sounds like #9429 but we can't know without having the entire error text

**Comment by yairm210** [comment] 2023-05-28 05:42
Since no more info is forthcoming, I'm assuming this is a duplicate of #9429

**Closed by yairm210** 2023-05-28 05:42 UTC
Labels: bug
