### ISSUE TITLE
Prevent people from joining games with old versions 

### ISSUE THREAD

**Issue by alexban011** [yairm210/Unciv#7248] opened 2022-06-21 13:03 UTC
I think we should add the game version used to create the game with in gameInfo and gameInfoPreview and prevent people from joining games using an older version

And then display a simple message like "You need to update the game to x.x.x in order to play in this game"

There isn't any reason you'd want to use an older version

**Comment by alexban011** [comment] 2022-06-21 13:41
> This will cause more problems than it solves.

Like what? Not having this causes problems

**Comment by touhidurrr** [comment] 2022-06-21 13:57
> Like what? Not having this causes problems and forward compatability is probably impossible/unfeasable to do

The problem is for Unciv even if you see that you do not have the latest Unciv version popup and want to update Unciv you can't. Google Play doesn’t roll out 100%, And only a tiny bit of players actually uses Github Releases.

So, after implementing this A portion of players be it 10% would be unable to make moves. In a 3/4 player game that would always cause problems cause GP Let's you update not downgrade.

Do 100% release in GP first if you want to implement this. Else this is not for Unciv.

**Comment by touhidurrr** [comment] 2022-06-21 13:59
In other games the rollout in Google Play 100% first before telling player to update the game @alexban011
As you said that other games uses this in Discord.

**Comment by touhidurrr** [comment] 2022-06-21 14:06
> lol

The real problem is partial rollout. And users complain every time because they see their game break and can do nothing about it. Preventing people from joining game doesn’t solve this problem just mask it.

It's nonsense.

**Comment by touhidurrr** [comment] 2022-06-21 14:09
If you want to do anything about it then learn to flag Pull Requests that might cause game breaking change in Multiplayer and do 100% rollout when such a Pull Request is merged. Otherwise, this is not a solution.

**Comment by BramvdnHeuvel** [comment] 2022-06-21 15:25
A notice of `old version, proceed at own risk` could already do wonders too.
It seems a bit unnecessary to implement a hard-coded access denial purely for making sure everyone plays the latest version.

Additionally, I'd rather not be hindered to update my server to version `x + 1` because some users want to finish their version `x` game.

**Comment by alexban011** [comment] 2022-06-21 16:11
Then you're gonna send broken saves to the server..

**Comment by alexban011** [comment] 2022-06-21 17:00
>  hindered to update my server 

The server won't need to update. This is done locally, the server doesn't need to know what version of the game the users have

**Closed** 2022-07-01 06:34 UTC
Labels: feature
