### ISSUE TITLE
RAM usage increases turn-on-turn

### ISSUE THREAD

**Issue by xlenstra** [yairm210/Unciv#5919] opened 2022-01-06 20:09 UTC
Short experiment done based on a remark of Ravignir on discord.
After closing + reopening Unciv and loading the save below, Unciv uses 700 MB RAM on my pc.
Clicking next turn ~20 times increases this to 5.5 GB RAM (according to htop), and stays there. 
As I have 47 GB of RAM, I'm fine with such a relatively small amount being used for unciv, but to me it still seems like a lot of RAM for a game without 3D-graphics and such.

[Autosave.txt](https://github.com/yairm210/Unciv/files/7824418/Autosave.txt)

I've run this on Unciv 3.18.11-patch1 (the most recent version I have installed outside of android studio, which is more difficult to track the RAM of via htop), so things might have changed a bit since then

**Comment by yairm210** [comment] 2022-01-06 21:10
I tried multiple times to try and analyze the memory size with the Android debug tool, but it stuck'd Android Studio every time. Fun.

**Comment by yairm210** [comment] 2022-01-06 21:35
I got to around 1.4 GB RAM which is nowhere near as much, but yes, it is steadily climbing
It seems that ~600MB is the amount of memory it needs for a screen, and so on the very first "next turn" it creates another screen and predictably doubles in RAM size to 1.2, but from there I 'next turn'ed 5 times and only got to 1.4, so it seems there is a slight memory leak, but only around 40MB per next turn.
Still shouldn't happen but it's not as bad as 5GB RAM

**Comment by yairm210** [comment] 2022-01-06 21:38
I will note that this game uses wraparound, which by itself causes all maps to be generated *3 with the associated RAM cost.
That's why we lock it behind an "options" setting. So the initial RAM isn't that surprising either.
I would like to know what the memory is actually allocated to though.

**Comment by GGGuenni** [comment] 2022-01-06 22:31
One thing I was always wondering when implementing world wrap was could the ram usage be reduced by sort of "caching" the images? I think every tile and every image per tile is a new image that needs ram allocated (dunno if that's true). Could we render each image multiple times with one libgdx actor instead of each one independently? I remember trying something like this but failing miserably

**Comment by yairm210** [comment] 2022-01-06 22:37
There's a difference between the actors and the textures.
If we display the same image multiple times, we only save the pixel data - the texture - once, and use that everywhere (see: ImageGetter)
Each location will need its own Image actor so the game knows where to render it, z-indexes, rotation/tinting/scaling, tabling, etc

**Comment by yairm210** [comment] 2022-01-06 22:38
Otherwise even a small map would lead to memory errors
I know this because this is how the game used to work and it did 😅

**Comment by yairm210** [comment] 2022-02-01 08:26
On my previous computer when I tried to memory profile the game the computer flat out died.
On my BRAND NEW computer it just got extremely stuck, but this means that we do have information!
![image](https://user-images.githubusercontent.com/8366208/151934855-8f913295-b2b7-40d0-a201-eedd1c0b93ce.png)
![image](https://user-images.githubusercontent.com/8366208/151934936-17d3b169-b144-4f4f-8570-e642d723a7d3.png)
What you're seeing here is "~100MB of allocated memory from Kotlin code, ~1.5GB of memory allocation from Native code", so I'll try and figure out where that's coming from

**Comment by yairm210** [comment] 2022-02-01 08:27
![image](https://user-images.githubusercontent.com/8366208/151935120-c1a56f30-d469-420d-a3b1-6fbe655e2ebc.png)
Pictured: Unciv being so allocation-intensive that even profiling it stretched available memory

**Comment by yairm210** [comment] 2022-02-01 08:57
Apparently I don't know how to read memory allocation graphs :/
The way it seems to work is, Kotlin requests memory from the JRE; JRE requests memory from the OS (native).
When Kotlin allocated memory that the Dalvik/JRE doesn't have, then you'll see a native memory allocation.

Findings:
![image](https://user-images.githubusercontent.com/8366208/151938327-9f5c52de-18d6-44b6-b3ca-cf99f13a400f.png)

A. guaranteeUnitPromotions is generating 100MB or requested memory?!?!
![image](https://user-images.githubusercontent.com/8366208/151938501-560dccbc-d92e-4a7e-825e-a4237d654d53.png)

B. getCivResources generates a lot of memory requests as well, since it builds the entire resource list every time from scratch:
![image](https://user-images.githubusercontent.com/8366208/151938699-e6aec0cb-cc86-4cf2-ad8a-4f39b79b5163.png)
![image](https://user-images.githubusercontent.com/8366208/151938750-af60df40-0d47-4821-881f-43fc4324d098.png)
![image](https://user-images.githubusercontent.com/8366208/151938773-4d2f0e7b-701b-4027-a0be-8e3949670d1a.png)
![image](https://user-images.githubusercontent.com/8366208/151938797-9cef97b6-d6d1-4513-a74e-c8dd73460505.png)

This is because we recently added the civ resources as a possible source for getMatchingUniques, which is called ALL THE TIME.
Conclusion: Civ resources need to be cached.

C. That stupid getUnitMaintenance is getting in our way again!
![image](https://user-images.githubusercontent.com/8366208/151938997-2abc407f-e3b7-4729-a81c-c41e581b73f8.png)

The problem is that it goes over EVERY unit and for each one runs getAllUniques, because we can't just run it once globally since then the conditionals will reject some of them.
Conclusion: We need a version of GetMatchingUniques that returns ALL uniques of a specific uniqueType, REGARDLESS of conditional matching, so we can run that once and then run only the conditional matching per-unit.

**Comment by yairm210** [comment] 2022-02-01 09:56
A. Solved in cf6dacdcbeab790e0ab5a8ca93793cdb2db6324e
B. Solved in #6093 
C. Solved in #6092 

These account for over 50% (60%? 70%?) of profiled memory usage, so once they're submitted we can run the profiling again (half the time it gets the Android Studio permanently stuck so it's not easily micro-usable like the CPU profiling is)

**Comment by yairm210** [comment] 2022-02-01 10:55
Results:
![image](https://user-images.githubusercontent.com/8366208/151954781-373acf9a-68f5-48f4-8726-bd875c0dd43f.png)

Compare to the previous one:

![image](https://user-images.githubusercontent.com/8366208/151938327-9f5c52de-18d6-44b6-b3ca-cf99f13a400f.png)

Great success!

All the pain points (A B C) are now gone, 
We've gone from a baseline of ~800MB to ~300MB
And considering that there's around 100MB of *images*, which is roughly static across all games, that means we've effectively gone from 700 to 200 MB of allocated memory for the specific game data. That's insane. If this scales proportionally, then games that used to take 1.5GB of RAM should now take only 500MB.

I often tell people that in my experience there are 2 main indicators of professional teams - 1. Teams that deal with the results of their own failures (a la On Call) and 2. Teams that look at their own data, since even just looking at the data often leads to quick wins that can lead to order-of-magnitude improvements.
Even so, I wasn't expecting a 70% reduction. 
I'm willing to close this as resolved.

**Closed by yairm210** 2022-02-01 10:55 UTC
Labels: bug, Contains Saved Game

**Comment by RasRaimo36** [comment] 2022-05-14 04:31
> ![image](https://user-images.githubusercontent.com/8366208/151935120-c1a56f30-d469-420d-a3b1-6fbe655e2ebc.png) Pictured: Unciv being so allocation-intensive that even profiling it stretched available memory

hacked my konami id hm.
