### ISSUE TITLE
Keyboard controls only work with english layout

### ISSUE THREAD

**Issue by sockybob** [yairm210/Unciv#4430] opened 2021-07-08 19:33 UTC

**Comment by SomeTroglodyte** [comment] 2021-07-12 13:51
I'd say they work as described. They can definitely be operated with french or german layouts, so "only english" isn't strictly true. I don't even know how you would generate an ascii "C" with a cyrillic layout, but the libGdx functions used and their documentation say that's what I'm looking for when a settler is selected to found a city. We're not looking for the fourth key to the right of the left 'shift', where many western layouts have the "C" - which would also be possible. If you can show otherwise I'd be highly interested.

That the chosen letters are not adaptable to language, culture, user preference or the like is by design for the time being and an entirely different matter.

**Comment by sockybob** [comment] 2021-07-12 17:47
> I'd say they work as described. They can definitely be operated with french or german layouts, so "only english" isn't strictly true. I don't even know how you would generate an ascii "C" with a cyrillic layout, but the libGdx functions used and their documentation say that's what I'm looking for when a settler is selected to found a city. We're not looking for the fourth key to the right of the left 'shift', where many western layouts have the "C" - which would also be possible. If you can show otherwise I'd be highly interested.
> 
> That the chosen letters are not adaptable to language, culture, user preference or the like is by design for the time being and an entirely different matter.

I never encounter such weird behaviour in other games. All games i played so far are not dependent of which layout i'm currently switched to, so i assumed that the Unciv gets input from keyboard in a wrong way, like reading letters i typing in and doing certain action if it's equal to some latin letter (like if i were typing in a text field). Imo it's completely wrong approach and should be changed to process keycodes instead. Also i don't quite get what you mean but i will try to answer anyway. When i want to press button with certain latin letter i would press the same button as i were on english layout, so it's the same key with the same keycode, but the very fact that i'm on cyrillic layout makes the game ignore keyboard input until i switch to english. I'm not asking to make the game also understand those cyrillic letters which are similar to the latin ones.

**Comment by yairm210** [comment] 2021-07-12 18:47
Some small experimenting lead to the fact that Input.Keys has a .toString() function and that if you replace line 33 in KeyPressDispatcher with `       if (event == null) '_' else Input.Keys.toString(event.keyCode).first().toLowerCase(),` all single-letter keys work on all layouts, but all non-letter keys (e.g. the esc key) don't, so it still needs some refining.

**Comment by sockybob** [comment] 2021-07-12 19:18
Just whenever you process input from keyboard compare keycode integers instead of comparing strings/chars.

**Comment by yairm210** [comment] 2021-07-12 19:21
Yes, but there needs to be some matching between the characters (as defined e.g. in tileimprovements.json) and the key codes

**Comment by SomeTroglodyte** [comment] 2021-07-13 06:08
> if (event == null) '_' else Input.Keys.toString(event.keyCode).first().toLowerCase(),

The other way round. Translate in the [Char] set operators and just use the keyCode directly in the listener.

**Comment by SomeTroglodyte** [comment] 2021-07-13 06:30
And the tooltips would need to go, they'd be wrong for most non-english users.

How would we get the translators to re-do the 'keyboard' tutorial? Hmmm... Ctrl-Letter would need rethink anyway. What is the norm on Cyrillic to map some equivalent of "Ctrl-X"? By "geographical" position too? Should one then use the ascii in the event to assume Ctrl was held if it's below the Space? Or use Gdx.Input.isKeyPressed and just hope the modifiers haven't been released in the meantime?

Or - implement user-programmable key bindings later, which should also satisfy this.
Feels a little like catering to the backwards people who still refuse to use SI units or ISO dates. Though with keyboards, the obviously intelligent variant isn't used by anybody at all. I might have to by a [Dvorak](https://en.wikipedia.org/wiki/Dvorak_keyboard_layout) keyboard to find out whether they re-mapped the keycodes.

**Comment by sockybob** [comment] 2021-07-13 07:13
> And the tooltips would need to go, they'd be wrong for most non-english users.

I disagree on that. I don't know about how keyboards mapped for other languages in other countries but in my country we usually have both latin and cyrillic letters mapped on keyboard (in a qwerty way), sometimes there's only latin letters and i don't know if cyrillic only keyboards even exists, if they are then it's probably very rare occurence. Pretty sure for most other laungages/countries it's the same.

**Comment by sockybob** [comment] 2021-07-13 09:33
The tooltips can be relied to translators, so they can "translate" them as they see appropriate. So the keycodes can still be used.

**Comment by SomeTroglodyte** [comment] 2021-07-13 10:27
Another option I forgot to mention - have the listener compare both ascii and keycode, and supply enough combinations to satisfy all layouts. Where that knowledge is stored left unanswered for now.

Current base is also not too badly set up to allow full translatability using readable names like - introducing a magic marker just to separate from the outlandish case one would want single-letter words to be translated - `Keyboard.Z = Z` meaning ASCII `Z` if one wishes the function to move with the layout vs. `Keyboard.Z = Keys.Z` meaning keyCode 54 if one wishes it to stay put just down there bottom left, even on a kraut clavier. A "Display" string could be appended with another magic by-convention method - though that would be nicer if I'd finally get multichar tooltips to obey, but they still baffle me.

The latter would be combinable with 'other way round' in successive PR's because both would mainly touch the KeyCharAndCode constructors, not the listener code.

**Comment by SomeTroglodyte** [comment] 2021-07-14 12:12
#### Tester please
@sockybob  - are you able to test debug apk's and/or directly from Android Studio?

[Unciv-debug-keycodes.apk](https://github.com/SomeTroglodyte/Scratchpad/blob/master/Debug%20apk's/Unciv-debug-keycodes.apk) - see [Warning and instructions](https://github.com/SomeTroglodyte/Scratchpad/blob/master/Debug%20apk's/Warning%20and%20instructions.md)
or
[my Keyboard-mapping branch](https://github.com/SomeTroglodyte/Unciv/tree/Keyboard-mapping) - see [Testing another collaborator's work](https://github.com/SomeTroglodyte/Scratchpad/blob/master/Unciv-notes/Working%20in%20the%20IDE%20and%20Contributing.md#testing-another-collaborators-work)

#### Explanation
That thing can 'translate' keys before feeding them into the dispatcher, and many (but not all - e.g. too lazy to switch F1-F12 right away) dispatcher assignments are changed to use that. 'R' becomes 'Key:R' which goes through translation - and since there isn't any it stays "Key:R" which is then interpreted by looking up the key named "R" from java's Input.Keys class, giving keyCode 46. As you suggested - it's now recognized by position not by ASCII letter.

A translation line `Key:R = Key:NUMPAD_DIVIDE` would work, while `Key:R = Key:NUM_LOCK` would not, since the dispatcher still uses a keyTyped listener, not a keyDown listener, so only keys producing a character can be matched.
A translation line `Key:R = R` would work and make the dispatcher react to the ASCII letter as before.
Control-Letter combos go into translation as `Key:Ctrl-X` and are parsed the same, though I allow omitting the `Key:` part.

Demo would be switch to german, run, ESC, "Yes" is now "Ja" and reacts to "J" not "Y" due to a `Key:Y = Key:J` translation.

Nothing done to tooltips yet. Wouldn't be too hard - default to a toString() of the translation but allow appending ",tip" to the translation line and the key translation routine would cache that (it is already caching its results), except - I still can't do predictably positioned multichar tooltips.

Idea: Use invented names by function and require a translation line, even in English. So the `YesNoPopup` could do a `KeyCharAndCode.translate("Yes")` instead of `KeyCharAndCode.translate('y')` and the translation would supply the `Key:Yes = Y` meaning... Or `Key:Civilopedia = Key:F1` or `Key:Fortify = F` or...

#### Reviewers please
- Any comments
- What do you think of the "Functional" key binding way

**Comment by sockybob** [comment] 2021-07-14 17:38
> @sockybob - are you able to test debug apk's and/or directly from Android Studio?

No, i'm sorry. I don't have android studio installed and i have no experience of using it.

**Comment by SomeTroglodyte** [comment] 2021-07-14 18:37
> No i'm sorry

That's OK. I just learned how to get a jar - by **not** looking in Studio's menus for a likely sounding menu entry.

[Unciv-debug-keycodes.jar](https://we.tl/t-A525JKCe5S) was too big to store here, no idea why it's so much more bloated than an apk. Runs under a jre8, not a jre14. Maybe it's just enough so you can tell us whether keys with this behave nicer.

**Comment by sockybob** [comment] 2021-07-14 19:08
Yep, they're working now no matter which layout i use.

**Comment by SomeTroglodyte** [comment] 2021-07-14 19:16
:+1: Glad to hear!

But I'll also have to disappoint you a little - this will take some time, to evaluate future strategy and find the best way. Do we want to follow tinysquishy in localizing keyboard commands at all? Do we want customizable mappings now or the near future? And - how to deal with QWERTZ and AZWERTY and the like. Telling people they should press 'Y' and then it only reacts to 'Z' isn't nice either.

**Comment by sockybob** [comment] 2021-07-14 19:29
Doing some research about how other games handle those issues might help.

**Comment by SomeTroglodyte** [comment] 2021-07-14 19:42
> how other games

And then reading some heated comments on how any respectable game absolutely _requires_ full keyboard binding remap capability from its UI lead me to waaaaay overthink this - and those were complaining about original Civ5! Can't remember where I read that though. During research way back in the first drafts of KeyPressDispatcher.

**Comment by yairm210** [comment] 2021-07-15 11:06
Step one - check by key. That's a PR in of itself.
Maybe future step two - custom keybindings.
To not do - key translations.

**Closed** 2021-07-17 19:26 UTC
Labels: bug
