### ISSUE TITLE
Why a large number of functions of the module fail.

### ISSUE THREAD

**Issue by MGLSIDE** [yairm210/Unciv#5840] opened 2021-12-22 11:17 UTC
The author explains the situation in the latest edition.

**Comment by MGLSIDE** [comment] 2021-12-22 11:24
@yairm210  Author, please give an explanation.

**Comment by xlenstra** [comment] 2021-12-22 15:11
I have no idea what the problem is you are describing. Is it a problem with the game? With modding? What did you do, and what went wrong? Please go in more detail, otherwise we're unable to help at all

**Comment by yairm210** [comment] 2021-12-22 19:24
I'm closing this on principle.
If you can't be bothered to explain what your problem is then I'm definitely not going to to try and guess.
Please be respectful of people's time.

**Closed by yairm210** 2021-12-22 19:24 UTC
