### ISSUE TITLE
Cannot translate some politics strings

### ISSUE THREAD

**Issue by J0anJosep** [yairm210/Unciv#7857] opened 2022-09-25 08:58 UTC
**Version**
master branch, 23 September, commit e2187a268f56376892a9e0ed6a6f74e7284dfd03

**Describe the bug**
These strings cannot be translated:
Politics: text button
Show global politics: text button
Show diagram: text button

**Comment by xlenstra** [comment] 2022-09-25 10:32
Duplicate of #6131

**Closed by xlenstra** 2022-09-25 10:32 UTC
Labels: bug
