### ISSUE TITLE
Game crashes when interacting with anything related to coasts or oceans or mountains or lake tiles in Map Editor

### ISSUE THREAD

**Issue by Handsome-Italian** [yairm210/Unciv#8235] opened 2022-12-26 11:09 UTC
**Platform**
Android, Samsung Galaxy S8

**Version**
Version: 4.3.12 (Build 782)

**Describe the bug**
When making a map in map editor, placing ocean/coast tiles or trying to place any kind of resource on coast tiles causes the game to crash. The same happens on pre-existing and downloaded maps. This happens also when placing Mountains, Lakes, Atolls or other tiles related to Coasts and Oceans.

**To Reproduce**
1. Go to 'Map Editor'
2. Click on 'Edit'
3. Click on 'Terrain'
4. Click on 'Ocean/Coast tiles' (or tiles and resources related to those two/mountain tiles or lakes)
5. Place such tiles on any point in the map
6. See Error

</details>

**Expected behavior**
Normally, the placement of such tiles/resources shouldn't cause the game to crash.

**Additional context**
When making maps before, the game never crashed. I first experienced this roughly 2 days ago, and it's been bothering me since.

**Comment by CrispyXYZ** [comment] 2022-12-29 01:08
This is caused by `TileInfo.removeRoad()`, which is fixed in #8250.

**Comment by Handsome-Italian** [comment] 2022-12-29 09:52
I see. So I just have to update the game now to the new version to prevent this from happening again?

**Comment by CrispyXYZ** [comment] 2022-12-29 10:09
Not now. Just wait for the new version(4.3.14) to be released.

**Closed** 2022-12-29 11:51 UTC
Labels: bug
