### ISSUE TITLE
Coroutines causes Unciv to crash

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#6810] opened 2022-05-14 23:50 UTC
**Platform**
Raspberry Pi OS armhf (32-bit linux arm)
Raspberry Pi OS arm64 (64-bit linux arm)

**Version**
Unciv from [yairm210:master@03579a8](https://github.com/yairm210/Unciv/tree/03579a884deb2e8475cc64c62aa4abd5f4a97b8e) or
Unciv from #6801 but not
Unciv from #6809

**Describe the bug**
As soon as i try to run `java -jar Unciv.jar` with Temurin 11 or 8 it crashes.
Only `Unciv.jar` compiled with the coroutines pr are affected.

**Logs**
```java
~$ java -jar Unciv-03579a8.jar
Packing textures - 634ms
Could not initialize Discord
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
Loading Construction = Construction.atlas
Loading Flags = Flags.atlas
Loading NationIcons = NationIcons.atlas
Loading PolicyIcons = PolicyIcons.atlas
Loading ReligionIcons = ReligionIcons.atlas
Loading Skin = Skin.atlas
Loading Tech = Tech.atlas
Loading UnitPromotionIcons = UnitPromotionIcons.atlas
Loading RekMOD = mods/RekMOD/game.atlas
Loading 5Hex Tileset = mods/5Hex Tileset/game.atlas
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoClassDefFoundError: kotlinx/coroutines/ExecutorsKt
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:172)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:63)
Caused by: java.lang.NoClassDefFoundError: kotlinx/coroutines/ExecutorsKt
	at com.unciv.ui.crashhandling.CrashHandlingThreadKt.<clinit>(CrashHandlingThread.kt:14)
	at com.unciv.UncivGame.create(UncivGame.kt:120)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:366)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	... 1 more
Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.ExecutorsKt
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more
```

**Comment by touhidurrr** [comment] 2022-05-14 23:52
Sorry @Azzurite but early issue. I was interested in testing coroutines, but it crashed.
I am sure this is not because of https://github.com/yairm210/Unciv/pull/6809 because I also tested this `Unciv.jar` from here:
https://github.com/touhidurrr/buildUnciv/releases/tag/1652568251180967824
For releases, check: https://github.com/touhidurrr/buildUnciv/releases

**Comment by SomeTroglodyte** [comment] 2022-05-15 00:54
Disable cache once, build, reenable - please, and tell us whether that helps?

**Comment by SomeTroglodyte** [comment] 2022-05-15 00:58
At least, locally killing the renitent Studio with build/clean, invalidate caches and restart, then wait for sync and then do a rebuild is what I normally do when I see a NoClassDefFoundError. Without second thought, which is why I can't tell you whether I did that locally due to the coroutines stuff or not. I feel like yes I did several times because going back to a branch pre-problem also pollutes cache.

**Comment by touhidurrr** [comment] 2022-05-15 01:12
> Disable cache once, build, reenable - please, and tell us whether that helps?

Same. I have Tested on arm and arm64, both are the same.

**Comment by touhidurrr** [comment] 2022-05-15 01:14
Also dependency management systems have their own way to verify files with hashes if I remember. So, downloading broken files in unlikely.
Same for Github Caches, they check filehashes too.

**Comment by touhidurrr** [comment] 2022-05-15 01:14
Also dependency management systems have their own way to verify files with hashes if I remember. So, downloading broken files in unlikely.
Same for Github Caches, they check filehashes too.

**Comment by yairm210** [comment] 2022-05-15 14:55
@Azzurite I'm going to revert the coroutines commit so it doesn't block our releases and we can reintroduce it once problems are solved, so no rush

**Comment by yairm210** [comment] 2022-05-15 18:16
Removed, so closing

**Closed by yairm210** 2022-05-15 18:16 UTC
Labels: bug

**Comment by SomeTroglodyte** [comment] 2022-05-15 18:20
I can confirm tohidurr's assessment with an assortment of 5 different JRE's.

Really a pity. I have a very fuzzy memory of toying with coroutines to get more CPU's to automate units, and arrived at the conclusion that the runtime environment changes that the coroutine documentation back then required were too demanding, and the whole thing was still marked experimental. Late days of kotlin 1.4 or so. Must be solvable as the thing runs fine in Studio...
