### ISSUE TITLE
"replaces" does not work with Tile Improvements

### ISSUE THREAD

**Issue by Caballero-Arepa** [yairm210/Unciv#7791] opened 2022-09-12 20:27 UTC
"Replaces" from jsons is used a lot for civs to replace certain building/unit with its own.

But when trying to replace an improvement, the game doesn't recognizes it and the unique imp. doesn't replace the desired improvement.

Example of this in "Naciones pa Unciv ES", and maybe if I remember right, in "Latin American Civs" with El Salvador.
![Screenshot_20220912-152343_Firefox.png](https://user-images.githubusercontent.com/78449553/189752274-621f3fcb-1bac-45de-b1e3-52a0ea02133c.png)![Screenshot_20220912-152535_UnCiv.png](https://user-images.githubusercontent.com/78449553/189752292-1af89ced-6227-4dcf-b9b1-203dab2229ce.png)

**Comment by yairm210** [comment] 2022-09-12 20:29
This was never intended, therefore not a bug, but a feature request.

**Comment by zhan313** [comment] 2022-09-13 02:55
Also, can we make it hidden in civilopedia?

**Comment by Caballero-Arepa** [comment] 2022-09-13 03:00
> Also, can we make it hidden in civilopedia? 

What? There is the unique "Will not be displayed on civilopedia" for that.

**Comment by zhan313** [comment] 2022-09-22 05:02
Didn't work, try it

**Comment by Caballero-Arepa** [comment] 2024-03-15 01:49
sad

**Comment by SeventhM** [comment] 2024-03-18 17:31
Closing as #3242. I might look into this soon, though

**Closed by SeventhM** 2024-03-18 17:31 UTC
Labels: feature
