### ISSUE TITLE
Feature request: Worker AI should not improve tiles not within a city's are of use

### ISSUE THREAD

**Issue by The-Talik** [yairm210/Unciv#12293] opened 2024-10-14 18:52 UTC
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

Once cities start expanding territory outside of their 3 tile radius, un-used tiles become part of your empire.  Workers don't distinguish this fact, and spend time upgrading tiles that will never be used by your cities.

### Desired Solution

Worker AI only improves tiles that are within 3 tiles of one of your cities.

### Alternative Approaches

Alternatively, allow assigning a worker to a specific city.  This has the added benefit of a bit more worker control (ie, preventing them from running through a barbarian camp to another city) while still leaving them on automatic mode.

**Comment by yairm210** [comment] 2024-10-14 20:13
I'm pretty sure we already coded this in, can you give an example save?

**Comment by The-Talik** [comment] 2024-10-14 20:41
I'll send it next time it happens.  The particular tile is upgraded now, since I didn't want to have to keep fighting with the AI.
Also, and I'm not sure if this is a good thing or not, but cities will claim tiles more than 3 tiles away before they've claimed all usable tiles.  I could see an argument for this, but it feels like they should claim all workable tiles before unworkable tiles.

**Comment by yairm210** [comment] 2024-10-14 20:44
Was that tile with a resource?

**Comment by The-Talik** [comment] 2024-10-14 20:46
The resource was truffles.  The city claimed it before all usable tiles were claimed, and the worker upgraded it

**Comment by yairm210** [comment] 2024-10-14 21:19
Yes, resources in your borders are provided even when outside of city limits 
If that's the case, closing as "intended behaviour"

**Comment by The-Talik** [comment] 2024-10-14 21:21
Thanks, sorry for the mixup.

**Comment by The-Talik** [comment] 2024-10-14 21:33
Actually, I just got it to happen with a farm on a non-resource.  Attaching save file.
It should be the next unit in queue, but if not, it's the settler just east of the capital Konigsberg.  Clicking Automate on them will start constructing a farm on the tile he's currently on, which is outside of any city's usable land.
[Prussia - 529 turns.zip](https://github.com/user-attachments/files/17369578/Prussia.-.529.turns.zip)

**Comment by yairm210** [comment] 2024-10-15 21:27
Resolved in #e0f3c0ac

**Closed by yairm210** 2024-10-15 21:27 UTC
Labels: feature

**Comment by The-Talik** [comment] 2024-10-16 20:15
Thanks again.  You rock!
