### ISSUE TITLE
Suggestion on the new map editor

### ISSUE THREAD

**Issue by heipizhu4** [yairm210/Unciv#6579] opened 2022-04-20 12:36 UTC
**Is your feature request related to a problem? Please describe.**
1. Players may have no idea to exit the new map editor. I know it's in the view tablet, but someone may not know and they will have a hard time exiting it after they save the file.
2. The 'natural wonder' in the partial tablet looks wierd. Other generation steps say '**Spread** Resources' and '**Create** ancient ruins'. The verb before makes phrases here different from other places, but the 'natural wonder' has been translated somewhere else.
3. Some phrases in the editor are pretty confusing, for example, 'Complete match'. I bet most people (inclduing me) can't undersdand at the first sight.

**Describe the solution you'd like**
1. Add a button to exit in the top-left corner or a button in the save tablet.
2. Change 'Natural wonder' into 'Create natural wonder' or sth. like that.
3. Adding a 'help' tablet might help the newcomers.

**Additional context**
I'd be glad to pull a request myself, but I don't know Kotlin :(
Hope someone will help me.

Edited: Suggestion from other players:
The menu on the right blocks too much of the map, especially in low-resultion mode. They want to have a 'collapse' button.

**Comment by heipizhu4** [comment] 2022-04-21 00:45
Sorry, for late comment. I went to sleep after posting it. 
I didn't notice the fact that it's collapsible. But I think that's why a help tablet is neccessary. You know, not everyone can check out @Sometrogodyte 's video. It's on dropbox so Chinese players can't watch it and more people don't even know there's a video here.

**Comment by AdityaMH** [comment] 2022-04-21 06:17
Add button for collapsing.
pretty annoying for android. More annoying if using split mode in xiaomi phone.

**Comment by heipizhu4** [comment] 2022-04-21 08:05
Sure, most

> Add button for collapsing menu. pretty annoying for android. More annoying if using split mode in xiaomi phone.

I can't agree more. It's 'challenging' to press the small edge on the phone. I'm using honor.

**Comment by SomeTroglodyte** [comment] 2022-04-25 03:34
As for leaving - it should react to back/ESC just fine, from any tab. A dupe of the quit button on the save tab - why not, if the 

The clip is not an instruction video, just a short demo, and censorship is not my problem. Believe me, crapbox was not my first or second or even third choice.
The "drawer" widget is originally close to the SplitPane one, with identical handle width, and can be dragged just like a SplitPane. The open/close fully on click feature is just added on top for convenience. I had no trouble when I designed that part months ago in hardware tests - on xiaomi hardware btw. The ability to leave it halfway is a bonus compared to the old editor, which used roughly the same screen percentage when open - those widgets still visible do work.

No idea what "split mode in xiaomi" or "honor" means in this context.

'Complete match' & co will change when the tile / ruleset normalization gets done. That was the biggest to-do left. At the moment it uses an existing normalize-tile function to deal with e.g. painting forest onto desert, and it's not optimal. The idea is to have a spectrum from "don't paint anything that conflicts with the existing tile in any way" to "force the change even if you have to remove improvements, features or change the base terrain", so on one end painting forest onto desert would do nothing, on the other end it would change the desert into plains to allow the forest. Wording is also an early compromise because the floodfill feature also uses the same steps to determine boundaries, and the same background test needs different words to be easily understandable in that context.

"but the 'natural wonder' has been translated somewhere else." - probably precisely why I reused the already translated string. Valid suggestion. The "partial" system has regressed anyway over the many merges and the first step no longer does what it should.

Note to self: Is "allow control over strategic resource abundance / check relevance of new dropdown and slider and clarify" in the TO-DO's? (at the moment it can do only minorDepositAmount.default just like the old one)

**Comment by heipizhu4** [comment] 2022-04-25 13:15
That 'split screen' means you can split your phone into two screens so that you can run and use two apps at a time. For example, I can play unciv and comment this issue at the same time. But this mode has resulted in the edge of the menu almost impossible to press. I'd like to give you a screenshot, but my poor phone doesn't allow it in this mode.

**Comment by SomeTroglodyte** [comment] 2022-04-26 10:47
After more testing I thank you for pushing the "handle too hard to hit" thing, it works indeed a _lot_ better on phones by just making it 25f wide instead of 10f. Will need more work - how it does on lower unciv-display-resolutions, is placing a little triangle in there easy or hard, such stuff.

**Closed** 2022-04-27 05:19 UTC
Labels: feature
