### ISSUE TITLE
Feature request: Victory status button 

### ISSUE THREAD

**Issue by Thienanbad** [yairm210/Unciv#7854] opened 2022-09-24 10:17 UTC
While we are playing sometime we need to check other civ status and we use victory status tab to do it so i recommend the Victory status tab should be move to next to overview tab or some where to access easier

**Comment by xlenstra** [comment] 2022-09-24 10:21
Duplicate of #3417

**Closed** 2022-09-24 10:21 UTC
Labels: feature

**Comment by Thienanbad** [comment] 2022-09-24 10:29
#3417 is from 2020 and now the Victory status tab still not access easier

Vào 17:21, Th 7, 24 thg 9, 2022 Xander Lenstra ***@***.***>
đã viết:

**Comment by yairm210** [comment] 2022-09-24 16:45
It doesn't matter from how long ago it is, it doesn't magically not become a duplicate because it's been a while.
