### ISSUE TITLE
UI bug: incorrect handling of unit and worked tile icon opacity

### ISSUE THREAD

**Issue by letstalkaboutdune** [yairm210/Unciv#8669] opened 2023-02-13 16:44 UTC
@vegeta1k95 possibly related to your recent changes?

Happens on version 4.4.14, PC and Android. 

When unit icon opacity is < 100%, the correct behavior is as follows:
- Unit not selected -> display icon with selected opacity
- Unit selected -> display icon with 100% opacity

Currently that is not the case. I play with 50% opacity and this is the behavior:
- Unit not selected -> display icon with selected opacity
- Unit selected -> **_display icon with even less opacity_**

This makes units look inactive when selecting them, instead of looking ready to move. 

Citizen worked tile icons are incorrectly getting less opaque on unit selection as well. This can also be seen in the screenshots below.

Before selected:
![01](https://user-images.githubusercontent.com/56904240/218518663-2e09ee0c-8031-4c77-8bc1-8757bf07451c.png)

After selected:
![02](https://user-images.githubusercontent.com/56904240/218518709-6f8c7d77-8137-4b1b-b984-8e28cccd2d57.png)

**Comment by vegeta1k95** [comment] 2023-02-13 18:00
I think that might be not the bug with opacity, but the fact that white selection highlight sprite is a filled shape, not an outline, so when flag is half-transparent, white selection mixes with flag bg which makes it less visible.
I'll check it.

**Comment by letstalkaboutdune** [comment] 2023-02-13 18:13
It shouldn't matter, because the unit icons should become fully opaque when selected. So anything underneath it will not be visible.

**Comment by vegeta1k95** [comment] 2023-02-13 18:20
The default logic is the following:
1) Unselected unit, has moves - 100% opacity
2) Unselected unit, no moves - 50% opacity
3) Selected unit, has moves - 50% opacity
4) Selected unit, no moves - 50% opacity

Unit should be opaque 100% **if and only if** it has moves.

If you play with default opacity < 100, then it should never be fully opaque, that is indended.

**Comment by vegeta1k95** [comment] 2023-02-13 18:25
Civ 5:
Full moves selected:
![image](https://user-images.githubusercontent.com/32207817/218542914-72fcb382-90eb-4c6b-bea8-cf9b71bc8629.png)
Out of moves selected:
![image](https://user-images.githubusercontent.com/32207817/218542980-f612ac13-5f6f-44bf-9ba1-56edacb9d0c3.png)

**Comment by letstalkaboutdune** [comment] 2023-02-13 18:26
That's with 100% icon opacity, which is the only option in Civ 5. Not relevant for Unciv with adjustable unit icon opacity.

**Comment by vegeta1k95** [comment] 2023-02-13 18:28
Ok, I'll have to branch conditions for opacity into 100/<100. Cannot be unified into one.

**Comment by letstalkaboutdune** [comment] 2023-02-13 18:29
> Ok, I'll have to branch conditions for opacity into 100/<100. Cannot be unified into one.

Thanks.

**Comment by vegeta1k95** [comment] 2023-02-13 18:51
Should be fine now wtih #8670.

50%
![image](https://user-images.githubusercontent.com/32207817/218547291-c4bd094d-d868-4407-a041-f53690c83d6c.png)

100%
![image](https://user-images.githubusercontent.com/32207817/218547324-40062699-47b4-4d03-ab05-3f05107e876a.png)

**Comment by Caballero-Arepa** [comment] 2023-02-13 18:54
> > because the unit icons should become fully opaque when selected
> 
> They shouldn't.

Yes they should.

I dont see why it shpuldn't apart from Civ 5.

Right now, the opacity sistem is becoming ever more confusing than how it was before.


Its very simple, if I or the game selects a unit it should be on 100% to denote the selected unit.

Dimming the icon when selected goes against any coherence.

**Comment by vegeta1k95** [comment] 2023-02-13 19:10
> I dont see why it shpuldn't apart from Civ 5.

Civ 5 dims icons of out-of-moves units, independent of selection. Look pictures above.

**Comment by vegeta1k95** [comment] 2023-02-13 19:11
> The unit opacity setting shouldn't affect the opacity when the unit selected.

But it isn't affecting. Look 50% pic, selected unit is 100% opaque.

**Comment by letstalkaboutdune** [comment] 2023-02-13 19:12
> > The unit opacity setting shouldn't affect the opacity when the unit selected.
> 
> But it isn't affecting. Look 50% pic, selected unit is 100% opaque.

The 50% pic is fine. I mean in the 100% pic, the model is selected but it is at 50% opacity.

**Comment by vegeta1k95** [comment] 2023-02-13 19:17
> The 50% pic is fine. I mean in the 100% pic, the model is selected but it is at 50% opacity.

As I said, because 100% pic behaviour is according to Civ 5 behaviour.

> Also what happens when the unit is not selected and out of moves?
100 - unit is half-opaque,  <100 - unit retains selected opacity.

**Comment by letstalkaboutdune** [comment] 2023-02-13 19:19
Ok well now you're not being internally consistent. If you want to match Civ 5, then opacity should be reduced from whatever the baseline setting is whenever a unit is out of moves.

**Comment by vegeta1k95** [comment] 2023-02-13 19:21
>  then opacity should be reduced from whatever the baseline setting is whenever a unit is out of moves.
It was like this. You requested different behaviour for <100 baseline setting.

**Comment by letstalkaboutdune** [comment] 2023-02-13 19:26
> > then opacity should be reduced from whatever the baseline setting is whenever a unit is out of moves.
> 
> It was like this. You requested different behaviour for <100 baseline setting. If I set 50% default opacity, then out-of-moves units will be at 25% opacity, which is almost transparent.

Yes, that's the way I originally implemented it. It's okay for units to be at 50% of setting opacity when out of moves, so if 50% is the setting then they will be 25% when out of moves.

**Comment by vegeta1k95** [comment] 2023-02-13 19:31
50% baseline, unit on the right is out of moves (so 25%)
![image](https://user-images.githubusercontent.com/32207817/218555563-08f6070a-35d8-463a-8bc1-f1e6a32e8d3d.png)
This okay?

**Comment by letstalkaboutdune** [comment] 2023-02-13 19:35
> 50% baseline, unit on the right is out of moves (so 25%) ![image](https://user-images.githubusercontent.com/32207817/218555563-08f6070a-35d8-463a-8bc1-f1e6a32e8d3d.png) This okay?

Yes, that looks right. What happens if you click the unit which is out of moves?

**Comment by vegeta1k95** [comment] 2023-02-13 19:36
> What happens if you click the unit which is out of moves?

![image](https://user-images.githubusercontent.com/32207817/218556654-445d1aac-a75c-4ab9-a10a-eedf09ca12a3.png)

**Comment by letstalkaboutdune** [comment] 2023-02-13 19:37
> > What happens if you click the unit which is out of moves?
> 
> ![image](https://user-images.githubusercontent.com/32207817/218556654-445d1aac-a75c-4ab9-a10a-eedf09ca12a3.png)

Yep, I think that's perfect, thanks!

**Comment by vegeta1k95** [comment] 2023-02-13 19:44
Seems like solved. 
I still need to correct selection sprites to be only outline not to interfere with transparent flag background, but that for another commit.
Can close this for now.

**Closed by vegeta1k95** 2023-02-13 19:44 UTC
Labels: bug

**Comment by letstalkaboutdune** [comment] 2023-02-13 21:17
> 

Please take a look at my original post for another part of the issue, the citizen worked tile icons are also getting dimmed when a unit is selected.

**Comment by vegeta1k95** [comment] 2023-02-13 21:23
> citizen worked tile icons are also getting dimmed when a unit is selected

This is not my change. It was like this before I came along: when military unit selected, overlays such as improvement icons and worker icons are dimmed. I think yairm considers them unimportant when you move your military, or something, idk.

I can remove dimming, but you better ask him.

**Comment by letstalkaboutdune** [comment] 2023-02-13 21:25
> 

I don't think this is true. Pretty sure if I go back a few versions this isn't the case.

**Comment by letstalkaboutdune** [comment] 2023-02-13 21:30
> No. [Proof](https://github.com/yairm210/Unciv/blob/92d3fa65e364015d425038be153e6defde8032f6/core/src/com/unciv/ui/worldscreen/WorldMapHolder.kt#L489).
> 
> Look at the date of that commit.

No, I'm good. You're really a pain in the ass to deal with, you know?

**Comment by vegeta1k95** [comment] 2023-02-13 21:41
Whatever dude. I fixed all the UI bugs you have reported rather quickly, including this one.

Dimming of worker icons is not a bug, and actually I don't like it too myself, I'd remove dimming.

**Comment by vegeta1k95** [comment] 2023-02-13 21:52
I created [PR](https://github.com/yairm210/Unciv/pull/8674).
If it will be approved, then you should be good.
