### ISSUE TITLE
Duplicate Nations Stack... and that's not good.

### ISSUE THREAD

**Issue by Caballero-Arepa** [yairm210/Unciv#4137] opened 2021-06-13 23:20 UTC
If you activate 2 or more mods, which have the same nation, but different uniques, they will stack, making such nation overpowered, or at least with a lot of uniques. 

An example is when you activate Rekmod and Latin American civs, there, Brazil, Argentina and Mexico will stack.

One solution is to have them separatedly. Let's imagine, when you have mods that have nations that would stack, they don't. So you select Mexico, and when selecting the nation, instead of showing directly the nation traits, it will show the different *leaders*, and when you select one, you can pick that leader and have the correspondent uniques. So if leader A is from rekmod, and leader B is from another mod; when you select leader A you will be playing with the mexico of rekmod, but if you pick leader B, you'll play the mexico of the other mod.

Now, there is a problem, and it is when both duplicate nations have the same leader, there I don't know at the moment what could be done.

Sorry if you don't understand me, I'll try to ilustrate it, or make any questions you want!

**Comment by ArchDuque-Pancake** [comment] 2021-06-13 23:21
Ah, this can also serve for the future when civ 6 is implemeted.

**Comment by Mape6** [comment] 2021-06-14 03:44
What about a mod sequence? 
The mods could be loaded in a sequence which can be adjusted by the user. The last loaded mod would then overwrite the nation's from the loaded mods before. 
So in your example, if you load Rekmod and after that Latin American Civs, you will play Mexico from the last loaded mod. If you change the sequence and put Rekmod in the last position, you will play Mexico from that mod. 
This solves the problem with stacked uniques and same leader names.

**Comment by ravignir** [comment] 2021-06-14 06:22
> 
> 
> Ah, this can also serve for the future when civ 6 is implemeted

civ6 is not going to be implemented.

> 
> 
> What about a mod sequence?
> The mods could be loaded in a sequence which can be adjusted by the user. The last loaded mod would then overwrite the nation's from the loaded mods before.
> So in your example, if you load Rekmod and after that Latin American Civs, you will play Mexico from the last loaded mod. If you change the sequence and put Rekmod in the last position, you will play Mexico from that mod.
> This solves the problem with stacked uniques and same leader names.

yes, but what about the mod that wants to add new things to existing nations or modify them?.

**Comment by Mape6** [comment] 2021-06-14 06:55
> yes, but what about the mod that wants to add new things to existing nations or modify them?.

The modder should then copy the nations information from Unciv into their mod and change, what they want. Then you have the original nation with new or changes attributes.

**Comment by yairm210** [comment] 2021-06-14 11:01
I understand the problem. The problem is that the nation objects override each other, but the buildings and units - which have different names - remain.

The way I can see to deal with this problem is v if there's a mod that 'adds' a nation, we will remove all unique buildings and units before adding the nation, so the last remaining will 'win'.

**Comment by ArchDuque-Pancake** [comment] 2021-06-15 00:50
`if there's a mod that 'adds' a nation, we will remove all unique buildings and units before adding the nation, so the last remaining will 'win'.`
I don't understand very well.

**Comment by ravignir** [comment] 2021-06-15 06:23
That is no a perfect solution, because there are mods that replace nations unique only. What about having some sort of option in ModOptions.json that will allow the mod creator to decide what to do?

**Comment by ArchDuque-Pancake** [comment] 2021-06-15 19:37
What if you do as what I said, but instead of showing the leaders, you show the mod from which the nation comes.
For example: Mexico: - From Mod1
                                 -From Mod2

**Comment by yairm210** [comment] 2021-06-15 21:33
I don't think you understand, there can't be more than 1 Mexico per game.

**Comment by yairm210** [comment] 2021-06-15 21:34
That goes against the entire way the game is built.

**Comment by ArchDuque-Pancake** [comment] 2021-06-15 22:37
Ok then, so after you pick one, you have choosen that mexico and no other player can be mexico.
So if I select mexico from mod-2, that Mexico will get chosen, and the mexico from mod-1 will "dissappear", making it not possible to chose more than 1 mexico.

**Comment by SomeTroglodyte** [comment] 2021-06-16 00:02
I would patch `CheckModLinksResult` to recognize the situation and classify it as error.
Do something to prevent multiple base ruleset mods being selected - is this already in or not?
Do something to prevent non-base mods meant for vanilla to be used with, say, deciv
Do something to prevent mods not suitable as "permanent visual" to be selected as such

Last two of these would probably require a mod author to provide a kind of compatibility list...? ModOptions.compatibleBaseRulesets -> could make isBaseRuleset obsolete, as equivalent to empty, and a compatibility check could automatically cover case 2. Suggested minimum and default = "Civ V - Vanilla".

**Comment by ArchDuque-Pancake** [comment] 2021-06-17 14:46
I think the mod options tbing wpuld work, but it still doesnt resolve this specific issue...

**Comment by SomeTroglodyte** [comment] 2021-06-18 07:17
> still doesnt resolve

A rule "A specific nation can at most appear in _one_ non-base ruleset mod in addition to 0-1 appearances in the selected base ruleset mod" _would_ resolve this specific issue, which is what I meant with "patch `CheckModLinksResult`" - on the new game screen, you would select the second Mexico-overloading mod, the check would fail, you'd get a toast describing the rule violation, and the second mod _stays_ deselected. You would know which other mod is blocking as the toast would tell you.

**Comment by ArchDuque-Pancake** [comment] 2021-06-19 14:07
So if I want to play with Bolivia as well, I cant, because the mod is deselected due to a duplicate nation...

**Comment by SomeTroglodyte** [comment] 2021-06-19 19:00
Well if you want to have Bolivia from mod 1 and Méjico from mod 2 in one game - no problem as long as mod 1 does not try to bring along another Méjico. In that case I'd ditch mod2 and go with mod 1's Mx, or hand-edit the mods locally, or get the mod authors to talk and resolve their diverging ideas for the ideal Mx... Hay muchas posibilidades.

Anyway, that's just my idea - easy conflict prevention.

**Comment by freddyhayward** [comment] 2021-06-20 02:51
Why not pass the problem back to modders? Someone already made "Mexico"? Call yours "Mexicans", "{Leader}'s Mexico", "{username}'s Mexico", "United States of Mexico".

**Comment by jahodovykolac** [comment] 2021-06-20 16:56
Or, a popup would show up saying "Civilization [name] already exists!", similar to non-existing units or terrains (e.g. older popup "Unit Composite Bowman doesn't exist in ruleset!")

**Comment by ArchDuque-Pancake** [comment] 2021-06-21 15:29
So basically, if there are 2 mexicoss in 2 mods, the mexico from the first selected mod will be the one that will prevail and be playable?
This is good, but it would get very complicated if there are more duplicate nations.

About the modder solving this problem, how could this be? Because, sure, you can just name "Estados Unidos de Mexico", but there would tecnically be 2 mexicos still.

**Comment by SomeTroglodyte** [comment] 2021-06-21 16:47
"first selected mod" - yes but nothing prevents you from de-selecting that first and making the other "the first".
And - the "name" property in the json is the primary key which will be unique in the running game's combined ruleset nations table no matter what. So - you rename the key to anything unique, you have a new unique nation. Translation results are a different matter. Technically you could do a mexico1 and a mexico2 in json then translate both to "Mexico" - even in English.properties - and they would be playable independently, no matter which if any other properties differ or not. Just remember properties like uniqueTo are foreign keys, so if you want to have all your mexicos to have the same unique building you'd have to pull the same trick for it.

**Comment by ArchDuque-Pancake** [comment] 2021-06-21 19:20
> yes but nothing prevents you from de-selecting that first and making the other "the first".

Exactly, that way I can choose what mexico I want.

**Comment by ArchDuque-Pancake** [comment] 2021-06-24 03:15
![21 sin título_20210623221231](https://user-images.githubusercontent.com/78449553/123196842-3ecd4e00-d470-11eb-9f3a-4db0bb6d9dfc.png)
This my original idea.
Once you select one, mexico will desappear from the list and you cant play more than two mexicos.

**Comment by SomeTroglodyte** [comment] 2021-06-24 19:13
> This my original idea

While I agree the 'end user' might be delighted...

You're missing something: At that point the _combined_ ruleset has already been built and must be. So, your two Mexicos would forcibly have different names to be distinct in their containing collection - I repeat these names are logical keys. And if you modify the names while the combined ruleset is built, maybe to literally what you show up there, colon and all, then getting all this to still translate properly under all possible circumstances gets to be a nightmare. And I think I could supply at least four to five complications of high complexity after your "select one", too lazy to explain (starting with what to do with foreign keys referencing those). Simpler is better - _far_ simpler here please. See: [KISS](https://en.wikipedia.org/wiki/KISS_principle) (and by 'please' I do not mean please better efforts on your part - I think we all get the issue, and one of these days someone will have a nice eureka moment - or the chuzpah to tackle this head-on)

**Comment by ArchDuque-Pancake** [comment] 2021-06-24 22:52
Ah, I see and comprehend.

**Comment by AdityaMH** [comment] 2021-06-28 08:18
And my suggestion is, Change nation selection to leader selection.
If they have different leader name but same nation, they become splitted. If they have same leader name and nation or same leader name and different nation, one of them will be removed.
Then make additional code first-tag and end-tag for each civ. That's make code easily detected to remove duplicate leader name.

So, civ selection not sorted or choosed by nation but by leader name.

**Comment by ravignir** [comment] 2021-06-28 10:00
same as in civ5. Nations are sorted by leaders.

**Comment by yairm210** [comment] 2021-07-02 13:15
May I remind you that Civ VI also has a leader who can lead two different nations. It's a whole mess, and I'm not dealing with that.

**Comment by AdityaMH** [comment] 2021-07-02 23:01
> May I remind you that Civ VI also has a leader who can lead two different nations. It's a whole mess, and I'm not dealing with that.

Let's see again my suggestion:
> If they have different leader name but same nation, they become splitted.

And

> If they have same leader name and nation or same leader name and different nation, one of them will be removed.

So, this very different from civ 6 civ sorting.
This only avoiding from stacking nation and not expected nation because using multiple mods.

**Comment by logicminimal** [comment] 2021-07-04 09:08
> May I remind you that Civ VI also has a leader who can lead two different nations. It's a whole mess, and I'm not dealing with that.

what about just adding different nations for every leader that just happen to share the same nation name??

like:

name: abc civ leader: a leader
name: def civ leader: a leader

**Comment by jahodovykolac** [comment] 2021-07-04 11:14
If I remember, in older versions, the list was not like France, Denmark, Germany etc., but Napoleon Bonaparte of France, Harald Bluetooth of Denmark, Otto von Bismarck of Germany etc. That could solve this problem, because you wouldn't choose a nation with a leader, not a leader leading a nation, but a combination of leader and nation.

**Comment by logicminimal** [comment] 2021-07-04 11:42
yep, they should be added as (different nations in code) different nations with the same name but with different leaders and bonuses, what do you think @yairm210

**Comment by SomeTroglodyte** [comment] 2021-07-04 13:18
C'mon guys, forget that. None of us is going to redesign key data structures that much in the foreseeable future. :dog2: :meat_on_bone: :persevere: ("a pack of dogs persevere in picking the meat off a carcass")

I'll code something when I have time to move some responsibility back to the modders, that should be enough. I'm thinking of a `compatibility` property in ModOptions.json, and unless that explicitly says otherwise, two nations with the same name (not counting vanilla ruleset) will simply not be allowed. You want it anyway, you fork the mod and do it yourself. Pondered the idea for a few weeks now and still think it's sound.

Leaving nation name technically as is and just fill it with "Evil Tyrant of Nowhere at all" - and `leadername` = "Evil Tyrant" - mod away, no problem. Once someone does that and complains where the leader name is duplicated in an offensive manner, we could consider patching the leader display code. Maybe not too shabby - I'll let the idea stew.

**Comment by logicminimal** [comment] 2021-08-14 14:14
idea on how to fix some incompatibilities

say there are two mods using the same civilization name: they will be shown as for instance Iroquois (rekmod) and İroques (somemod) and when you select one the other(s) get de activated, so nobody can ever select them

another hypotatical situation would be that two mods using same civ name and same leader name, in which case the same conditions apply in the first one,

but say a mod1 adds 1 civ, 2 leaders and mod2 adds 1 civ 1 leader of the same civilization, in this case the ones with the same leader name should be blacked out if one is chosen, but the other leader name should stay as it is basically another civilization

**Comment by ravignir** [comment] 2021-08-14 14:21
But what if mod B adds extra things to a civ from mod A, which also exists in mod C, but is a completely different civ, so mod B is not supposed to affect it?

**Comment by logicminimal** [comment] 2021-08-14 14:28
no idea

**Comment by ArchDuque-Pancake** [comment] 2021-08-14 14:48
> But what if mod B adds extra things to a civ from mod A, which also exists in mod C, but is a completely different civ, so mod B is not supposed to affect it?

Then it should have a different name.

**Comment by ravignir** [comment] 2021-08-14 17:10
> > But what if mod B adds extra things to a civ from mod A, which also exists in mod C, but is a completely different civ, so mod B is not supposed to affect it?
> 
> Then it should have a different name.

Then there is no problem at all :D

**Comment by logicminimal** [comment] 2021-08-14 17:11
so this couls be implemented

**Comment by xlenstra** [comment] 2021-08-14 18:03
> > But what if mod B adds extra things to a civ from mod A, which also exists in mod C, but is a completely different civ, so mod B is not supposed to affect it?
> 
> Then it should have a different name.

True, but that would be the responsibility of the mod makers and we can't enforce that. If mod makers do make two nations with the same name, we still have this exact problem.

**Comment by logicminimal** [comment] 2021-08-14 18:18
> > > But what if mod B adds extra things to a civ from mod A, which also exists in mod C, but is a completely different civ, so mod B is not supposed to affect it?
> > 
> > Then it should have a different name.
> 
> True, but that would be the responsibility of the mod makers and we can't enforce that. If mod makers do make two nations with the same name, we still have this exact problem.

just add leader (modname) or civilization (modname) to their names if there are more than 1 of the same civ

**Comment by ArchDuque-Pancake** [comment] 2021-08-14 19:19
I still push for separating the nations, not by civ name, but by leader name.

**Comment by xlenstra** [comment] 2021-08-14 19:36
> > > > But what if mod B adds extra things to a civ from mod A, which also exists in mod C, but is a completely different civ, so mod B is not supposed to affect it?
> > > 
> > > 
> > > Then it should have a different name.
> > 
> > 
> > True, but that would be the responsibility of the mod makers and we can't enforce that. If mod makers do make two nations with the same name, we still have this exact problem.
> 
> just add leader (modname) or civilization (modname) to their names if there are more than 1 of the same civ

But then you can't have mods adding abilities to civilizations of other mods

**Comment by xlenstra** [comment] 2021-08-14 19:36
> I still push for separating the nations, not by civ name, but by leader name.

Then you would still have the same problem, but with leader names instead of civilization names

**Comment by SomeTroglodyte** [comment] 2021-08-14 19:40
I say: If you shoot yourself in the knee, you've earned your pain. Mod and ~~moron~~ user problem, not an Unciv problem.

**Comment by logicminimal** [comment] 2021-08-14 20:33
> But then you can't have mods adding abilities to civilizations of other mods

just add a tag per civilization in nations.json "changesOriginalStats", dont know what happens if 2 mods try to change 1 mod thougg

**Comment by ArchDuque-Pancake** [comment] 2021-08-14 23:09
> But then you can't have mods adding abilities to civilizations of other mods

I dont think thats important.

> Then you would still have the same problem, but with leader names instead of civilization names

But there are more leaders for a civ. There a re more leaders of Poland than Polands.

**Comment by will-ca** [comment] 2021-09-01 03:01
The display name shouldn't be the internal ID. Mods that change existing civs, including civs from other mods, should deliberately use colliding IDs; Everything else should have a unique identifier that's separate from the displayed name.

**Comment by ravignir** [comment] 2021-09-01 07:27
Yes, but what if two mods happen to use the same ID by accident?

**Comment by logicminimal** [comment] 2021-09-01 07:37
> Yes, but what if two mods happen to use the same ID by accident?

bro damn

**Comment by xlenstra** [comment] 2021-09-01 07:42
> Yes, but what if two mods happen to use the same ID by accident?

If we go this route, I would make this the responsibility of the modder, and throw an error when trying to load in two mods with nations with the same ID and different names.

**Comment by ravignir** [comment] 2021-09-01 07:44
Another thing. Nation names as of now are not any different from ID.
So just use different nation name of you want a separate civ. Use the same nation name if you want to expand nation features.

I would only add something if someone wants to have multiple leaders, so it chcecks both leader name and nation name.

**Comment by xlenstra** [comment] 2021-09-01 07:54
> Another thing. Nation names as of now are not any different from ID.
> So just use different nation name of you want a separate civ. Use the same nation name if you want to expand nation features.
> 
> I would only add something if someone wants to have multiple leaders, so it chcecks both leader name and nation name.

That is basically the situation we have now, but people seem to be unhappy with that. And naming your nation "Mexico" does make more sense than having to name it "Mexico - 2" in order to avoid conflicts. Using numerical ID's would solve that, as long as mod makers all start at some high enough number that there are no unintentional conflicts.

**Comment by will-ca** [comment] 2021-09-01 13:08
@xlenstra Unless there's a technical reason not to, I suggest using string IDs and establishing a (non-binding) convention for naming things to be even safer, and make things clearer.

E.G.: `baseGame-France`, `modPackA-France`, `otherModPack.Spain`, `unciv.base.mexico`, `addon.steve123.mexico`.

**Comment by will-ca** [comment] 2021-09-01 13:11
Since people already go to some trouble to choose distinct names for themselves and their projects, including either author name or mod name in IDs by convention should solve the vast majority of name collisions while also making it easier to deliberate override other mods.

**Comment by ArchDuque-Pancake** [comment] 2021-09-01 17:50
> @xlenstra Unless there's a technical reason not to, I suggest using string IDs and establishing a (non-binding) convention for naming things to be even safer, and make things clearer.
> 
> E.G.: `baseGame-France`, `modPackA-France`, `otherModPack.Spain`, `unciv.base.mexico`, `addon.steve123.mexico`.

I agree with this, if the both, leader and nation name checking is not added, words rathen than numbers would be better for not so inteligent people.

**Comment by will-ca** [comment] 2021-09-01 18:21
@ArchDuque-Pancake ???? A variable-length string of dozens of permitted ASCII characters in a specific order objectively increases the size of the available namespace compared to a single integer, from a one-dimensional discrete axis and by a factor of at least `26**[length of string]`. Allowing for words lets the semantics of mods' relationships be included in a self-documenting way, objectively exposing more information and clarity to both modders and users than an arbitrary number would.

Numerical IDs would require either some sort of central coordination or random selection from a huge range to ensure no one chooses the same numbers. Neither would really eliminate ID collisions, and neither would carry any bonus human-readable metadata either.

Checking for leader name does nothing to solve this issue either, outside of a very specific and arbitrary edge case. You still can't have two mods that implement different stats if they use the same leader, and you'd also lose the ability to have one mod override another.

Words "rathen" than numbers has absolutely nothing to do with any smug euphemisms of not-so-"inteligent" people.

If anything, using a flat structure like integers or an patchy automated system like name checking is what would really be insulting to the intelligence of modders and users.

I would appreciate it if you kept your ego out of this technical suggestion.

**Comment by ArchDuque-Pancake** [comment] 2021-09-01 18:34
Eehhh and now what insect bite you?
I may not know how to code, but that doesn't mean that I am talking non-sence.

I don't think you know, but I see every dy people not being able to figure out what "uniques" are for. So having an ID would be more confusing to confusing to them for they don't know how it would work until they ask, that's what I'm refering to.

After all, I just agreed with you, nó sea cansón, si?

**Comment by will-ca** [comment] 2021-09-01 18:46
@ArchDuque-Pancake  There are many technical and workflow reasons to prefer a structured string to an integer, and calling other people dumb is not one of them.

Perhaps there is also a valid community and learning curve concern. But that can be better expressed without insulting anyone.

**Comment by ArchDuque-Pancake** [comment] 2021-09-01 23:00
Sorry if you feel insulted @will-ca , it is not my intention, nor to insult anyone in particular.
My point is that the sistem may, could, might and probably not be understanded by some, as they would know what it is for and are too lazy to check.

Then why did I say "not so intelligent"? Because it's the word that encircles the sort of people that wouldn't easily understand it.

Back to the point, yes, it may be more convinient to do the easier way, but at what cost? If it costs user expirience or not full solution to the problem, it is not actually useful. That is my worries.

**Comment by will-ca** [comment] 2021-09-01 23:58
I understand. I felt annoyed because I felt like you were oversimplifying a technical solution in a way that both degraded other people and undermined the other technical reasons for that solution, but I see now that you had an actual point based on experiences and observations with the current system.

I agree with your points about usability and getting a full solution.

(I might have personally phrased it differently, though. "Inattentive", instead of "not so intelligent". Or better yet, not even focused on other people's personal traits at all— I think the point could be made just by saying that words would be easier to understand than numbers, and you already get confused questions about existing systems— Keep the focus on the system, instead of the people using it. I get the feeling English may not be your first language? Congrats if so! Your English is far better than my French and Spanish. I'm just trying to explain why I misjudged your earlier comment.)

Thanks for your time. @ArchDuque-Pancake

**Comment by ArchDuque-Pancake** [comment] 2021-09-02 00:10
I understand you and feel you, I also get annoy when people seem malinterpreting things in areas I know well, so I think it's somewhat normal.

Yeah, altough I feel pretty confident with english, it's not my main language, but either way I overall struggle making my point clear at a pretty representative way.

Sorry for the inconvinience @will-ca

**Comment by MadManMoon** [comment] 2021-12-15 13:15
Small suggestion coming from a non-coder and non-modder with only the tiniest slice of knowledge about this dev work.

---

_Before I go on, a quick side thought which you can feel free to ignore ... I'll come back to it in a bit._

I'm sure that you already do this, but why not ensure that all mods contain a unique identifier at the UNCIV mod site level (I'm sure that GitHub has hidden IDs for repositories, perhaps that?)? This will always ensure that no mod can 'be' another mod.

---

### Unique IDs For Each Nation In A Given Game

Why not just have the game generate unique, **hidden**, names for each nation from any mod? 

This way any and all nations/leaders/whatever from any mods are handled as completely separate entities at all times. Obviously this doesn't deal with the user side UX/UI part, but handle that as a separate problem.

So, one possible way of handling that could be that every time a new nation is added to a game config (including base nations) it is given a database entry or unique identifier. That way, each entry on the list is a distinct, separate, entity, which isn't affected by others
(_this is **for example**, it does not **need** to be DB or ID based_) 

#### What If I Want My Mod To _Change_ Existing Nations?
If a modder wishes their mod to override existing nations/leaders/whatever, then:

1. Ensure all mods have a unique identifier at the unciv mod site level.
2. Use a very specific flag to do so.

By using the (previously mentioned) method of hierarchical mods overriding existing data or even other mods, you can ensure that there's no overlap.

The user experience would be that when they enable an 'override mod' that uses the specific flag to change something, then it warns them what it changes, and they have to accept that.

If the user then adds another mod that further either modifies the nation (for example) or even the previously loaded mod (located by #1) then they have to accept _those_ changes.

This can obviously scale. :-)

Additionally, as long as it's flagged as an 'override mod' (or that specific part of the mod is flagged as such) then it will only affect the specific part of the game it's aiming for. PLUS it won't affect other mods, unless it specifically targets their unique identifier.

**Comment by yairm210** [comment] 2023-03-19 17:14
Closing as 'not in roadmap' as part of our cleanup
The current setup is good enough for any mod that wants to avoid this problem, and the complexity of the offered solutions is simply not worth whatever benefit it may give

**Closed by yairm210** 2023-03-19 17:14 UTC
Labels: feature
