### ISSUE TITLE
Cannot enable Bubbly Borders and 5Hex Tileset at the same time

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#7879] opened 2022-09-30 20:39 UTC
**Platform**
Windows 11 64 bit

**Version**
4.2.11 (Build 755)

**Describe the bug**
Same as Title.
I tried enabling `Permanent Audiovisual Mod` option for both mods but it doesn't work.
No Bubbly Borders over 5Hex Tileset.

**Comment by yairm210** [comment] 2022-10-02 05:18
This is not a bug, but a feature request.
Bubbly borders defines new border images for specific tilesets, of which 5hex is not in the list.
The feature request is 'make it possible to define mod images for all tilesets at once'

**Comment by touhidurrr** [comment] 2022-10-02 10:58
> Bubbly borders defines new border images for specific tilesets, of which 5hex is not in the list.

Oh, so it worked like that. Didn't know that.

**Comment by will-ca** [comment] 2023-03-11 14:07
> > Bubbly borders defines new border images for specific tilesets, of which 5hex is not in the list.
> 
> Oh, so it worked like that. Didn't know that.

Yeah— IIRC, my intention was that tilesets which desire it should be updated to include their *own* themed border images— "Bubbly Borders" just overrode FantasyHex instead because it was easier to make an example/reference implementation that way. Personally, I also had been thinking about making a bunch of tilesets with fun theming like old-timey medieval antique maps, blueprint lines, abstract art, sketchy pencil drawing looks, etc., for which the border images would be tightly coupled to the rest of the tileset.

> The feature request is 'make it possible to define mod images for all tilesets at once'

Hm. Currently #5852 already allows tilesets to pull images from other tilesets. Images defined for `FantasyHex` or `Default` should automatically be available in all other tilesets as long as the other tilesets don't deliberately disable `.fallbackTileset`, but at a lower priority than images from the tileset itself, I *think*. Does allowing tileset mods to arbitrarily override other tilesets at a *higher* priority make a lot of sense?

---

My apologies to @yairm210 for leaving a bunch of open pull requests and issues when I stopped having the ability to contribute to this project last year, BTW! (And for avoiding this repository in shame ever since then.)

**Comment by yairm210** [comment] 2023-03-11 19:52
I think I'll close this as "wontfix" for now since it's easily "solvable" and there aren't a lot of tilesets

**Closed by yairm210** 2023-03-11 19:52 UTC
Labels: feature
