### ISSUE TITLE
When attack enemy city game crashes

### ISSUE THREAD

**Issue by Griden1** [yairm210/Unciv#8611] opened 2023-02-07 06:23 UTC
**Platform****Platform:** Android
**Version:** 4.4.10 (Build 807)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.worldscreen.WorldScreen`

--------------------------------

Device Model: M2006C3MNG
API Level: 29

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.ui.worldscreen.bottombar.BattleTableHelpers$flashWoundedCombatants$getMapActorsForCombatant$1.invokeSuspend(BattleTableHelpers.kt:27)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at kotlin.sequences.SequenceBuilderIterator.yieldAll(SequenceBuilder.kt:172)
	at kotlin.sequences.SequenceScope.yieldAll(SequenceBuilder.kt:92)
	at com.unciv.ui.worldscreen.bottombar.BattleTableHelpers$flashWoundedCombatants$actorsToFlashRed$1.invokeSuspend(BattleTableHelpers.kt:37)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at com.unciv.ui.worldscreen.bottombar.BattleTableHelpers.flashWoundedCombatants(BattleTableHelpers.kt:88)
	at com.unciv.ui.worldscreen.bottombar.BattleTable.onAttackButtonClicked(BattleTable.kt:309)
	at com.unciv.ui.worldscreen.bottombar.BattleTable.access$onAttackButtonClicked(BattleTable.kt:37)
	at com.unciv.ui.worldscreen.bottombar.BattleTable$simulateBattle$3.invoke(BattleTable.kt:280)
	at com.unciv.ui.worldscreen.bottombar.BattleTable$simulateBattle$3.invoke(BattleTable.kt:279)
	at com.unciv.ui.utils.extensions.Scene2dExtensionsKt$onClick$1.invoke(Scene2dExtensions.kt:325)
	at com.unciv.ui.utils.extensions.Scene2dExtensionsKt$onClick$1.invoke(Scene2dExtensions.kt:325)
	at com.unciv.ui.utils.extensions.OnClickListener.clicked(Scene2dExtensions.kt:305)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.UncivStage.access$touchUp$s80204510(UncivStage.kt:15)
	at com.unciv.ui.UncivStage$touchUp$1.invoke(UncivStage.kt:72)
	at com.unciv.ui.UncivStage$touchUp$1.invoke(UncivStage.kt:72)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.UncivStage.touchUp(UncivStage.kt:72)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:426)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:472)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1581)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1280)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```

**Comment by Gualdimar** [comment] 2023-02-07 09:57
Was fixed in 4.4.11. 
Duplicate of #8596

**Comment by Griden1** [comment] 2023-02-07 10:00
Okay, thanks.
Can i update game now or need some time?

**Comment by Gualdimar** [comment] 2023-02-07 10:33
it should be your decision)

**Closed** 2023-02-07 11:09 UTC
Labels: bug
