### ISSUE TITLE
"EffectBeforeCause" seems not work normally on "Simplified_Chinese.properties"

### ISSUE THREAD

**Issue by iamlibertybell** [yairm210/Unciv#8561] opened 2023-02-03 03:33 UTC
**Platform**
Linux 64bit

**Version**
4.4.7 (804)

**Describe the bug**
EffectBeforeCause = false
It should be "由于建造了[buildingName]，您可以选择一项免费的政策" ranther than "您可以选择一项免费的政策由于建造了[buildingName]，"

**To Reproduce**
1. Play the Game
2. Finished Wonder that provide free Policy
3. See error

**Screenshots**
![EffectBeforeCause](https://user-images.githubusercontent.com/72909724/216505933-ac19d6bb-5f92-40c5-9a1b-79f958440c07.png)

**Comment by iamlibertybell** [comment] 2023-02-03 03:37
[Autosave-Germany-494.zip](https://github.com/yairm210/Unciv/files/10575310/Autosave-Germany-494.zip)
[Autosave-Germany-495.zip](https://github.com/yairm210/Unciv/files/10575313/Autosave-Germany-495.zip)
It happens on turn 495.

**Comment by nacro711072** [comment] 2023-02-04 15:23
🧐  It works for me.

**Comment by yairm210** [comment] 2023-02-05 22:43
I'm not getting this problem at all
![image](https://user-images.githubusercontent.com/8366208/216850161-11fb3f9d-5036-492f-81c9-6e02aba9fd3d.png)

Try upgrading to latest version perhaps?

**Comment by yairm210** [comment] 2023-02-09 17:35
Closing "not reproducible"

**Closed by yairm210** 2023-02-09 17:35 UTC
Labels: bug
